function l_toe_frame = left_toe_frame(model)
    %
    
    l_knee_frame = model.Joints(getJointIndices(model, 'q2_left'));
    l_toe_frame = CoordinateFrame(...
        'Name','LeftToe',...
        'Reference',l_knee_frame,...
        'P',[0,0,0.4],...
        'R',[pi,0,0]... 
        );
    
    
end