function r_toe_frame = right_toe_frame(model)
    %
    
    r_knee_frame = model.Joints(getJointIndices(model, 'q2_right'));
    r_toe_frame = CoordinateFrame(...
        'Name','RightToe',...
        'Reference',r_knee_frame,...
        'P',[0,0,0.4],...
        'R',[pi,0,0]... 
        );
    
    
end