function torso = torso_frame(model)
    %
    pelvis_frame = model.Joints(getJointIndices(model, 'BaseRotY'));
    torso = CoordinateFrame(...
        'Name','Torso',...
        'Reference',pelvis_frame,...
        'P',[0,0,0.63],...
        'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
        );
            
end