AMBER Suite: utils/mathlink/cell2tensor.m File Reference
cell2tensor.m File Reference
Convert a cell array to a Mathematica tensor.
Functions
function expr = cell2tensor (X, varargin)
Convert a cell array to a Mathematica tensor.
Detailed Description
Convert a cell array to a Mathematica tensor.
Definition in file cell2tensor.m.
Function Documentation
function expr = cell2tensor (X, varargin)
Convert a cell array to a Mathematica tensor.
Author
ayonga
Date
2016-11-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file cell2tensor.m.
References general2math(), and implode().
Referenced by KinematicGroup.compile(), KinematicExpr.compile(), general2math(), KinematicOrientation.getJacMathCommand(), KinematicContact.getJacMathCommand(), KinematicOrientation.getKinMathCommand(), and KinematicContact.getKinMathCommand().