FROST: utils/mathlink/check_var_exist.m File Reference
check_var_exist.m File Reference
A wrapper function that checks if a variable has been assigned to a value in Mathematica.
Functions
function logical status = check_var_exist (char var)
A wrapper function that checks if a variable has been assigned to a value in Mathematica.
Detailed Description
A wrapper function that checks if a variable has been assigned to a value in Mathematica.
Definition in file check_var_exist.m.
Function Documentation
function logical status = check_var_exist (char var)
A wrapper function that checks if a variable has been assigned to a value in Mathematica.
Author
ayonga
Date
2016-11-23
Author
Ayonga Hereid ayong.nosp@m.a27@.nosp@m.gmail.nosp@m..com
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Parameters
var a string or a cell string of the symbolic variable name
Return values
status returns true if the variable exists and has been assigned a value, returns false otherwise.
Definition at line 17 of file check_var_exist.m.
Referenced by KinematicGroup.compile(), Kinematics.compile(), KinematicExpr.compile(), Kinematics.export(), KinematicExpr.export(), and Kinematics.print().