FROST: RigidImpact Class Reference
RigidImpact Class Reference
RigidImpact represents a rigid body impact map assuming that the impact is plastic and occurs instantaneously.
Public Member Functions
RigidImpact (char name,RigidLinks model,char event)
the class constructin method
function obj = addImpactConstraint (HolonomicConstraint constr)
Adds an impact constraint to the rigid impact map.
function obj = removeImpactConstraint (cellstr name)
Remove impact (holonomic) constraints defined for the system.
function TrajectoryOptimization nlp = rigidImpactConstraint (TrajectoryOptimization nlp, src, tar,struct bounds, varargin)
Impose system specific constraints as NLP constraints for the trajectory optimization problem.
function [ xn , lambda ] = calcDiscreteMap (t, x, varargin)
calculates the discrete map of the dynamical system that maps xminus from xplus. Subclasses must implement this method by its own.
Public Member Functions inherited from DiscreteDynamics
DiscreteDynamics (char type,char name,char event)
the constructor function for DiscreteDynamics class objects
function obj = addState (SymVariable xplus, xminus,SymVariable dxplus, dxminus)
overload the superclass addState method with fixed state fields
function TrajectoryOptimization nlp = IdentityMapConstraint (TrajectoryOptimization nlp, src, tar,struct bounds, varargin)
Impose system specific constraints as NLP constraints for the trajectory optimization problem.
Public Attributes
HolonomicConstraint ImpactConstraints
The impact constraints (holonomic)
matrix R
The coordinate relabeling matrix.
Public Attributes inherited from DiscreteDynamics
function_handle UserNlpConstraint
A handle to a function called by a trajectory optimization NLP to enforce system specific constraints.
char EventName
The event name that triggers the discrete dynamics.
Detailed Description
RigidImpact represents a rigid body impact map assuming that the impact is plastic and occurs instantaneously.
Definition at line 17 of file RigidImpact.m.
Constructor & Destructor Documentation
RigidImpact.RigidImpact (char name, RigidLinks model, char event)
the class constructin method
Parameters
name the name of the rigid impact dynamics
model the RigidLinks model object
event the event name of the rigid impact
Required fields of model:
Definition at line 83 of file RigidImpact.m.
References DiscreteDynamics.addState(), DiscreteDynamics.DiscreteDynamics(), and R.
Member Function Documentation
function obj = RigidImpact.addImpactConstraint (HolonomicConstraint constr)
Adds an impact constraint to the rigid impact map.
Parameters
constr the expression of the constraints
Definition at line 144 of file RigidImpact.m.
function [ xn , lambda ] = RigidImpact.calcDiscreteMap (t, x, varargin)
calculates the discrete map of the dynamical system that maps xminus from xplus. Subclasses must implement this method by its own.
Note
By default, this discrete map will be a Identity map. For specific discrete map, please implement as a subclass of this class
Parameters
t the time instant
varargin
Definition at line 18 of file calcDiscreteMap.m.
References R.
Referenced by removeImpactConstraint().
function obj = RigidImpact.removeImpactConstraint (cellstr name)
Remove impact (holonomic) constraints defined for the system.
Parameters
name the name of the constraint
Generated fields of obj:
Definition at line 186 of file RigidImpact.m.
References calcDiscreteMap(), and rigidImpactConstraint().
function TrajectoryOptimization nlp = RigidImpact.rigidImpactConstraint (TrajectoryOptimization nlp, src, tar, struct bounds, varargin)
Impose system specific constraints as NLP constraints for the trajectory optimization problem.
Parameters
nlp an trajectory optimization NLP object of the system
bounds a struct data contains the boundary values
varargin
Definition at line 18 of file rigidImpactConstraint.m.
References R.
Referenced by removeImpactConstraint().
Member Data Documentation
RigidImpact.ImpactConstraints
The impact constraints (holonomic)
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 42 of file RigidImpact.m.
RigidImpact.R
The coordinate relabeling matrix.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
This property has custom functionality when its value is changed.
Definition at line 55 of file RigidImpact.m.
Referenced by calcDiscreteMap(), RigidImpact(), and rigidImpactConstraint().
The documentation for this class was generated from the following files:
robotics/@RigidImpact/RigidImpact.m
robotics/@RigidImpact/calcDiscreteMap.m
robotics/@RigidImpact/rigidImpactConstraint.m