FROST: NlpVariable Class Reference
NlpVariable Class Reference
This class provides a data structure for NLP optimization variables.
Public Member Functions
NlpVariable (varargin)
The class constructor function.
function obj = setIndices (integer index)
Sets indinces of the Nlp Variables.
function obj = setBoundary (colvec lowerbound,colvec upperbound)
Sets the lower/upper boundary value for a NLP variable.
function obj = setInitialValue (x)
Sets a typical initial value for the NLP variables. This value will be used to assign the initial value for the NLP solver.
function obj = setName (char name)
Specifies the name of the NLP variable.
function obj = setDimension (double dim)
Sets the dimension of the NLP variable vector.
function obj = updateProp (varargin)
This function updates the properties of the class object based on the input name-value pair arguments.
Public Attributes
char Name
A string that specifies the name of the optimization variable.
integer Dimension
The dimension the optimization variable.
colvec InitialValue
The typical value of the variable.
colvec LowerBound
The lower limit of the optimization variable.
colvec UpperBound
The upper limit of the optimization variable.
colvec Indices
The index of the current variable in an array of NlpVariable objects.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Detailed Description
This class provides a data structure for NLP optimization variables.
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file NlpVariable.m.
Constructor & Destructor Documentation
NlpVariable.NlpVariable (varargin)
The class constructor function.
Parameters
varargin variable nama-value pair input arguments, in detail:
NlpVariable (Name, Dimension, lb, ub, x0)
Required Parameters for varargin:
Name name of the variable
Dimension dimension of the variable
lb lower limit
ub upper limit
x0 a typical value of the variable
Definition at line 128 of file NlpVariable.m.
References setBoundary(), setDimension(), setIndices(), setInitialValue(), setName(), and updateProp().
Member Function Documentation
function obj = NlpVariable.setBoundary (colvec lowerbound, colvec upperbound)
Sets the lower/upper boundary value for a NLP variable.
Note
If the boundary values are not specified, then use -Inf/Inf by default.
If the NLP variable is a vector (Dimension > 1) but the lower/upper bound values are specified as a scalar, we set the lower/upper bounds of all element with the same scalar value.
Ignore a particular boundary if it is given as empty
Parameters
lowerbound the lower boundary values
upperbound the upper boundary values
Generated fields of obj:
Definition at line 18 of file setBoundary.m.
References handle.transpose.
Referenced by NlpVariable(), and updateProp().
function obj = NlpVariable.setDimension (double dim)
Sets the dimension of the NLP variable vector.
Parameters
dim the dimension of the vector
Generated fields of obj:
Definition at line 18 of file setDimension.m.
Referenced by NlpVariable().
function obj = NlpVariable.setIndices (integer index)
Sets indinces of the Nlp Variables.
Parameters
index the indices of the variables
Generated fields of obj:
Definition at line 18 of file setIndices.m.
Referenced by NlpVariable().
function obj = NlpVariable.setInitialValue (x)
Sets a typical initial value for the NLP variables. This value will be used to assign the initial value for the NLP solver.
Note
If the initial value is not given, then use the middle value of the lower/upper boundaries.
Parameters
x0 an array of initial value of the NLP variables
Generated fields of obj:
Definition at line 18 of file setInitialValue.m.
References handle.transpose.
Referenced by NlpVariable(), and updateProp().
function obj = NlpVariable.setName (char name)
Specifies the name of the NLP variable.
Parameters
name the name character
Generated fields of obj:
Definition at line 18 of file setName.m.
Referenced by NlpVariable().
function obj = NlpVariable.updateProp (varargin)
This function updates the properties of the class object based on the input name-value pair arguments.
Parameters
varargin variable nama-value pair input arguments, in detail:
updateProp (Dimension, lb, ub, x0)
Required Parameters for varargin:
Dimension dimension of the variable
lb lower limit
ub upper limit
x0 a typical value of the variable
Definition at line 18 of file updateProp.m.
References setBoundary(), and setInitialValue().
Referenced by NlpVariable().
Member Data Documentation
NlpVariable.Dimension
The dimension the optimization variable.
When we define a optimization variable, we assume that it represnts a vector of variable that belongs to a particular group. For example, the joint configurations q and control inputs u. The dimension specifies the length of this vector.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 50 of file NlpVariable.m.
NlpVariable.Indices
The index of the current variable in an array of NlpVariable objects.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 111 of file NlpVariable.m.
NlpVariable.InitialValue
The typical value of the variable.
You can specify a typical value for the variable explicity. If not given, this value will be determined by the upper/lower boundary of the variable. If both upper/lower boundary values are infinity, then we set the typical value as zeros. If one of the upper/lower boundary values is infinity, then the typical value will be the non-infinity boundary value. Otherwise, the typical value will be the middle point of the two boundary values.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 67 of file NlpVariable.m.
NlpVariable.LowerBound
The lower limit of the optimization variable.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 87 of file NlpVariable.m.
NlpVariable.Name
A string that specifies the name of the optimization variable.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 38 of file NlpVariable.m.
NlpVariable.UpperBound
The upper limit of the optimization variable.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 99 of file NlpVariable.m.
The documentation for this class was generated from the following files:
nlp/@NlpVariable/NlpVariable.m
nlp/@NlpVariable/setBoundary.m
nlp/@NlpVariable/setDimension.m
nlp/@NlpVariable/setIndices.m
nlp/@NlpVariable/setInitialValue.m
nlp/@NlpVariable/setName.m
nlp/@NlpVariable/updateProp.m