FROST: HolonomicConstraint Class Reference
HolonomicConstraint Class Reference
HolonomicConstraint: represents a group of holonomic constraints of a dynamical systems.
Public Member Functions
HolonomicConstraint (DynamicalSystem model, h,SymExpression name, varargin)
The class constructor function.
function obj = configure ()
compiles the derivatives and Jacobian of the actual/desired outputs functions
function nlp = imposeNLPConstraint (nlp)
impose holonomic objaints as NLP objaints in the trajectory optimization problem nlp of the dynamical system
function [ Jh , dJh ] = calcJacobian (x, dx)
calculate the holonomic constraints, Jacobian and its time derivatives
function h = calcConstraint (colvec x)
calculate the holonomic constraints
function export (char export_path,varargin varargin)
export the symbolic expressions of the constraints matrices and vectors and compile as MEX files.
function obj = setJacobian (SymExpression jac)
Jacobian matrix sets the Jacobian matrix of the holonomic constraints if it is provided directly by the users.
function obj = setDerivativeOrder (integer degree)
RelativeDegree sets the highest derivative order of holonomic constraints in order to enforce as bilateral constraints of the system.
function obj = setConstrLabel (cellstr label)
OutputLabel sets the naming labels of outputs.
function name = validateName (name)
Name.
Public Attributes
integer Dimension
The dimension of the virtual constraints.
SymVariable Param
The symbolic representation of constant parameter value hd that the holonomic constraints associated wtih.
SymVariable Input
The symbolic representation of the input variables associated with the holonomic constraints.
char Name
The name of the virtual constraints.
char ConstrLabel
The label of the holonomic constraint.
integer DerivativeOrder
The highest order of derivatives to enforce the holonomic constraints. This is the same as the relative degree of a virtual constraint.
SymFunction ConstrExpr
The holonomic constraint expression.
SymFunction ConstrJac
The Jacobian matrix of the holonomic constraitns.
char ParamName
The name of the parameter variable hd associated with the holonomic constraints.
char InputName
The name othe input variables (external forces, etc.) associated with the holonomic constraints.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Protected Attributes
DynamicalSystem Model
The dynamical system model.
SymFunction h_
The holonomic constraint expression.
SymFunction Jh_
The Jacobian matrix of the holonomic constraint expression.
SymFunction dh_
The first order derivative of the holonomic constraint expression.
SymFunction dJh_
The first order derivative of the Jacobian matrix of the holonomic constraint expression.
SymFunction ddh_
The second order derivatives of the holonomic constraints expression.
Detailed Description
HolonomicConstraint: represents a group of holonomic constraints of a dynamical systems.
A holonomic constraint is defined as a function of state variables that equals to constants, i.e., h(x) == hd
Author
ayonga
Date
2017-04-20
Copyright (c) 2016-2017, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file HolonomicConstraint.m.
Constructor & Destructor Documentation
HolonomicConstraint.HolonomicConstraint (DynamicalSystem model, h, SymExpression name, varargin)
The class constructor function.
Parameters
model the dynamical system model in which the virtual constraints are defined
h the symbolic expression of the constraints
name the name of the virtual constraints
varargin optional parameters. In details
HolonomicConstraint (..., ConstrLabel, Jacobian)
Required Parameters for varargin:
ConstrLabel
Jacobian
Required fields of model:
Definition at line 311 of file HolonomicConstraint.m.
References calcConstraint(), calcJacobian(), configure(), imposeNLPConstraint(), and validateName().
Member Function Documentation
function h = HolonomicConstraint.calcConstraint (colvec x)
calculate the holonomic constraints
Parameters
x the states
Return values
h the value of the holonomic constraint
Definition at line 18 of file calcConstraint.m.
Referenced by HolonomicConstraint().
function [ matrix Jh , matrix dJh ] = HolonomicConstraint.calcJacobian (x, dx)
calculate the holonomic constraints, Jacobian and its time derivatives
Parameters
x the states
dx the first order derivatives
Return values
Jh the first-order Jacobian of the constraint
dJh the time derivative of the Jacobian matrix
Definition at line 18 of file calcJacobian.m.
Referenced by HolonomicConstraint().
function obj = HolonomicConstraint.configure ()
compiles the derivatives and Jacobian of the actual/desired outputs functions
Generated fields of obj:
Definition at line 18 of file configure.m.
Referenced by HolonomicConstraint().
function HolonomicConstraint.export (char export_path, varargin varargin)
export the symbolic expressions of the constraints matrices and vectors and compile as MEX files.
Parameters
export_path the path to export the file
varargin variable input parameters
export (..., Vars, File, ForceExport, BuildMex, Namespace)
Required Parameters for varargin:
Vars a list of symbolic variables
File the (full) file name of exported file
ForceExport force the export
BuildMex flag whether to MEX the exported file
Namespace the namespace of the function
Definition at line 422 of file HolonomicConstraint.m.
function TrajectoryOptimization nlp = HolonomicConstraint.imposeNLPConstraint (nlp)
impose holonomic objaints as NLP objaints in the trajectory optimization problem nlp of the dynamical system
Parameters
nlp the trajectory optimization NLP
Definition at line 18 of file imposeNLPConstraint.m.
Referenced by HolonomicConstraint().
function obj = HolonomicConstraint.setConstrLabel (cellstr label)
OutputLabel sets the naming labels of outputs.
Parameters
label the cell array of labels
Generated fields of obj:
Definition at line 510 of file HolonomicConstraint.m.
function obj = HolonomicConstraint.setDerivativeOrder (integer degree)
RelativeDegree sets the highest derivative order of holonomic constraints in order to enforce as bilateral constraints of the system.
Parameters
degree derivative order
Generated fields of obj:
Definition at line 483 of file HolonomicConstraint.m.
function obj = HolonomicConstraint.setJacobian (SymExpression jac)
Jacobian matrix sets the Jacobian matrix of the holonomic constraints if it is provided directly by the users.
Parameters
jac the jacobian matrix
Generated fields of obj:
Definition at line 456 of file HolonomicConstraint.m.
function name = HolonomicConstraint.validateName (name)
Name.
Definition at line 535 of file HolonomicConstraint.m.
Referenced by HolonomicConstraint().
Member Data Documentation
HolonomicConstraint.ConstrExpr
The holonomic constraint expression.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 139 of file HolonomicConstraint.m.
HolonomicConstraint.ConstrJac
The Jacobian matrix of the holonomic constraitns.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 152 of file HolonomicConstraint.m.
HolonomicConstraint.ConstrLabel
The label of the holonomic constraint.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 106 of file HolonomicConstraint.m.
HolonomicConstraint.ddh_ protected
The second order derivatives of the holonomic constraints expression.
Definition at line 287 of file HolonomicConstraint.m.
HolonomicConstraint.DerivativeOrder
The highest order of derivatives to enforce the holonomic constraints. This is the same as the relative degree of a virtual constraint.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 119 of file HolonomicConstraint.m.
HolonomicConstraint.dh_ protected
The first order derivative of the holonomic constraint expression.
Definition at line 264 of file HolonomicConstraint.m.
HolonomicConstraint.Dimension
The dimension of the virtual constraints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 45 of file HolonomicConstraint.m.
HolonomicConstraint.dJh_ protected
The first order derivative of the Jacobian matrix of the holonomic constraint expression.
Definition at line 274 of file HolonomicConstraint.m.
HolonomicConstraint.h_ protected
The holonomic constraint expression.
Definition at line 243 of file HolonomicConstraint.m.
HolonomicConstraint.Input
The symbolic representation of the input variables associated with the holonomic constraints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 72 of file HolonomicConstraint.m.
HolonomicConstraint.InputName
The name othe input variables (external forces, etc.) associated with the holonomic constraints.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 179 of file HolonomicConstraint.m.
HolonomicConstraint.Jh_ protected
The Jacobian matrix of the holonomic constraint expression.
Definition at line 253 of file HolonomicConstraint.m.
HolonomicConstraint.Model protected
The dynamical system model.
Definition at line 232 of file HolonomicConstraint.m.
HolonomicConstraint.Name
The name of the virtual constraints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 90 of file HolonomicConstraint.m.
HolonomicConstraint.Param
The symbolic representation of constant parameter value hd that the holonomic constraints associated wtih.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 58 of file HolonomicConstraint.m.
HolonomicConstraint.ParamName
The name of the parameter variable hd associated with the holonomic constraints.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 165 of file HolonomicConstraint.m.
The documentation for this class was generated from the following files:
system/@HolonomicConstraint/HolonomicConstraint.m
system/@HolonomicConstraint/calcConstraint.m
system/@HolonomicConstraint/calcJacobian.m
system/@HolonomicConstraint/configure.m
system/@HolonomicConstraint/imposeNLPConstraint.m