FROST: Guard Class Reference
Guard Class Reference
Guard defines a switching surface or a guard of a hybrid system model.
Public Member Functions
Guard (name, varargin)
the class constructor function
function thres = calcThreshold (double t,colvec qe,colvec dqe)
Calculates the threshold value of the guard condition.
function obj = setCondition (cond)
function obj = setDirection (direction)
function obj = setResetMap (RigidBodyModel model,logical rigid_impact,matrix relabel_matrix,KinematicContact reset_point)
Sets the reset map for the current domain.
function x_post = calcResetMap (RigitBodyModel model, x_pre,Domain target)
Updates the system states using the reset map associated with the discontinuous transition to the current domain to get the initial states of the current domain.
Public Attributes
char Name
This is the name of the object that gives the object an universal identification.
char Condition
The guard condition of the switching surface.
integer Direction
The direction of the switching surface.
struct ResetMap
% Reset map A reset map of system states associated with the guard
Detailed Description
Guard defines a switching surface or a guard of a hybrid system model.
Author
ayonga
Date
2016-09-29
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file Guard.m.
Constructor & Destructor Documentation
Guard.Guard (name, varargin)
the class constructor function
Required fields of ResetMap:
RigidImpact — indicates whether it goes through a rigid impact
RelabelMatrix — the coordinate relabel matrix
ResetPoint — a point to be reset to the origin (0,0,0)
Definition at line 104 of file Guard.m.
References setCondition(), and setDirection().
Member Function Documentation
function colvec x_post = Guard.calcResetMap (RigitBodyModel model, x_pre, Domain target)
Updates the system states using the reset map associated with the discontinuous transition to the current domain to get the initial states of the current domain.
Parameters
model the robot model
target the target domain
qe_pre pre-guard joint configuration
dqe_pre pre-guard velocities
Return values
x_post post reset map states
Required fields of model:
Required fields of target:
Definition at line 18 of file calcResetMap.m.
References Kinematics.Funcs, and Domain.HolonomicConstr.
Referenced by setDirection().
function thres = Guard.calcThreshold (double t, colvec qe, colvec dqe)
Calculates the threshold value of the guard condition.
To use particular threshold value, such as ground heights, make sure to overwrite this function in the subclass.
Parameters
t the time instant
qe the joint configuration
dqe the joint velocities
Definition at line 142 of file Guard.m.
function obj = Guard.setCondition (cond)
Definition at line 162 of file Guard.m.
Referenced by Guard().
function obj = Guard.setDirection (direction)
Definition at line 171 of file Guard.m.
References calcResetMap(), and setResetMap().
Referenced by Guard().
function obj = Guard.setResetMap (RigidBodyModel model, logical rigid_impact, matrix relabel_matrix, KinematicContact reset_point)
Sets the reset map for the current domain.
Note
The reset point can be specified as a struct with the following
required fields
ParentLink
Offset
Parameters
model a rigid body model
rigid_impact indicates whether it goes through a rigid impact
relabel_matrix coordinate relabelling matrix
reset_point a point to be reset to the origin (0,0,0)
Required fields of model:
Generated fields of obj:
Definition at line 18 of file setResetMap.m.
References KinematicContact.ContactType, KinematicContact.ModelType, Kinematics.Name, RigidBodyModel.nDof, Kinematics.Prefix, and RigidBodyModel.Type.
Referenced by setDirection().
Member Data Documentation
Guard.Condition
The guard condition of the switching surface.
The guard condition must be a member of unilateral constraints of the source domain.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 53 of file Guard.m.
Guard.Direction
The direction of the switching surface.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 68 of file Guard.m.
Guard.Name
This is the name of the object that gives the object an universal identification.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 40 of file Guard.m.
Guard.ResetMap
% Reset map A reset map of system states associated with the guard
The reset map will be applied to the target continuous domain prior to the beginning of the domain
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 80 of file Guard.m.
The documentation for this class was generated from the following files:
system/@Guard/Guard.m
system/@Guard/calcResetMap.m
system/@Guard/setResetMap.m