FROST: DiscreteDynamics Class Reference
DiscreteDynamics Class Reference
Discrete event dynamic system governed by discrete transition map and triggered by discrete events.
Public Member Functions
DiscreteDynamics (char type,char name,char event)
the constructor function for DiscreteDynamics class objects
function obj = addState (SymVariable x,SymVariable xn,SymVariable dx,SymVariable dxn)
overload the superclass addState method with fixed state fields
function xn = calcDiscreteMap (double t,colvec x,varargin varargin)
calculates the discrete map of the dynamical system that maps xminus from xplus. Subclasses must implement this method by its own.
function TrajectoryOptimization nlp = IdentityMapConstraint (TrajectoryOptimization nlp,TrajectoryOptimization src,TrajectoryOptimization tar,struct bounds,varargin varargin)
Impose system specific constraints as NLP constraints for the trajectory optimization problem.
Public Member Functions inherited from DynamicalSystem
function obj = addState (varargin)
Add state variables of the dynamical system.
function obj = addInput (category, name, var, gf, varargin)
Add input variables of the dynamical system.
function obj = removeInput (category, name)
Remove input variables of the dynamical system.
function obj = addParam (varargin)
Add parameter variables of the dynamical system.
function obj = removeParam (param_name)
Remove parameter variables of the dynamical system.
function obj = setParamValue (varargin)
set the actual value of the system parameters
function obj = compile (export_path, varargin)
export the symbolic expressions of the system dynamics matrices and vectors and compile as MEX files.
DynamicalSystem (char type,char name)
The class construction function.
function obj = setName (name)
set the name of the dynamical system
function var_group = validateVarName (char name)
Adds unilateral (inequality) constraints on the dynamical system states and inputs.
function obj = setType (char type)
Sets the type of the dynamical system.
Public Attributes
function_handle UserNlpConstraint
A handle to a function called by a trajectory optimization NLP to enforce system specific constraints.
char EventName
The event name that triggers the discrete dynamics.
Public Attributes inherited from DynamicalSystem
char Name
The unique name identification of the system.
function_handle ExternalOutputFun
Returns the external input defined on the dynamical system.
char Type
The highest order of the state derivatives of the system.
struct States
A structure that contains the symbolic representation of state variables.
double numState
The total number of system states.
struct Inputs
A structure that contains the symbolic representation of input variables.
struct Params
The parameters of the system.
struct Gvec
The struct of input vector fields Gvec(x,u) SymFunction.
struct Gmap
The struct of input map Gmap(x) SymFunction.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Additional Inherited Members
Protected Member Functions inherited from DynamicalSystem
function value = getValue (vars)
returns the variables (vars) value that are stored during computing the dynamics
function v_type = validateSystemType (type)
validate if it is valid system type
Protected Attributes inherited from DynamicalSystem
double t_
The time.
struct states_
The states.
struct inputs_
The inputs.
struct params_
The parameters.
struct GmapName_
The name of the Gmap functions.
struct GvecName_
The name of the Gvec functions.
Detailed Description
Discrete event dynamic system governed by discrete transition map and triggered by discrete events.
Author
ayonga
Date
2017-04-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file DiscreteDynamics.m.
Constructor & Destructor Documentation
DiscreteDynamics.DiscreteDynamics (char type, char name, char event)
the constructor function for DiscreteDynamics class objects
Parameters
type the type of the system
name the name of the system
event the event name associated with the discrete map
Definition at line 80 of file DiscreteDynamics.m.
References DynamicalSystem.DynamicalSystem(), and EventName.
Referenced by RigidImpact.compile(), and RigidImpact.RigidImpact().
Member Function Documentation
function obj = DiscreteDynamics.addState (SymVariable x, SymVariable xn, SymVariable dx, SymVariable dxn)
overload the superclass addState method with fixed state fields
Parameters
x the pre-impact state variables
xn the post-impact state variables
dx the pre-impact first order derivative of state variables
dxn the post-impact first order derivative of state variables
Definition at line 128 of file DiscreteDynamics.m.
References calcDiscreteMap(), DynamicalSystem.DynamicalSystem(), and IdentityMapConstraint().
Referenced by RigidImpact.RigidImpact().
function colvec xn = DiscreteDynamics.calcDiscreteMap (double t, colvec x, varargin varargin)
calculates the discrete map of the dynamical system that maps xminus from xplus. Subclasses must implement this method by its own.
Note
By default, this discrete map will be a Identity map. For specific discrete map, please implement as a subclass of this class
Parameters
t the time instant
x the pre-impact states
varargin extra argument
Return values
xn the post-impact states
Definition at line 18 of file calcDiscreteMap.m.
Referenced by addState().
function TrajectoryOptimization nlp = DiscreteDynamics.IdentityMapConstraint (TrajectoryOptimization nlp, TrajectoryOptimization src, TrajectoryOptimization tar, struct bounds, varargin varargin)
Impose system specific constraints as NLP constraints for the trajectory optimization problem.
Parameters
nlp an trajectory optimization NLP object of the system
src the NLP of the source domain system
tar the NLP of the target domain system
bounds a struct data contains the boundary values
varargin extra arguments
Definition at line 18 of file IdentityMapConstraint.m.
Referenced by addState().
Member Data Documentation
DiscreteDynamics.EventName
The event name that triggers the discrete dynamics.
Note
This property has custom functionality when its value is changed.
Definition at line 63 of file DiscreteDynamics.m.
Referenced by DiscreteDynamics().
DiscreteDynamics.UserNlpConstraint
A handle to a function called by a trajectory optimization NLP to enforce system specific constraints.
The function handle should have the syntax
userNlpConstraint(edge_nlp, src_nlp, tar_nlp, bounds, varargin)
Definition at line 45 of file DiscreteDynamics.m.
The documentation for this class was generated from the following files:
system/@DiscreteDynamics/DiscreteDynamics.m
system/@DiscreteDynamics/calcDiscreteMap.m
system/@DiscreteDynamics/IdentityMapConstraint.m