FROST: TrajectoryOptimization Class Reference
TrajectoryOptimization Class Reference
TrajectoryOptimization defines a particular type of nonlinear programing problem — trajectory optimization problem.
Public Member Functions
TrajectoryOptimization (char name,DynamicalSystem plant,integerConstantTimeHorizon num_grid,struct bounds,varargin varargin)
The constructor function.
function obj = update ()
Updates the NLP problems before load it to NLP solver.
function obj = configure (struct bounds)
configure the trajectory optimizatino NLP problem
function compileConstraint (cellstr constr,char export_path,cellstr exclude,varargin varargin)
Compile and export symbolic expression and derivatives of all NLP functions.
function compileObjective (cellstr cost,char export_path,cellstr exclude,varargin varargin)
Compile and export symbolic expression and derivatives of all NLP functions.
function obj = addVariable (char label,rowvec nodes, varargin)
Adds NLP decision variables.
function obj = removeVariable (char label)
Removes a NLP optimization variable.
function obj = addInputVariable (struct bounds)
Adds input variables as the NLP decision variables to the problem.
function obj = addParamVariable (struct bounds)
Adds parameters as the NLP decision variables to the problem.
function obj = addStateVariable (struct bounds)
Adds state variables as the NLP decision variables to the problem.
function obj = addTimeVariable (struct bounds)
Adds time as the NLP decision variables to the problem.
function obj = updateVariableProp (char label,char node, varargin)
This function updates the properties of the NLP variable objects based on the input name-value pair arguments.
function obj = configureVariables (struct bounds)
This function configures the structure of the optimization variable by adding (registering) them to the optimization variable table.
function fcstr = directCollocation (char name,SymVariable x,SymVariable dx)
Return the SymFunction object of the direct collocation constraint given the state (x) and derivatives (dx).
function obj = addConstraint (char label,rowvec nodes,struct cstr_array)
Add NLP constraints constraints.
function obj = addCollocationConstraint ()
Add direct collocation equations as a set of equality constraints.
function obj = addDynamicsConstraint ()
Add system dynamics equations as a set of equality constraints.
function obj = addNodeConstraint (SymFunction func,cellstr deps,char nodes,colvec lb,colvec ub,char type,double auxdata)
Add NLP constraint function that only depends on variables at a particular node. The input argument 'nodes' will specify at which nodes the function is defined.
function obj = updateConstrProp (char label,char node, varargin)
This function updates the properties of the constraint objects based on the input name-value pair arguments.
function obj = removeConstraint (char label)
Removes a group of NLP constraints.
function obj = addCost (char label,rowvec nodes,struct cost_array)
Add NLP object functions.
function obj = addRunningCost (SymFunction func,cellstr deps,double auxdata)
Add a running cost to the problem.
function obj = addNodeCost (SymFunction func,cellstr deps,char node,double auxdata)
Add a cost function that only depends on variables at a particular node. The input argument 'nodes' will specify at which nodes the function is defined.
function obj = updateCostProp (char label,char node, varargin)
This function updates the properties of the cost function objects based on the input name-value pair arguments.
function obj = removeCost (label)
Removes a group of NLP cost functions.
function [ yc , cl , cu ] = checkConstraints (x, tol, output_file, permission)
Check the violation of the constraints.
function yc = checkCosts (x, output_file, permission)
Check the value of const function.
function checkVariables (x, tol, output_file, permission)
Check the violation of the constraints.
function [ tspan , states , inputs , params ] = exportSolution (colvec sol,double t0)
Analyzes the solution of the NLP problem.
Public Member Functions inherited from NonlinearProgram
NonlinearProgram (name)
The default class constructor function.
function obj = regVariable (NlpVariable vars)
This method registers the information of an optimization variable.
function obj = update ()
Updates the NLP problems before load it to NLP solver.
function obj = regObjective (NlpFunction funcs)
This method registers the information of a NLP function as a cost function.
function obj = regConstraint (NlpFunction funcs)
This method registers the information of a NLP function as a constraint.
function [ nVar , lowerbound , upperbound ] = getVarInfo ()
The function returns the dimension, upper/lower limits of NLP variables.
function x0 = getInitialGuess (char method)
This function returns an initial guess for the NLP.
function obj = setOption (varargin)
Sets the object options, and return the complete list of option structure including unchanged default options.
function compileConstraint (char export_path,varargin varargin)
Compile and export symbolic expression and derivatives of all NLP functions.
function compileObjective (char export_path,varargin varargin)
Compile and export symbolic expression and derivatives of all NLP functions.
Public Attributes
integer NumNode
The number of discrete nodes along the trajectory.
table OptVarTable
A table of NLP decision variables. The row determines the identity of the variable, and the column determines at which node the variable is defined.
table ConstrTable
A table of NLP constraints. The row determines the identity of the constraint, and the column determines at which node the constraint is defined.
table CostTable
A table of cost functions. The row determines the identity of the function, and the column determines at which node the variable is defined.
DynamicalSystem Plant
The dynamical system plant of the interest.
Public Attributes inherited from NonlinearProgram
char Name
The name of the problem.
struct Options
The class option.
NlpVariable VariableArray
An array contains all information regarding NLP optimization variables.
NlpFunction CostArray
An array data stores objective functions.
NlpFunction ConstrArray
A cell array data stores all constraints functions.
Sol
The solution of the NLP problem.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Static Public Attributes
static const ::double DefaultNumberOfGrid = 10
The default number of collocation grids.
Detailed Description
TrajectoryOptimization defines a particular type of nonlinear programing problem — trajectory optimization problem.
See also
NonlinearProgram, HybridSystem
Author
ayonga
Date
2016-10-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file TrajectoryOptimization.m.
Constructor & Destructor Documentation
TrajectoryOptimization.TrajectoryOptimization (char name, DynamicalSystem plant, integerConstantTimeHorizon num_grid, struct bounds, varargin varargin)
The constructor function.
Parameters
name the name of the problem
plant the dynamical system plant
num_grid the number of grids along the trajectory
bounds a structed data stores the boundary information of the NLP variables
varargin user-defined options for the problem
TrajectoryOptimization (...,  [ "CollocationScheme", CollocationScheme_value ] [, "DistributeParameters", DistributeParameters_value ]
                    [, "DistributeTimeVariable", DistributeTimeVariable_value ] [, "ConstantTimeHorizon", ConstantTimeHorizon_value ]
                    [, "DerivativeLevel", DerivativeLevel_value ] [, "EqualityConstraintBoundary", EqualityConstraintBoundary_value ] )
Named Parameters for varargin:
CollocationScheme CollocationScheme (Default: HermiteSimpson)
DistributeParameters DistributeParameters (Default: true)
DistributeTimeVariable DistributeTimeVariable (Default: true)
ConstantTimeHorizon ConstantTimeHorizon (Default: nan(2,1))
DerivativeLevel DerivativeLevel (Default: 1)
EqualityConstraintBoundary EqualityConstraintBoundary (Default: 0)
Definition at line 141 of file TrajectoryOptimization.m.
References addCollocationConstraint(), addConstraint(), addCost(), addDynamicsConstraint(), addInputVariable(), addNodeConstraint(), addNodeCost(), addParamVariable(), addRunningCost(), addStateVariable(), addTimeVariable(), addVariable(), checkConstraints(), checkCosts(), checkVariables(), compileConstraint(), compileObjective(), configure(), configureVariables(), DefaultNumberOfGrid, directCollocation(), exportSolution(), NonlinearProgram.NonlinearProgram(), removeConstraint(), removeCost(), removeVariable(), update(), updateConstrProp(), updateCostProp(), and updateVariableProp().
Member Function Documentation
function obj = TrajectoryOptimization.addCollocationConstraint ()
Add direct collocation equations as a set of equality constraints.
Todo:
implement pseudospectral method
Definition at line 18 of file addCollocationConstraint.m.
References addConstraint(), and directCollocation().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addConstraint (char label, rowvec nodes, struct cstr_array)
Add NLP constraints constraints.
See also
NlpFunction, removeConstraint
Note
Parameters
label the label name (column) of the constraints
nodes the node list of the variable
cstr_array an array of structures that could be used to construct the NlpFunction object.
Definition at line 18 of file addConstraint.m.
References implode().
Referenced by addCollocationConstraint(), addDynamicsConstraint(), HybridTrajectoryOptimization.addJumpConstraint(), addNodeConstraint(), addParamVariable(), addTimeVariable(), and TrajectoryOptimization().
function obj = TrajectoryOptimization.addCost (char label, rowvec nodes, struct cost_array)
Add NLP object functions.
See also
NlpFunction, removeCost
Note
Parameters
label the label name (column) of the cost
nodes the node list of the variable
cost_array an array of structures that could be used to construct the NlpFunction object.
Definition at line 18 of file addCost.m.
References implode().
Referenced by addNodeCost(), addRunningCost(), and TrajectoryOptimization().
function obj = TrajectoryOptimization.addDynamicsConstraint ()
Add system dynamics equations as a set of equality constraints.
Definition at line 18 of file addDynamicsConstraint.m.
References addConstraint(), and handle.fieldnames.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addInputVariable (struct bounds)
Adds input variables as the NLP decision variables to the problem.
Note
The input variables may includes the control inputs, as well as external forces such as disturbance or contact wrenches.
Parameters
bounds a structed data stores the boundary information of the NLP variables
Required fields of bounds:
Definition at line 18 of file addInputVariable.m.
References addVariable(), handle.fieldnames, and updateVariableProp().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addNodeConstraint (SymFunction func, cellstr deps, char nodes, colvec lb, colvec ub, char type, double auxdata)
Add NLP constraint function that only depends on variables at a particular node. The input argument 'nodes' will specify at which nodes the function is defined.
Note
This function provides a simple type of constraints function which dependends only on variables at same particular node.
Attention
In the case the constraints function dependes on variables at different nodes, please use the basic 'addCost' method directly.
This method can be used to add any terminal constraint by specify 'nodes' as either 'first' or 'last'.
Parameters
func a symbolic function of the constraint
deps a list of dependent variables
nodes an indicator of first or last node
lb the lower bound of the constraints
ub the upper bound of the constraints
type the type of the constraints ('Linear' or 'Nonlinear')
auxdata auxilary constant data to be feed in the function
Required fields of func:
Definition at line 18 of file addNodeConstraint.m.
References addConstraint(), implode(), and SymFunction.Name.
Referenced by addTimeVariable(), and TrajectoryOptimization().
function obj = TrajectoryOptimization.addNodeCost (SymFunction func, cellstr deps, char node, double auxdata)
Add a cost function that only depends on variables at a particular node. The input argument 'nodes' will specify at which nodes the function is defined.
Note
This function provides a simple type of cost function which dependends only on variables at some particular node. If multiple nodes are specified, the final cost function will be the sum of the function computated at each node.
Attention
In the case the cost function dependes on variables at different nodes, please use the basic 'addCost' method directly.
This method can be used to add any terminal cost function by specify 'nodes' as either 'first' or 'last'.
Parameters
func a symbolic function to be integrated
deps a list of dependent variables
auxdata auxilary constant data to be feed in the function
node an indicator of first or last node
Required fields of func:
Definition at line 18 of file addNodeCost.m.
References addCost(), implode(), and SymFunction.Name.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addParamVariable (struct bounds)
Adds parameters as the NLP decision variables to the problem.
Parameters
bounds a structed data stores the boundary information of the NLP variables
Definition at line 18 of file addParamVariable.m.
References addConstraint(), addVariable(), handle.fieldnames, and handle.transpose.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addRunningCost (SymFunction func, cellstr deps, double auxdata)
Add a running cost to the problem.
Parameters
func a symbolic function to be integrated
deps a list of dependent variables
auxdata auxilary constant data to be feed in the function
Required fields of func:
Definition at line 18 of file addRunningCost.m.
References addCost(), SymFunction.Name, SymFunction.Params, and SymFunction.Vars.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addStateVariable (struct bounds)
Adds state variables as the NLP decision variables to the problem.
Parameters
bounds a structed data stores the boundary information of the NLP variables
Definition at line 18 of file addStateVariable.m.
References addVariable(), handle.fieldnames, and updateVariableProp().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addTimeVariable (struct bounds)
Adds time as the NLP decision variables to the problem.
Parameters
bounds a structed data stores the boundary information of the NLP variables
Required fields of bounds:
Definition at line 18 of file addTimeVariable.m.
References addConstraint(), addNodeConstraint(), and addVariable().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.addVariable (char label, rowvec nodes, varargin)
Adds NLP decision variables.
See also
NlpVariable, removeVariable
Parameters
label the label name (column) of the variable
nodes the node list of the variable
varargin variable input arguments for property values non-empty NlpVariables This function updates the properties of the class object based on the input name-value pair arguments.
varargin variable nama-value pair input arguments, in detail:
updateProp (lb, ub, x0)
Required Parameters for varargin:
lb lower limit
ub upper limit
x0 a typical value of the variable
Definition at line 18 of file addVariable.m.
References implode().
Referenced by addInputVariable(), addParamVariable(), addStateVariable(), addTimeVariable(), and TrajectoryOptimization().
function [ yc , cl , cu ] = TrajectoryOptimization.checkConstraints (x, tol, output_file, permission)
Check the violation of the constraints.
Definition at line 18 of file checkConstraints.m.
Referenced by TrajectoryOptimization().
function yc = TrajectoryOptimization.checkCosts (x, output_file, permission)
Check the value of const function.
Definition at line 18 of file checkCosts.m.
Referenced by TrajectoryOptimization().
function TrajectoryOptimization.checkVariables (x, tol, output_file, permission)
Check the violation of the constraints.
Definition at line 18 of file checkVariables.m.
Referenced by TrajectoryOptimization().
function TrajectoryOptimization.compileConstraint (cellstr constr, char export_path, cellstr exclude, varargin varargin)
Compile and export symbolic expression and derivatives of all NLP functions.
Note
If constr is emtpy, then it will compile all constraints.
Parameters
constr a list of constraints to be compiled
export_path the path to export the file
exclude a list of functions to be excluded
varargin variable input parameters
compileConstraint (..., StackVariable, ForceExport, BuildMex, Namespace)
Required Parameters for varargin:
StackVariable whether to stack variables into one
ForceExport force the export
BuildMex flag whether to MEX the exported file
Namespace the namespace of the function
Definition at line 18 of file compileConstraint.m.
Referenced by TrajectoryOptimization().
function TrajectoryOptimization.compileObjective (cellstr cost, char export_path, cellstr exclude, varargin varargin)
Compile and export symbolic expression and derivatives of all NLP functions.
Note
If cost is emtpy, then it will compile all cost functions.
Parameters
cost the cost function to be compiled
export_path the path to export the file
exclude a list of functions to be excluded
varargin variable input parameters
compileObjective (..., ForceExport, BuildMex)
Required Parameters for varargin:
ForceExport force the export
BuildMex flag whether to MEX the exported file
Definition at line 18 of file compileObjective.m.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.configure (struct bounds)
configure the trajectory optimizatino NLP problem
This process will add NLP variables based on the information of the dynamical system object, impose dynamical and collocation constraints, then call the system constraints callback function to add any system-specific constraints.
Parameters
bounds a struct data contains the boundary values
Note
If the number of node equals 1, then the system is either discrete event system or a ternimal node of a hybrid system. For this type of system, the problem is actually not a trajectory optimization problem. Hence no need to enforce the collocation constraint and dynamics constraint.
Definition at line 18 of file configure.m.
References handle.fieldnames.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.configureVariables (struct bounds)
This function configures the structure of the optimization variable by adding (registering) them to the optimization variable table.
A particular project might inherit the class and overload this function to achieve custom configuration of the optimization variables
Parameters
bounds a structed data stores the boundary information of the NLP variables
Required fields of bounds:
Definition at line 18 of file configureVariables.m.
References handle.fieldnames.
Referenced by TrajectoryOptimization().
function fcstr = TrajectoryOptimization.directCollocation (char name, SymVariable x, SymVariable dx)
Return the SymFunction object of the direct collocation constraint given the state (x) and derivatives (dx).
Parameters
name the name suffix of the function
x the state SymVariable
dx the derivative of states
Definition at line 18 of file directCollocation.m.
Referenced by addCollocationConstraint(), and TrajectoryOptimization().
function [ rowvec tspan , struct states , struct inputs , struct params ] = TrajectoryOptimization.exportSolution (colvec sol, double t0)
Analyzes the solution of the NLP problem.
Parameters
sol The solution vector of the NLP problem
t0 the initial time
Return values
tspan the time span of the trajectory
states the state trajectories
inputs the input variable trajectories
params the parameter variables
Definition at line 18 of file exportSolution.m.
References handle.fieldnames.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.removeConstraint (char label)
Removes a group of NLP constraints.
See also
addConstraint
Parameters
label the label name (column) of the constraints
Definition at line 18 of file removeConstraint.m.
References str_index().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.removeCost (label)
Removes a group of NLP cost functions.
See also
addCost
Parameters
label the label name (column) of the cost function
Definition at line 18 of file removeCost.m.
References str_index().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.removeVariable (char label)
Removes a NLP optimization variable.
See also
addVariable
Parameters
label the label name (column) of the variable
Definition at line 18 of file removeVariable.m.
References str_index().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.update ()
Updates the NLP problems before load it to NLP solver.
Note
Overload the superclass (NonlinearProgram) for additional updates
Generated fields of obj:
Definition at line 18 of file update.m.
References NonlinearProgram.NonlinearProgram(), NonlinearProgram.regConstraint(), NonlinearProgram.regObjective(), and NonlinearProgram.regVariable().
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.updateConstrProp (char label, char node, varargin)
This function updates the properties of the constraint objects based on the input name-value pair arguments.
Note
The note identifier can be either the numbers of node indices
or the following string to specify particular nodes
first: the first node
last: the last node
all: all nodes
cardinal: all cardinal (odd) nodes, only effective if HermiteSimpson scheme is used
interior: all interior (even) nodes, only effective if HermiteSimpson scheme is used
Parameters
label the row name of the constraints
node the identifier of the node list
varargin variable nama-value pair input arguments, in detail:
updateConstrProp (..., lb, ub)
Required Parameters for varargin:
lb lower limit
ub upper limit
Definition at line 18 of file updateConstrProp.m.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.updateCostProp (char label, char node, varargin)
This function updates the properties of the cost function objects based on the input name-value pair arguments.
Note
The note identifier can be either the numbers of node indices
or the following string to specify particular nodes
first: the first node
last: the last node
all: all nodes
cardinal: all cardinal (odd) nodes, only effective if HermiteSimpson scheme is used
interior: all interior (even) nodes, only effective if HermiteSimpson scheme is used
Parameters
label the row name of the constraints
node the identifier of the node list
varargin variable nama-value pair input arguments, in detail:
updateCostProp (..., lb, ub)
Required Parameters for varargin:
lb lower limit
ub upper limit
Definition at line 18 of file updateCostProp.m.
Referenced by TrajectoryOptimization().
function obj = TrajectoryOptimization.updateVariableProp (char label, char node, varargin)
This function updates the properties of the NLP variable objects based on the input name-value pair arguments.
Note
The note identifier can be either the numbers of node indices
or the following string to specify particular nodes
first: the first node
last: the last node
all: all nodes
cardinal: all cardinal (odd) nodes, only effective if HermiteSimpson scheme is used
interior: all interior (even) nodes, only effective if HermiteSimpson scheme is used
Parameters
label the row name of the constraints
node the identifier of the node list
varargin variable nama-value pair input arguments, in detail:
updateVariableProp (..., lb, ub, x0)
Required Parameters for varargin:
lb lower limit
ub upper limit
x0 a typical value of the variable
Definition at line 18 of file updateVariableProp.m.
Referenced by addInputVariable(), addStateVariable(), and TrajectoryOptimization().
Member Data Documentation
TrajectoryOptimization.ConstrTable
A table of NLP constraints. The row determines the identity of the constraint, and the column determines at which node the constraint is defined.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 89 of file TrajectoryOptimization.m.
TrajectoryOptimization.CostTable
A table of cost functions. The row determines the identity of the function, and the column determines at which node the variable is defined.
Attention
We assume the cost functioin (or objective) of a NLP is the sum of these cost functions.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 103 of file TrajectoryOptimization.m.
TrajectoryOptimization.DefaultNumberOfGrid = 10 static
The default number of collocation grids.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Default: 10
Definition at line 44 of file TrajectoryOptimization.m.
Referenced by TrajectoryOptimization().
TrajectoryOptimization.NumNode
The number of discrete nodes along the trajectory.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 63 of file TrajectoryOptimization.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint(), and VirtualConstraint.imposeNLPConstraint().
TrajectoryOptimization.OptVarTable
A table of NLP decision variables. The row determines the identity of the variable, and the column determines at which node the variable is defined.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 75 of file TrajectoryOptimization.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint(), and VirtualConstraint.imposeNLPConstraint().
TrajectoryOptimization.Plant
The dynamical system plant of the interest.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 120 of file TrajectoryOptimization.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint().
The documentation for this class was generated from the following files:
nlp/@TrajectoryOptimization/TrajectoryOptimization.m
nlp/@TrajectoryOptimization/addCollocationConstraint.m
nlp/@TrajectoryOptimization/addConstraint.m
nlp/@TrajectoryOptimization/addCost.m
nlp/@TrajectoryOptimization/addDynamicsConstraint.m
nlp/@TrajectoryOptimization/addInputVariable.m
nlp/@TrajectoryOptimization/addNodeConstraint.m
nlp/@TrajectoryOptimization/addNodeCost.m
nlp/@TrajectoryOptimization/addParamVariable.m
nlp/@TrajectoryOptimization/addRunningCost.m
nlp/@TrajectoryOptimization/addStateVariable.m
nlp/@TrajectoryOptimization/addTimeVariable.m
nlp/@TrajectoryOptimization/addVariable.m
nlp/@TrajectoryOptimization/checkConstraints.m
nlp/@TrajectoryOptimization/checkCosts.m
nlp/@TrajectoryOptimization/checkVariables.m
nlp/@TrajectoryOptimization/compileConstraint.m
nlp/@TrajectoryOptimization/compileObjective.m
nlp/@TrajectoryOptimization/configure.m
nlp/@TrajectoryOptimization/configureVariables.m
nlp/@TrajectoryOptimization/directCollocation.m
nlp/@TrajectoryOptimization/exportSolution.m
nlp/@TrajectoryOptimization/removeConstraint.m
nlp/@TrajectoryOptimization/removeCost.m
nlp/@TrajectoryOptimization/removeVariable.m
nlp/@TrajectoryOptimization/update.m
nlp/@TrajectoryOptimization/updateConstrProp.m
nlp/@TrajectoryOptimization/updateCostProp.m
nlp/@TrajectoryOptimization/updateVariableProp.m