FROST: KinematicExpr Class Reference
KinematicExpr Class Reference
Defines a kinematic constraint that expressed as a function of other kinematic constraints.
Public Member Functions
KinematicExpr (varargin)
The constructor function.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
Public Member Functions inherited from Kinematics
Kinematics (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic function. By default, we assume the dimension of a kinematic function is 1, unless this method is overloaded by subclasses.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function print (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
Public Attributes
char Expression
A string representation of the symbolic expressions.
Kinematics Dependents
An array of Kinematic constraints objects that are dependent variables of the kinematic expression.
struct Parameters
An array of parameters of the kinematic expression.
Public Attributes inherited from Kinematics
char Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
logical Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
char Prefix
A prefix for the function to be exported.
char Suffix
A suffix for the function to be exported.
struct Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
struct Funcs
File names of the kinematic functions.
Additional Inherited Members
Protected Member Functions inherited from Kinematics
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
function cmd = getJacDotMathCommand ()
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Protected Attributes inherited from Kinematics
logical LinearizeFlagChanged
A flag for whether the 'Linearize' option is changed.
Detailed Description
Defines a kinematic constraint that expressed as a function of other kinematic constraints.
Author
Ayonga Hereid
Date
2016-09-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file KinematicExpr.m.
Constructor & Destructor Documentation
KinematicExpr.KinematicExpr (varargin)
The constructor function.
See also
struct
Parameters
varargin it could be a struct has the same fields as this class or name-value pair arguments. The syntax would be similar to construct a struct in Matlab. Use either
kin = Kinematics('Prop1', Value1,'Prop2',Value2,...);
or
kin = Kinematics(KinStruct);
See also
Kinematics
Definition at line 85 of file KinematicExpr.m.
References compile(), Dependents, export(), Expression, Kinematics.getDimension(), Kinematics.Kinematics(), and Parameters.
Member Function Documentation
function status = KinematicExpr.compile (RigidBodyModel model, logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
The compilation for KinematicExpr requires complex computations, hence, we overload the superclass method here.
Parameters
model the rigid body model
re_load re-evaluate the symbolic expression
Required fields of model:
Definition at line 18 of file compile.m.
References cell2tensor(), check_var_exist(), eval_math(), Kinematics.getJacDotMathCommand(), and RigidBodyModel.Name.
Referenced by KinematicExpr().
function logical status = KinematicExpr.export (char export_path, logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
Overload by KinematicExpr
Parameters
export_path the complete directory path where the compiled symbolic function will be exported to
do_build determine whether build the mex files. Default: true
Return values
status indicator of successful export/built process
Definition at line 18 of file export.m.
References build_mex(), check_var_exist(), eval_math(), Kinematics.getDimension(), Kinematics.Kinematics(), and str2mathstr().
Referenced by KinematicExpr().
Member Data Documentation
KinematicExpr.Dependents
An array of Kinematic constraints objects that are dependent variables of the kinematic expression.
Note
This property has custom functionality when its value is changed.
Definition at line 49 of file KinematicExpr.m.
Referenced by KinematicExpr().
KinematicExpr.Expression
A string representation of the symbolic expressions.
Note
This property has custom functionality when its value is changed.
Definition at line 40 of file KinematicExpr.m.
Referenced by KinematicExpr().
KinematicExpr.Parameters
An array of parameters of the kinematic expression.
To use extra parameterized argument in the expression, the following rules must be applied (assuming 'p' is the name of
the parameter)
must consider it as an 1-D vector.
each element should be written in the form of 'p[i]' in the expression.
the indexing must start from 1 instead of zero.
if the parameter is a scalar, write it as 'p[1]' instead of 'p'.
Note
This property has custom functionality when its value is changed.
Definition at line 59 of file KinematicExpr.m.
Referenced by KinematicExpr().
The documentation for this class was generated from the following files:
kinematics/@KinematicExpr/KinematicExpr.m
kinematics/@KinematicExpr/compile.m
kinematics/@KinematicExpr/export.m