FROST: NlpFunctionSum Class Reference
NlpFunctionSum Class Reference
This class provides a particular NLP function that is the sum of multiple NlpFunction objects. For instance, the cost function, etc.
Public Member Functions
NlpFunctionSum (varargin)
The class constructor function.
function obj = setDependentFunction (NlpFunction deps)
Sets dependent objects of the Nlp Function.
function obj = setFuncIndices (integer index)
Sets indices of the Nlp Function.
function deps = getDepObject ()
Returns the object of the dependent function.
Public Member Functions inherited from NlpFunction
NlpFunction (varargin)
The class constructor function.
function deps = getDepObject ()
Returns the object of the dependent function.
function colvec indices = getDepIndices ()
Returns the indices of the dependent variables.
function obj = setName (char name)
Specifies the name of the NLP function.
function obj = setType (char type)
Sets the type (either LINEAR or NONLINEAR) of the NLP function.
function obj = setAuxdata (rowvec auxdata)
Sets the auxilary input argument data to call the NLP function. These auxilary data must be a vector of numeric values.
function obj = setJacobianPattern (matrix jac_sp,char sp_form)
This function configure the sparsity pattern of the Jacobian of the function.
function obj = setHessianPattern (cell hes_sp,char sp_form)
This function configure the sparsity pattern of the Hessian of the function.
function obj = setDependentVariable (NlpVariables depvars)
This function sets the dependent variables of the function.
function obj = setBoundary (cl, cu)
set the upper/lower boundary values of the function if they exist
function obj = updateProp (varargin)
This function updates the properties of the class object based on the input name-value pair arguments.
Public Attributes
NlpFunction Dependents
The dependent functions.
Public Attributes inherited from NlpFunction
logical Type
This property specifies whether the function is the linear function of dependent variables.
char Name
An identification of the object.
NlpVariable DepVariables
An array of dependent NLP variables.
colvec FuncIndices
Stores the indices of the function.
colvec nnzJacIndices
Stores the indices of the non-zero elements in the first-order jacobian.
colvec nnzHessIndices
Stores the indices of the non-zero elements in the Hessian matrix of the Lagrangian.
Funcs
File names of the external functions that computes the function/Jacobian/Hessian of the object.
char JacPattern
% The name of the function that computes the Jacobian of the % function % % Typically, this function is generated as a MEX function by % Mathematica symbolic engine. It can be also written as a matlab % function by the user. % % JacFunc % The name of the function that computes the Jacobian of the % function % % Typically, this function is generated as a MEX function by % Mathematica symbolic engine. It can be also written as a matlab % function by the user. % % HessFunc A two-vector structure that specifies the non-zero structure of the first order Jacobian of the function with respect to the dependent variables. The first vector determines the row indices of the all non-zero elements in the Jacobian matrix, and the second vector determines the colomn indices of the all non-zero elements in the Jacobian matrix. For the gradient of the cost function, the first vector should consists of all 1s.
struct HessPattern
A two-vector structure that specifies the non-zero structure of the second order Hessian of the Lagrangian function with respect to the dependent variables. The first vector determines the row indices of the all non-zero elements in the Hessian matrix, and the second vector determines the colomn indices of the all non-zero elements in the Hessian matrix.
integer nnzJac
The number of nonzero entries in the Jacobian matrix.
integer nnzHess
The number of nonzero entries in the Hessian matrix.
matrix AuxData
A constant array of auxiliary data that will be used to construct the function handles.
colvec LowerBound
The lower boundary values of the function.
colvec UpperBound
The upper boundary values of the function.
integer Dimension
It gives a quick access to the dimension of the function output without actually evaluating the function.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Additional Inherited Members
Static Public Attributes inherited from NlpFunction
static const LINEAR = true
static const NONLINEAR = false
Detailed Description
This class provides a particular NLP function that is the sum of multiple NlpFunction objects. For instance, the cost function, etc.
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file NlpFunctionSum.m.
Constructor & Destructor Documentation
NlpFunctionSum.NlpFunctionSum (varargin)
The class constructor function.
Definition at line 49 of file NlpFunctionSum.m.
References NlpFunction.NlpFunction(), and setDependentFunction().
Member Function Documentation
function deps = NlpFunctionSum.getDepObject ()
Returns the object of the dependent function.
Return values
deps the dependent objects
Definition at line 122 of file NlpFunctionSum.m.
function obj = NlpFunctionSum.setDependentFunction (NlpFunction deps)
Sets dependent objects of the Nlp Function.
Parameters
deps dependent objects
Generated fields of obj:
Definition at line 73 of file NlpFunctionSum.m.
Referenced by NlpFunctionSum().
function obj = NlpFunctionSum.setFuncIndices (integer index)
Sets indices of the Nlp Function.
Parameters
index the indices of the function
Generated fields of obj:
Definition at line 101 of file NlpFunctionSum.m.
Member Data Documentation
NlpFunctionSum.Dependents
The dependent functions.
Definition at line 37 of file NlpFunctionSum.m.
The documentation for this class was generated from the following file:
nlp/NlpFunctionSum.m