FROST: ContinuousDynamics Class Reference
ContinuousDynamics Class Reference
Continuous state dynamic system governed by differential equations.
Public Member Functions
ContinuousDynamics (char type,char name)
The class construction function.
function obj = addState (SymVariable x,SymVariable dx,SymVariable ddx)
overload the superclass addState method with fixed state fields
function sol = simulate (t0, x0, tf, controller, params, eventnames, options, varargin)
Simulate the dynamical system.
function [ value , isterminal , direction ] = checkGuard (t, x, controller, params, eventfuncs)
Detect the guard condition (event trigger)
function obj = setMassMatrix (M)
Set the mass matrix M(x) of the system.
function obj = setDriftVector (vf)
Set the drift vector field Fvec(x) or Fvec(x,dx) of the system.
function M = calcMassMatrix (x)
calculates the mass matrix Mmat(x)
function f = calcDriftVector (x, dx)
calculates the mass matrix Fvec(x) or Fvec(x,dx)
function [ xdot , extra ] = calcDynamics (t, x, controller, params)
calculate the dynamical equation dx
function [ xdot , extra ] = firstOrderDynamics (t, x, controller, params)
calculate the dynamical equation of the first order dynamical system
function [ xdot , extra ] = secondOrderDynamics (t, x, controller, params)
calculate the dynamical equation of the second order dynamical system
function obj = compile (export_path, varargin)
export the symbolic expressions of the system dynamics matrices and vectors and compile as MEX files.
function obj = addEvent (constr)
Adds event function for the dynamical system states and inputs.
function obj = removeEvent (name)
Remove event functions defined for the system.
function obj = addHolonomicConstraint (constr)
Adds a holonomic constraint to the dynamical system.
function obj = removeHolonomicConstraint (name)
Remove holonomic constraints defined for the system.
function obj = addUnilateralConstraint (constr)
Adds unilateral (inequality) constraints on the dynamical system states and inputs.
function obj = removeUnilateralConstraint (name)
Remove unilateral constraints defined for the system.
function obj = addVirtualConstraint (constr)
Adds a set of virtual constraints to the dynamical system.
function obj = removeVirtualConstraint (name)
Remove virtual constraints defined for the system.
Public Member Functions inherited from DynamicalSystem
function obj = addState (varargin)
Add state variables of the dynamical system.
function obj = addInput (category, name, var, gf, varargin)
Add input variables of the dynamical system.
function obj = removeInput (category, name)
Remove input variables of the dynamical system.
function obj = addParam (varargin)
Add parameter variables of the dynamical system.
function obj = removeParam (param_name)
Remove parameter variables of the dynamical system.
function obj = setParamValue (varargin)
set the actual value of the system parameters
function obj = compile (export_path, varargin)
export the symbolic expressions of the system dynamics matrices and vectors and compile as MEX files.
DynamicalSystem (char type,char name)
The class construction function.
function obj = setName (name)
set the name of the dynamical system
function var_group = validateVarName (char name)
Adds unilateral (inequality) constraints on the dynamical system states and inputs.
function obj = setType (char type)
Sets the type of the dynamical system.
Public Attributes
function_handle PreProcess
pre-process function handle of the object before the simulation
function_handle PostProcess
pre-process function handle of the object after the simulation
function_handle UserNlpConstraint
A handle to a function called by a trajectory optimization NLP to enforce system specific constraints.
struct Flow
The flow (trajectory) from the dynamical system simulation.
SymFunction Mmat
The mass matrix Mmat(x)
cell Fvec
The cell array of the drift vector fields Fvec(x) SymFunction.
struct HolonomicConstraints
The holonomic constraints of the dynamical system.
struct UnilateralConstraints
The unilateral constraints of the dynamical system.
struct VirtualConstraints
The virtual constraints of the dynamical system.
struct EventFuncs
The event functions.
SymFunction MmatDx
The left hand side of the dynamical equation: M(x)dx or M(x)ddx.
Public Attributes inherited from DynamicalSystem
char Name
The unique name identification of the system.
function_handle ExternalOutputFun
Returns the external input defined on the dynamical system.
char Type
The highest order of the state derivatives of the system.
struct States
A structure that contains the symbolic representation of state variables.
double numState
The total number of system states.
struct Inputs
A structure that contains the symbolic representation of input variables.
struct Params
The parameters of the system.
struct Gvec
The struct of input vector fields Gvec(x,u) SymFunction.
struct Gmap
The struct of input map Gmap(x) SymFunction.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Additional Inherited Members
Protected Member Functions inherited from DynamicalSystem
function value = getValue (vars)
returns the variables (vars) value that are stored during computing the dynamics
function v_type = validateSystemType (type)
validate if it is valid system type
Protected Attributes inherited from DynamicalSystem
double t_
The time.
struct states_
The states.
struct inputs_
The inputs.
struct params_
The parameters.
struct GmapName_
The name of the Gmap functions.
struct GvecName_
The name of the Gvec functions.
Detailed Description
Continuous state dynamic system governed by differential equations.
It could be either a
first order system with the form
\begin{eqnarray*} Mmat(x)\dot{x}= Fvec(x) + Gvec(x,u) \end{eqnarray*}
or a second order system with the form
\begin{eqnarray*} Mmat(x)\ddot{x}= Fvec(x,\dot{x}) + Gvec(x,u) \end{eqnarray*}
Further, if the inputs (u) are affine, the system can be written as
either for first order system of the form
\begin{eqnarray*} Mmat(x)\dot{x}= Fvec(x) + Gmap(x) u \end{eqnarray*}
or a second order system of the form
\begin{eqnarray*} Mmat(x)\ddot{x}= Fvec(x,\dot{x}) + Gmap(x) u \end{eqnarray*}
Author
ayonga
Date
2017-02-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file ContinuousDynamics.m.
Constructor & Destructor Documentation
ContinuousDynamics.ContinuousDynamics (char type, char name)
The class construction function.
Parameters
type the type of the system
name the name of the system
Definition at line 107 of file ContinuousDynamics.m.
References DynamicalSystem.DynamicalSystem().
Referenced by RobotLinks.RobotLinks().
Member Function Documentation
function obj = ContinuousDynamics.addEvent (constr)
Adds event function for the dynamical system states and inputs.
Parameters
constr the event function
Definition at line 18 of file addEvent.m.
function obj = ContinuousDynamics.addHolonomicConstraint (constr)
Adds a holonomic constraint to the dynamical system.
Note
Any holonomic constraint introduces a set of constrained wrenchs to the system (Lagrangian multiplier).
Parameters
constr the expression of the constraints
Definition at line 18 of file addHolonomicConstraint.m.
References DynamicalSystem.addInput(), DynamicalSystem.addParam(), and handle.transpose.
Referenced by RobotLinks.addContact(), and RobotLinks.addFixedJoint().
function obj = ContinuousDynamics.addState (SymVariable x, SymVariable dx, SymVariable ddx)
overload the superclass addState method with fixed state fields
Parameters
x the state variables
dx the first order derivative of state variables
ddx the second order derivative of state variables
Definition at line 146 of file ContinuousDynamics.m.
References DynamicalSystem.DynamicalSystem().
function obj = ContinuousDynamics.addUnilateralConstraint (constr)
Adds unilateral (inequality) constraints on the dynamical system states and inputs.
Parameters
constr the unilateral constraints
Definition at line 18 of file addUnilateralConstraint.m.
Referenced by RobotLinks.addContact().
function obj = ContinuousDynamics.addVirtualConstraint (constr)
Adds a set of virtual constraints to the dynamical system.
Parameters
constr the VirtualConstraint object
Definition at line 18 of file addVirtualConstraint.m.
References DynamicalSystem.addParam().
function f = ContinuousDynamics.calcDriftVector (x, dx)
calculates the mass matrix Fvec(x) or Fvec(x,dx)
Parameters
x the state variables
dx the first order derivative of state variables
Todo:
This calculation is slow due to multiple function invoke. Better ideas to improve the speed?
Definition at line 18 of file calcDriftVector.m.
Referenced by firstOrderDynamics(), and secondOrderDynamics().
function [ xdot , extra ] = ContinuousDynamics.calcDynamics (t, x, controller, params)
calculate the dynamical equation dx
Parameters
t the time instant
x the states
controller the controller
params the parameter structure
Definition at line 18 of file calcDynamics.m.
References firstOrderDynamics(), and secondOrderDynamics().
Referenced by checkGuard(), and simulate().
function M = ContinuousDynamics.calcMassMatrix (x)
calculates the mass matrix Mmat(x)
Parameters
x the state variables
Definition at line 18 of file calcMassMatrix.m.
Referenced by firstOrderDynamics(), and secondOrderDynamics().
function [ value , isterminal , direction ] = ContinuousDynamics.checkGuard (t, x, controller, params, eventfuncs)
Detect the guard condition (event trigger)
Parameters
t the absolute time
x the system states
controller the controller
params the parameter structure
eventfuncs a list of event function
Required fields of eventfuncs:
Definition at line 18 of file checkGuard.m.
References UnilateralConstraint.calcConstraint(), calcDynamics(), DynamicalSystem.getValue(), and UnilateralConstraint.InputDependent.
Referenced by simulate().
function obj = ContinuousDynamics.compile (export_path, varargin)
export the symbolic expressions of the system dynamics matrices and vectors and compile as MEX files.
Parameters
export_path the path to export the file
varargin variable input parameters
compile (..., StackVariable, File, ForceExport, BuildMex, Namespace)
Required Parameters for varargin:
StackVariable whether to stack variables into one
File the (full) file name of exported file
ForceExport force the export
BuildMex flag whether to MEX the exported file
Namespace the namespace of the function
Definition at line 18 of file compile.m.
References DynamicalSystem.DynamicalSystem(), and handle.fieldnames.
function [ xdot , extra ] = ContinuousDynamics.firstOrderDynamics (t, x, controller, params)
calculate the dynamical equation of the first order dynamical system
Parameters
t the time instant
x the states
controller the controller
params the parameter structure
Generated fields of extra:
Definition at line 18 of file firstOrderDynamics.m.
References calcDriftVector(), calcMassMatrix(), handle.fieldnames, and handle.transpose.
Referenced by calcDynamics().
function obj = ContinuousDynamics.removeEvent (name)
Remove event functions defined for the system.
Parameters
name the name of the constraint
Generated fields of obj:
Definition at line 18 of file removeEvent.m.
function obj = ContinuousDynamics.removeHolonomicConstraint (name)
Remove holonomic constraints defined for the system.
Parameters
name the name of the constraint
Generated fields of obj:
Definition at line 18 of file removeHolonomicConstraint.m.
References DynamicalSystem.removeInput(), and DynamicalSystem.removeParam().
function obj = ContinuousDynamics.removeUnilateralConstraint (name)
Remove unilateral constraints defined for the system.
Parameters
name the name of the constraint
Generated fields of obj:
Definition at line 18 of file removeUnilateralConstraint.m.
function obj = ContinuousDynamics.removeVirtualConstraint (name)
Remove virtual constraints defined for the system.
Parameters
name the name of the constraint
Generated fields of obj:
Definition at line 18 of file removeVirtualConstraint.m.
References DynamicalSystem.removeParam().
function [ xdot , extra ] = ContinuousDynamics.secondOrderDynamics (t, x, controller, params)
calculate the dynamical equation of the second order dynamical system
Parameters
t the time instant
x the states
controller the controller
params the parameter structure
Generated fields of extra:
Definition at line 18 of file secondOrderDynamics.m.
References calcDriftVector(), calcMassMatrix(), handle.fieldnames, and handle.transpose.
Referenced by calcDynamics().
function obj = ContinuousDynamics.setDriftVector (vf)
Set the drift vector field Fvec(x) or Fvec(x,dx) of the system.
Parameters
vf the f(x)
Generated fields of obj:
Definition at line 18 of file setDriftVector.m.
function obj = ContinuousDynamics.setMassMatrix (M)
Set the mass matrix M(x) of the system.
Parameters
M the mass matrix M(x)
Required fields of M:
Generated fields of obj:
Definition at line 18 of file setMassMatrix.m.
References SymFunction.Vars.
function sol = ContinuousDynamics.simulate (t0, x0, tf, controller, params, eventnames, options, varargin)
Simulate the dynamical system.
Parameters
t0 the starting time instant
x0 the initial states
tf the terminating time instant
controller the controller for the dynamical system
params extra parameters
eventnames the name of eventnames to be used
options simulation options of hybrid system
varargin extra arguments
Definition at line 18 of file simulate.m.
References calcDynamics(), checkGuard(), handle.fieldnames, str_index(), and struct_overlay().
Member Data Documentation
ContinuousDynamics.EventFuncs
The event functions.
The event functions are often subset of the unilateral constraints defined on the system. For flexibility, we define them separately.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 258 of file ContinuousDynamics.m.
ContinuousDynamics.Flow
The flow (trajectory) from the dynamical system simulation.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 176 of file ContinuousDynamics.m.
ContinuousDynamics.Fvec
The cell array of the drift vector fields Fvec(x) SymFunction.
We split the Fvec into many sub-vectors Fvec[i], such that
\begin{eqnarray*} Fvec = \sum_i^N Fvec[i] \end{eqnarray*}
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 204 of file ContinuousDynamics.m.
ContinuousDynamics.HolonomicConstraints
The holonomic constraints of the dynamical system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 221 of file ContinuousDynamics.m.
ContinuousDynamics.Mmat
The mass matrix Mmat(x)
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 190 of file ContinuousDynamics.m.
ContinuousDynamics.MmatDx
The left hand side of the dynamical equation: M(x)dx or M(x)ddx.
Note
This property has the MATLAB attribute Hidden set to true.
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 323 of file ContinuousDynamics.m.
ContinuousDynamics.PostProcess
pre-process function handle of the object after the simulation
The function handle should have the syntax
postPorcess(sys, sol, controller, params, varargin)
Definition at line 75 of file ContinuousDynamics.m.
ContinuousDynamics.PreProcess
pre-process function handle of the object before the simulation
The function handle should have the syntax
preProcess(sys, controller, params, varargin)
Definition at line 63 of file ContinuousDynamics.m.
ContinuousDynamics.UnilateralConstraints
The unilateral constraints of the dynamical system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 234 of file ContinuousDynamics.m.
ContinuousDynamics.UserNlpConstraint
A handle to a function called by a trajectory optimization NLP to enforce system specific constraints.
The function handle should have the syntax
userNlpConstraint(nlp, bounds, varargin)
Definition at line 87 of file ContinuousDynamics.m.
ContinuousDynamics.VirtualConstraints
The virtual constraints of the dynamical system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 246 of file ContinuousDynamics.m.
The documentation for this class was generated from the following files:
system/@ContinuousDynamics/ContinuousDynamics.m
system/@ContinuousDynamics/addEvent.m
system/@ContinuousDynamics/addHolonomicConstraint.m
system/@ContinuousDynamics/addUnilateralConstraint.m
system/@ContinuousDynamics/addVirtualConstraint.m
system/@ContinuousDynamics/calcDriftVector.m
system/@ContinuousDynamics/calcDynamics.m
system/@ContinuousDynamics/calcMassMatrix.m
system/@ContinuousDynamics/checkGuard.m
system/@ContinuousDynamics/compile.m
system/@ContinuousDynamics/firstOrderDynamics.m
system/@ContinuousDynamics/removeEvent.m
system/@ContinuousDynamics/removeHolonomicConstraint.m
system/@ContinuousDynamics/removeUnilateralConstraint.m
system/@ContinuousDynamics/removeVirtualConstraint.m
system/@ContinuousDynamics/secondOrderDynamics.m
system/@ContinuousDynamics/setDriftVector.m
system/@ContinuousDynamics/setMassMatrix.m
system/@ContinuousDynamics/simulate.m