FROST: SymExpression Class Reference
SymExpression Class Reference
An object that represents a symbolic expression in Mathematica.
Public Member Functions
SymExpression (x, varargin)
The class constructor function.
function delete ()
object destruction function
function display (namestr)
Display the symbolic expression.
function y = argnames ()
Symbolic function input variables ARGNAMES(F) returns a sym array [X1, X2, ... ] of symbolic variables for F(X1, X2, ...).
function x = formula ()
Symbolic expression formula body FORMULA(F) returns the definition of symbolic function F as a sym object expression.
function x = symbol ()
Symbolic expression symbol string SYMBOL(F) returns the symbolc string of symbolic expression F as a sym object expression.
function y = privToCell ()
function y = length ()
The length of the symbolic vector LENGTH(X) returns the length of vector X. It is equivalent to MAX(SIZE(X)) for non-empty arrays and 0 for empty ones.
function varargout = size ()
The size of the symbolic expression tensor.
function status = islist ()
Check if the symbolic expression is a scalar (non-list)
function X = first ()
function B = uminus ()
------------— Arithmetic --------------— Symbolic negation.
function B = uplus ()
Unary plus.
function X = plus (B)
Symbolic plus operation.
function X = minus (B)
Symbolic minus operation.
function X = times (B)
Symbolic array multiplication. TIMES(A,B) overloads symbolic A .* B.
function X = mtimes (B)
Symbolic matrix multiplication. MTIMES(A,B) overloads symbolic A * B.
function B = mpower (p)
Symbolic matrix power. MPOWER(A,p) overloads symbolic A^p.
function B = power (p)
Symbolic array power. POWER(A,p) overloads symbolic A.^p.
function X = rdivide (B)
Symbolic array right division. RDIVIDE(A,B) overloads symbolic A ./ B.
function X = ldivide (B)
Symbolic array left division. LDIVIDE(A,B) overloads symbolic A . B.
function X = mrdivide (B)
/ Slash or symbolic right matrix divide. A/B is the matrix division of B into A, which is roughly the same as A*INV(B) , except it is computed in a different way. More precisely, A/B = (B)'. See SYM/MLDIVIDE for details. Warning messages are produced if X does not exist or is not unique. Rectangular matrices A are allowed, but the equations must be consistent; a least squares solution is not computed.
function X = mldivide (B)
Symbolic matrix left division. MLDIVIDE(A,B) overloads symbolic A \ B. X = A solves the symbolic linear equations A*X = B. Warning messages are produced if X does not exist or is not unique. Rectangular matrices A are allowed, but the equations must be consistent; a least squares solution is not computed.
function B = transpose ()
Symbolic matrix transpose. TRANSPOSE(A) overloads symbolic A.' .
function B = ctranspose ()
Symbolic matrix complex conjugate transpose. CTRANSPOSE(A) overloads symbolic A' .
function B = inv ()
Symbolic matrix inverse. INV(A) computes the symbolic inverse of A INV(VPA(A)) uses variable precision arithmetic.
function y = eq (B)
Symbolic equality test. EQ(A,B) overloads symbolic A == B. If A and B are integers, rational numbers, floating point values or complex numbers then A == B compares the values and returns true or false. Otherwise A == B returns a sym object of the unevaluated equation which can be passed to other functions like solve. To force the equation to perform a comparison call LOGICAL or isAlways. LOGICAL will compare the two sides structurally. isAlways will compare the two sides mathematically.
function y = ne (B)
NE Symbolic inequality test. NE(A,B) overloads symbolic A ~= B. The result is the opposite of A == B.
function C = subsasgn (Idx, R)
Subscripted assignment for a sym array. C = SUBSASGN(L,Idx,R) is called for the syntax L(Idx)=R. Idx is a structure array with the fields: type – string containing () specifying the subscript type. Only parenthesis subscripting is allowed. subs – Cell array or string containing the actual subscripts.
function B = subsref (Idx)
Subscripted reference for a sym array. B = SUBSREF(A,S) is called for the syntax A(I). S is a structure array with the fields: type – string containing () specifying the subscript type. Only parenthesis subscripting is allowed. subs – Cell array or string containing the actual subscripts.
function y = end (varargin)
Last index in an indexing expression for a sym array. END(A,K,N) is called for indexing expressions involving the sym array A when END is part of the K-th index out of N indices. For example, the expression A(end-1,:) calls A's END method with END(A,1,2).
function X = double ()
Converts symbolic matrix to MATLAB double. DOUBLE(S) converts the symbolic matrix S to a matrix of double precision floating point numbers. S must not contain any symbolic variables, except eps.
function M = char ()
Convert scalar or array sym to string. CHAR(A) returns a string representation of the symbolic object A in MuPAD syntax.
Protected Attributes
char f
The body (or formula) of the symbolic expression.
char s
The symbol that represents the symbolic expression.
Additional Inherited Members
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Detailed Description
An object that represents a symbolic expression in Mathematica.
Copyright (c) 2016-2017, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file SymExpression.m.
Constructor & Destructor Documentation
SymExpression.SymExpression (x, varargin)
The class constructor function.
Parameters
x it could be one of the followings:
SymExpression: it will copy one SymExpression object to antother
numeric: create a numeric symbolic expression
char: create symbolic expression specified by x
Required fields of x:
Definition at line 60 of file SymExpression.m.
References end(), eval_math(), formula(), and general2math().
Referenced by argnames(), char(), ctranspose(), double(), end(), eq(), SymFunction.export(), SymFunction.exportHessian(), SymFunction.exportJacobian(), first(), inv(), islist(), ldivide(), minus(), mldivide(), mpower(), mrdivide(), mtimes(), ne(), plus(), power(), privToCell(), rdivide(), SymVariable.subsasgn(), subsasgn(), SymVariable.subsref(), subsref(), SymFunction.SymFunction(), SymVariable.SymVariable(), times(), transpose(), uminus(), and uplus().
Member Function Documentation
function y = SymExpression.argnames ()
Symbolic function input variables ARGNAMES(F) returns a sym array [X1, X2, ... ] of symbolic variables for F(X1, X2, ...).
Definition at line 157 of file SymExpression.m.
References SymExpression().
function M = SymExpression.char ()
Convert scalar or array sym to string. CHAR(A) returns a string representation of the symbolic object A in MuPAD syntax.
Note
This method has the MATLAB method attribute Hidden set to true.
matlab documentation of method attributes.
Definition at line 984 of file SymExpression.m.
References eval_math(), and SymExpression().
function B = SymExpression.ctranspose ()
Symbolic matrix complex conjugate transpose. CTRANSPOSE(A) overloads symbolic A' .
Example
[a b; 1-i c]' returns [ conj(a), 1+i] [ conj(b), conj(c)].
See also
SYM/TRANSPOSE.
Definition at line 620 of file SymExpression.m.
References SymExpression().
function SymExpression.delete ()
object destruction function
Definition at line 136 of file SymExpression.m.
function SymExpression.display (namestr)
Display the symbolic expression.
Definition at line 146 of file SymExpression.m.
References eval_math().
function X = SymExpression.double ()
Converts symbolic matrix to MATLAB double. DOUBLE(S) converts the symbolic matrix S to a matrix of double precision floating point numbers. S must not contain any symbolic variables, except eps.
See also
SYM, VPA.
Note
This method has the MATLAB method attribute Hidden set to true.
matlab documentation of method attributes.
Definition at line 960 of file SymExpression.m.
References eval_math(), and SymExpression().
function y = SymExpression.end (varargin)
Last index in an indexing expression for a sym array. END(A,K,N) is called for indexing expressions involving the sym array A when END is part of the K-th index out of N indices. For example, the expression A(end-1,:) calls A's END method with END(A,1,2).
See also
SYM.
Note
This method has the MATLAB method attribute Hidden set to true.
matlab documentation of method attributes.
Definition at line 927 of file SymExpression.m.
References length(), size(), and SymExpression().
Referenced by SymFunction.export(), SymFunction.exportHessian(), SymFunction.exportJacobian(), first(), ldivide(), mldivide(), mrdivide(), mtimes(), rdivide(), size(), SymVariable.subsasgn(), subsasgn(), SymVariable.subsref(), subsref(), SymExpression(), SymFunction.SymFunction(), SymVariable.SymVariable(), and times().
function y = SymExpression.eq (B)
Symbolic equality test. EQ(A,B) overloads symbolic A == B. If A and B are integers, rational numbers, floating point values or complex numbers then A == B compares the values and returns true or false. Otherwise A == B returns a sym object of the unevaluated equation which can be passed to other functions like solve. To force the equation to perform a comparison call LOGICAL or isAlways. LOGICAL will compare the two sides structurally. isAlways will compare the two sides mathematically.
See also
SYM/LOGICAL, SYM/isAlways
Required fields of B:
Definition at line 679 of file SymExpression.m.
References eval_math(), and SymExpression().
function X = SymExpression.first ()
Definition at line 276 of file SymExpression.m.
References end(), islist(), and SymExpression().
Referenced by ldivide(), rdivide(), and times().
function x = SymExpression.formula ()
Symbolic expression formula body FORMULA(F) returns the definition of symbolic function F as a sym object expression.
Definition at line 169 of file SymExpression.m.
Referenced by SymExpression().
function B = SymExpression.inv ()
Symbolic matrix inverse. INV(A) computes the symbolic inverse of A INV(VPA(A)) uses variable precision arithmetic.
Examples
Suppose B is [ 1/(2-t), 1/(3-t) ] [ 1/(3-t), 1/(4-t) ]
Then inv(B) is [ -(-3+t)^2*(-2+t), (-3+t)*(-2+t)*(-4+t) ] [ (-3+t)*(-2+t)*(-4+t), -(-3+t)^2*(-4+t) ]
Definition at line 646 of file SymExpression.m.
References SymExpression().
function status = SymExpression.islist ()
Check if the symbolic expression is a scalar (non-list)
Definition at line 258 of file SymExpression.m.
References eval_math(), and SymExpression().
Referenced by first(), ldivide(), rdivide(), and times().
function X = SymExpression.ldivide (B)
Symbolic array left division. LDIVIDE(A,B) overloads symbolic A . B.
See also
SYM/RDIVIDE, SYM/MRDIVIDE, SYM/MLDIVIDE, SYM/QUOREM.
Required fields of B:
Definition at line 505 of file SymExpression.m.
References end(), first(), islist(), and SymExpression().
Referenced by mldivide().
function y = SymExpression.length ()
The length of the symbolic vector LENGTH(X) returns the length of vector X. It is equivalent to MAX(SIZE(X)) for non-empty arrays and 0 for empty ones.
See also
NUMEL, SIZE
Definition at line 199 of file SymExpression.m.
References size().
Referenced by end(), SymFunction.exportHessian(), SymVariable.subsasgn(), and subsasgn().
function X = SymExpression.minus (B)
Symbolic minus operation.
Required fields of B:
Definition at line 345 of file SymExpression.m.
References SymExpression().
function X = SymExpression.mldivide (B)
Symbolic matrix left division. MLDIVIDE(A,B) overloads symbolic A \ B. X = A solves the symbolic linear equations A*X = B. Warning messages are produced if X does not exist or is not unique. Rectangular matrices A are allowed, but the equations must be consistent; a least squares solution is not computed.
See also
SYM/MRDIVIDE, SYM/LDIVIDE, SYM/RDIVIDE, SYM/QUOREM.
Required fields of B:
Definition at line 565 of file SymExpression.m.
References end(), ldivide(), and SymExpression().
function B = SymExpression.mpower (p)
Symbolic matrix power. MPOWER(A,p) overloads symbolic A^p.
Example; A = [x y; alpha 2] A^2 returns [x^2+alpha*y x*y+2*y; alpha*x+2*alpha alpha*y+4].
Required fields of p:
Definition at line 421 of file SymExpression.m.
References SymExpression().
function X = SymExpression.mrdivide (B)
/ Slash or symbolic right matrix divide. A/B is the matrix division of B into A, which is roughly the same as A*INV(B) , except it is computed in a different way. More precisely, A/B = (B)'. See SYM/MLDIVIDE for details. Warning messages are produced if X does not exist or is not unique. Rectangular matrices A are allowed, but the equations must be consistent; a least squares solution is not computed.
See also
SYM/MLDIVIDE, SYM/RDIVIDE, SYM/LDIVIDE, SYM/QUOREM.
Required fields of B:
Definition at line 534 of file SymExpression.m.
References end(), rdivide(), and SymExpression().
function X = SymExpression.mtimes (B)
Symbolic matrix multiplication. MTIMES(A,B) overloads symbolic A * B.
Required fields of B:
Definition at line 394 of file SymExpression.m.
References end(), SymExpression(), and times().
function y = SymExpression.ne (B)
NE Symbolic inequality test. NE(A,B) overloads symbolic A ~= B. The result is the opposite of A == B.
Required fields of B:
Definition at line 710 of file SymExpression.m.
References eval_math(), and SymExpression().
function X = SymExpression.plus (B)
Symbolic plus operation.
Required fields of B:
Definition at line 325 of file SymExpression.m.
References SymExpression().
function B = SymExpression.power (p)
Symbolic array power. POWER(A,p) overloads symbolic A.^p.
Examples
A = [x 10 y; alpha 2 5]; A .^ 2 returns [x^2 100 y^2; alpha^2 4 25]. A .^ x returns [x^x 10^x y^x; alpha^x 2^x 5^x]. A .^ A returns [x^x 1.0000e+10 y^y; alpha^alpha 4 3125]. A .^ [1 2 3; 4 5 6] returns [x 100 y^3; alpha^4 32 15625]. A .^ magic(3) is an error.
Required fields of p:
Definition at line 446 of file SymExpression.m.
References SymExpression().
function y = SymExpression.privToCell ()
Definition at line 194 of file SymExpression.m.
References eval_math(), and SymExpression().
function X = SymExpression.rdivide (B)
Symbolic array right division. RDIVIDE(A,B) overloads symbolic A ./ B.
See also
SYM/LDIVIDE, SYM/MRDIVIDE, SYM/MLDIVIDE, SYM/QUOREM.
Required fields of B:
Definition at line 475 of file SymExpression.m.
References end(), first(), islist(), and SymExpression().
Referenced by mrdivide().
function varargout = SymExpression.size ()
The size of the symbolic expression tensor.
See also
NUMEL, LENGTH
Definition at line 216 of file SymExpression.m.
References end(), and eval_math().
Referenced by end(), length(), SymVariable.subsasgn(), and subsasgn().
function C = SymExpression.subsasgn (Idx, R)
Subscripted assignment for a sym array. C = SUBSASGN(L,Idx,R) is called for the syntax L(Idx)=R. Idx is a structure array with the fields: type – string containing () specifying the subscript type. Only parenthesis subscripting is allowed. subs – Cell array or string containing the actual subscripts.
See also
SYM.
Required fields of Idx:
Note
This method has the MATLAB method attribute Hidden set to true.
matlab documentation of method attributes.
Definition at line 741 of file SymExpression.m.
References end(), eval_math(), general2math(), length(), mat2math(), size(), symbol(), and SymExpression().
function B = SymExpression.subsref (Idx)
Subscripted reference for a sym array. B = SUBSREF(A,S) is called for the syntax A(I). S is a structure array with the fields: type – string containing () specifying the subscript type. Only parenthesis subscripting is allowed. subs – Cell array or string containing the actual subscripts.
Required fields of Idx:
Note
This method has the MATLAB method attribute Hidden set to true.
matlab documentation of method attributes.
Definition at line 844 of file SymExpression.m.
References end(), eval_math(), mat2math(), and SymExpression().
function x = SymExpression.symbol ()
Symbolic expression symbol string SYMBOL(F) returns the symbolc string of symbolic expression F as a sym object expression.
Definition at line 182 of file SymExpression.m.
Referenced by SymVariable.subsasgn(), and subsasgn().
function X = SymExpression.times (B)
Symbolic array multiplication. TIMES(A,B) overloads symbolic A .* B.
Required fields of B:
Definition at line 365 of file SymExpression.m.
References end(), first(), islist(), and SymExpression().
Referenced by mtimes().
function B = SymExpression.transpose ()
Symbolic matrix transpose. TRANSPOSE(A) overloads symbolic A.' .
Example
[a b; 1-i c].' returns [a 1-i; b c].
See also
SYM/CTRANSPOSE.
Definition at line 595 of file SymExpression.m.
References SymExpression().
function B = SymExpression.uminus ()
------------— Arithmetic --------------— Symbolic negation.
Definition at line 288 of file SymExpression.m.
References SymExpression().
function B = SymExpression.uplus ()
Unary plus.
Definition at line 307 of file SymExpression.m.
References SymExpression().
Member Data Documentation
SymExpression.f protected
The body (or formula) of the symbolic expression.
Definition at line 36 of file SymExpression.m.
Referenced by SymFunction.export().
SymExpression.s protected
The symbol that represents the symbolic expression.
Definition at line 47 of file SymExpression.m.
Referenced by SymFunction.exportHessian(), and SymFunction.exportJacobian().
The documentation for this class was generated from the following file:
symbolic/@SymExpression/SymExpression.m