FROST: JointPD Class Reference
JointPD Class Reference
This class defines a PD feedback control on the joint space.
Public Member Functions
JointPD (char name)
The controller class constructor function.
function obj = setParam (varargin)
Sets the controller parameters.
function [ u , extra ] = calcControl (double t,colvec qe,colvec dqe,colvec vfc,colvec gfc,Domain domain)
Computes the PD feedback control law on joint space.
Public Member Functions inherited from Controller
Controller (char name)
The controller class constructor function.
virtual function [ u , extra ] = calcControl (t, qe, dqe, vfc, gfc, domain)
Additional Inherited Members
Public Attributes inherited from Controller
char Name
The name of the controller.
struct Param
The parameters of the controller.
Detailed Description
This class defines a PD feedback control on the joint space.
Author
ayonga
Date
2016-10-14
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file JointPD.m.
Constructor & Destructor Documentation
JointPD.JointPD (char name)
The controller class constructor function.
Parameters
name the controller name
Definition at line 44 of file JointPD.m.
References calcControl(), Controller.Controller(), and setParam().
Member Function Documentation
function [ colvec u , struct extra ] = JointPD.calcControl (double t, colvec qe, colvec dqe, colvec vfc, colvec gfc, Domain domain)
Computes the PD feedback control law on joint space.
Parameters
t the time instant
qe the joint configuration
dqe the joint velocities
vfc the vector field f(x)
gfc the vector field g(x)
domain the continuous domain
Return values
u the computed torque
extra additional computed data
Generated fields of extra:
Definition at line 18 of file calcControl.m.
Referenced by JointPD().
function obj = JointPD.setParam (varargin) virtual
Sets the controller parameters.
Parameters
varargin name-value pairs of control parameters. Expected arguments are:
setParam (kp, kd)
Required Parameters for varargin:
kp kp
kd kd
Generated fields of obj:
Implements Controller.
Definition at line 18 of file setParam.m.
Referenced by JointPD().
The documentation for this class was generated from the following files:
control/@JointPD/JointPD.m
control/@JointPD/calcControl.m
control/@JointPD/setParam.m