FROST: VirtualConstrDomain Class Reference
VirtualConstrDomain Class Reference
Defines a subclass of continuous domain with virtual constraints.
Public Member Functions
VirtualConstrDomain (name, varargin)
The class constructor function.
function obj = setPhaseVariable (char type,Kinematics var)
Sets the parameterized time variable (phase variable)
function obj = setVelocityOutput (Kinemtics act,char des)
Adds a velocity-modulating output of the domain.
function obj = addPositionOutput (Kinemtics act,char des)
Adds position-modulating outputs of the domain.
function obj = removePositionOutput (Kinemtics act)
Removes position-modulating outputs from the domain.
function obj = changeDesiredOutputType (varargin)
Sets the function type of desired outputs.
function obj = setParam (varargin)
Sets the parameter value of the desired outputs.
function y_act = calcActualOutputs (colvec qe,colvec dqe)
Calculate the actual outputs of the domain.
function [ y_des , extra ] = calcDesiredOutputs (double t,colvec qe,colvec dqe)
Calculates the desired outputs of the domain.
function obj = compile (RigidBodyModel model, varargin)
Compiles the symbolic expression of kinematic functions related to the domain in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function indices = getPositionOutputIndex (cell output_name)
Returns the indices of the position modulating outputs of the domain specified by 'output_name'.
Public Member Functions inherited from Domain
Domain (char name)
the calss constructor for Domain class
function obj = addContact (KinematicContact contacts)
Adds a contact constraint for the domain.
function obj = addHolonomicConstraint (Kinematic kins)
Adds holonomic kinematic constraints other than contact constraints to the domain.
function obj = addUnilateralConstraint (Kinematic kins)
Adds unilateral kinematic constraints other than contact constraints to the domain.
function obj = removeContact (contacts)
Removes holonomic kinematic constraints other than contact constraints from the domain.
function obj = removeHolonomicConstraint (Kinematic kins)
Removes holonomic kinematic constraints other than contact constraints from the domain.
function obj = removeUnilateralConstraint (Kinematic kins)
Removes unilateral kinematic constraints other than contact constraints from the domain.
function obj = setAcutation (RigidBodyModel model,cellstr actuated_joints)
Sets the actuation map for the current domain.
function obj = compile (RigidBodyModel model, varargin)
Compiles the symbolic expression of kinematic functions related to the domain in Mathematica.
function obj = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function Fe = calcConstraintForces (varargin)
Calculates the constraints forces exert on the kinematic constraints of the rigid body model.
function value = calcUnilateralCondition (cell cond,RigidBodyModel model,colvec qe,colvec dqe,colvec u)
Calculates the unilateral condition specified by 'cond'.
function [ vfc , gfc ] = calcVectorFields (RigidBodyModel model,colvec qe,colvec dqe,matrix De,colvec He)
Calculates the vector fields of the affine control system \(dot{x} = f(x) + g(x)*u\) for the constrained dynamics.
Static Public Member Functions
static function [ expr , n_param ] = getDesOutputExpr (char type)
Returns the symbolic expression of desired velocity output based on the function type.
Public Attributes
struct PhaseVariable
The parameterized time variable (phase variable)
struct DesPositionOutput
The desired position-modulating outputs of the domain.
struct DesVelocityOutput
The desired velocity-modulating outputs of the domain.
KinematicGroup ActPositionOutput
The actual position-modulating outputs of the domain.
Kinematics ActVelocityOutput
The actual velocity-modulating output of the domain.
struct Param
The parameter set of the domain.
Public Attributes inherited from Domain
char Name
% basic properties This is the name of the object that gives the object an universal identification
KinematicGroup HolonomicConstr
% holonomic constraints A group of holonomic kinematic constraints
table UnilateralConstr
% unilateral constraints A table of all unilateral constraints
matrix ActuationMap
% actuation a map for robot actuation on the current domain
Detailed Description
Defines a subclass of continuous domain with virtual constraints.
Author
ayonga
Date
2016-09-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file VirtualConstrDomain.m.
Constructor & Destructor Documentation
VirtualConstrDomain.VirtualConstrDomain (name, varargin)
The class constructor function.
Required fields of PhaseVariable:
Type — the type of the parameterized time variable
Var — the kinematic object if it is a state-based phase variable
Param — the scaling parameters of the state-based phase variable
Optional fields of Param:
p — the scaling parameters of the phase variable
v — the parameters of the desired velocity output
a — the parameters of the desired position outputs
Definition at line 124 of file VirtualConstrDomain.m.
References addPositionOutput(), calcActualOutputs(), calcDesiredOutputs(), changeDesiredOutputType(), compile(), Domain.Domain(), export(), getDesOutputExpr(), getPositionOutputIndex(), removePositionOutput(), setParam(), setPhaseVariable(), and setVelocityOutput().
Member Function Documentation
function obj = VirtualConstrDomain.addPositionOutput (Kinemtics act, char des)
Adds position-modulating outputs of the domain.
Parameters
act the kinematic function for the actual position-modulating output
des the function type of the desired output
Generated fields of obj:
Definition at line 18 of file addPositionOutput.m.
Referenced by VirtualConstrDomain().
function struct y_act = VirtualConstrDomain.calcActualOutputs (colvec qe, colvec dqe)
Calculate the actual outputs of the domain.
Parameters
qe joint configuration
dqe joint velocities
Return values
y_act the actual outputs
Required fields of y_act:
ya1 — the actual velocity (RD1) output
Dya1 — the first order partial derivatives of ya1 w.r.t to system states
ya2 — the actual position (RD2) outputs
Dya2 — the first order partial derivatives of ya2 w.r.t to system states
DLfya2 — the second order partial derivatives of ya2 w.r.t to system states
Generated fields of y_act:
Definition at line 18 of file calcActualOutputs.m.
Referenced by VirtualConstrDomain().
function y_des = VirtualConstrDomain.calcDesiredOutputs (double t, colvec qe, colvec dqe)
Calculates the desired outputs of the domain.
Parameters
t time
qe joint configuration
dqe joint velocities
Return values
y_act the actual outputs
extra extra computated data
Required fields of y_des:
yd1 — the desired velocity (RD1) output
Dyd1 — the first order partial derivatives of yd1 w.r.t to system states
yd2 — the desired position (RD2) outputs
Dyd2 — the first order partial derivatives of yd2 w.r.t to system states
DLfyd2 — the second order partial derivatives of yd2 w.r.t to system states
tau — the phase variable
dtau — the time derivative of the phase variable
Generated fields of y_des:
Definition at line 18 of file calcDesiredOutputs.m.
Referenced by VirtualConstrDomain().
function obj = VirtualConstrDomain.changeDesiredOutputType (varargin)
Sets the function type of desired outputs.
Parameters
varargin name-parameter pairs of input argument.
Generated fields of obj:
Definition at line 18 of file changeDesiredOutputType.m.
Referenced by VirtualConstrDomain().
function obj = VirtualConstrDomain.compile (RigidBodyModel model, varargin)
Compiles the symbolic expression of kinematic functions related to the domain in Mathematica.
See also
Kinematics.compile
Definition at line 18 of file compile.m.
References Domain.Domain(), and eval_math().
Referenced by VirtualConstrDomain().
function logical status = VirtualConstrDomain.export (char export_path, logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
Parameters
export_path the complete directory path where the compiled symbolic function will be exported to
do_build determine whether build the mex files. Default: true
Return values
status indicator of successful export/built process
Definition at line 18 of file export.m.
References build_mex(), Domain.Domain(), eval_math(), and str2mathstr().
Referenced by VirtualConstrDomain().
function [ expr , n_param ] = VirtualConstrDomain.getDesOutputExpr (char type) static
Returns the symbolic expression of desired velocity output based on the function type.
Parameters
type the desired output function type
Definition at line 18 of file getDesOutputExpr.m.
Referenced by VirtualConstrDomain().
function indices = VirtualConstrDomain.getPositionOutputIndex (cell output_name)
Returns the indices of the position modulating outputs of the domain specified by 'output_name'.
Parameters
output_name an array of output names
Definition at line 18 of file getPositionOutputIndex.m.
Referenced by VirtualConstrDomain().
function obj = VirtualConstrDomain.removePositionOutput (Kinemtics act)
Removes position-modulating outputs from the domain.
Parameters
act the kinematic function for the actual position-modulating output
Generated fields of obj:
Definition at line 18 of file removePositionOutput.m.
Referenced by VirtualConstrDomain().
function obj = VirtualConstrDomain.setParam (varargin)
Sets the parameter value of the desired outputs.
Parameters
varargin name-value pairs of parameter sets. For instance, (a, a_mat). It could be also given as a structured data with each field contains a set of parameters.
Generated fields of obj:
Definition at line 18 of file setParam.m.
Referenced by VirtualConstrDomain().
function obj = VirtualConstrDomain.setPhaseVariable (char type, Kinematics var)
Sets the parameterized time variable (phase variable)
Parameters
type The type of phase variable, it could be either TimeBased or StateBased
var only valid if use StateBased variable.
Required fields of var:
Generated fields of obj:
Definition at line 18 of file setPhaseVariable.m.
References Kinematics.Prefix.
Referenced by VirtualConstrDomain().
function obj = VirtualConstrDomain.setVelocityOutput (Kinemtics act, char des)
Adds a velocity-modulating output of the domain.
Parameters
act the kinematic function for the velocity-modulating output
des the function type of the desired output
Generated fields of obj:
Definition at line 18 of file setVelocityOutput.m.
Referenced by VirtualConstrDomain().
Member Data Documentation
VirtualConstrDomain.ActPositionOutput
The actual position-modulating outputs of the domain.
The position-modulating outputs are (vector) relative degree two by definition.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 75 of file VirtualConstrDomain.m.
VirtualConstrDomain.ActVelocityOutput
The actual velocity-modulating output of the domain.
The velocity-modulating outputs are relative degree one by definition.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 90 of file VirtualConstrDomain.m.
VirtualConstrDomain.DesPositionOutput
The desired position-modulating outputs of the domain.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 51 of file VirtualConstrDomain.m.
VirtualConstrDomain.DesVelocityOutput
The desired velocity-modulating outputs of the domain.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 63 of file VirtualConstrDomain.m.
VirtualConstrDomain.Param
The parameter set of the domain.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 105 of file VirtualConstrDomain.m.
VirtualConstrDomain.PhaseVariable
The parameterized time variable (phase variable)
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 39 of file VirtualConstrDomain.m.
The documentation for this class was generated from the following files:
system/@VirtualConstrDomain/VirtualConstrDomain.m
system/@VirtualConstrDomain/addPositionOutput.m
system/@VirtualConstrDomain/calcActualOutputs.m
system/@VirtualConstrDomain/calcDesiredOutputs.m
system/@VirtualConstrDomain/changeDesiredOutputType.m
system/@VirtualConstrDomain/compile.m
system/@VirtualConstrDomain/export.m
system/@VirtualConstrDomain/getDesOutputExpr.m
system/@VirtualConstrDomain/getPositionOutputIndex.m
system/@VirtualConstrDomain/removePositionOutput.m
system/@VirtualConstrDomain/setParam.m
system/@VirtualConstrDomain/setPhaseVariable.m
system/@VirtualConstrDomain/setVelocityOutput.m