AMBER Suite: NonlinearProgram Class Reference
NonlinearProgram Class Reference
NonlinearProgram defines an abstract class for general nonlinear programing problems.
Public Member Functions
NonlinearProgram (name, varargin)
The default class constructor function.
function obj = addVariable (char name,integer dimension, varargin)
This method registers the information of an optimization variable.
function obj = genVarIndices ()
Generate indices for all optimization variables. It must be run after registered all optimization variables.
function obj = addCost (char name,cell deps, extra)
This method registers the information of a NLP function as a cost function.
function obj = addConstraint (char name,cell deps, dimension, cl, cu, extra)
This method registers the information of a NLP function as a constraint.
function [ integer dimOptVar ,
colvec lb ,
colvec ub ] = getVarInfos ()
The function returns the dimension, upper/lower limits of NLP variables.
function obj = genCostIndices ()
This function generates the indexing information for cost functions.
function [ NlpCost costArray ,
struct
costInfos ] = getCostInfos ()
This function returns the indexing information of the cost function array, including the Gradient and Hessian (if applicable) sparse structures.
function obj = genConstrIndices (char solver)
This function generates the indexing information for constraints.
function obj = genConstrIndicesIpopt ()
This function generates the indexing information for constraints for IPOPT.
function [
constrArray ,
constrInfos ] = getConstrInfos (char solver)
This function returns the indexing information of the constraints function array, including the Gradient and Hessian (if applicable) sparse structures.
function [ NlpConstr constrArray ,
struct
constrInfos ] = getConstrInfosIpopt ()
This function returns the indexing information of the constraints function array, including the Gradient and Hessian (if applicable) sparse structures.
function z0 = getStartingPoint (varargin)
Returns an initial guess for the NLP.
function obj = setInitialGuess (z0)
Public Attributes
char name
The name identification.
NlpVar optVars
The structure array contains all information regarding NLP optimization variables.
struct optVarIndices
A data structure that stores the indexing of optimization variables.
NlpCost costArray
Contains the information of registered cost functions in the form of structure array.
NlpConstr constrArray
Contains the information of registered constraints in the form of structure array.
struct options
The class option.
Protected Attributes
colvec z0
The initial guess of the decision variables.
Detailed Description
NonlinearProgram defines an abstract class for general nonlinear programing problems.
Author
Ayonga Hereid
Date
2016-10-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file NonlinearProgram.m.
Constructor & Destructor Documentation
NonlinearProgram.NonlinearProgram (name, varargin)
The default class constructor function.
Parameters
varargin@code NonlinearProgram (..., name, "withHessian", withHessian_value ]) Required Parameters for varargin:
name name
Named Parameters for varargin:
withHessian withHessian (Default: false)
Definition at line 153 of file NonlinearProgram.m.
Referenced by TrajectoryOptimization.TrajectoryOptimization().
Member Function Documentation
function obj = NonlinearProgram.addConstraint (char name, cell deps, dimension, cl, cu, extra)
This method registers the information of a NLP function as a constraint.
Parameters
name name of the variable
deps a list of dependent variables
dimension the dimension of the constraint vector
cl the lower bound
cu the upper bound
extra (optional) extra input argument for functions
See Also
NlpConstr NlpFcn
Generated fields of obj:
Definition at line 302 of file NonlinearProgram.m.
function obj = NonlinearProgram.addCost (char name, cell deps, extra)
This method registers the information of a NLP function as a cost function.
See Also
NlpFcn
Parameters
name name of the variable
deps a list of dependent variables
extra (optional) extra constant input argument for functions
Generated fields of obj:
Definition at line 244 of file NonlinearProgram.m.
function obj = NonlinearProgram.addVariable (char name, integer dimension, varargin)
This method registers the information of an optimization variable.
Syntex
nlp = addVariable(nlp, name, 10, 0, 1)
Parameters
name name of the variable
dimension dimension of the variable
varargin@code addVariable (..., lb, ub) Required Parameters for varargin:
lb lower limit
ub upper limit
Generated fields of obj:
Definition at line 185 of file NonlinearProgram.m.
function obj = NonlinearProgram.genConstrIndices (char solver)
This function generates the indexing information for constraints.
Note
Indexing NLP constraints depends on different NLP solver being used. By default, we assume ipopt being used, with which all constraints are catagorized into one big group. If fmincon being used, then there will be linear/nonlinear and equality/inequality constraints, and each group of constraints are indexed separately.
Parameters
solver a string indicates the NLP solver being used Default: ipopt
Todo:
implement indexing function for fmincon
Todo:
implement indexing function for snopt
Definition at line 490 of file NonlinearProgram.m.
References genConstrIndicesIpopt().
Referenced by getConstrInfos().
function obj = NonlinearProgram.genConstrIndicesIpopt ()
This function generates the indexing information for constraints for IPOPT.
Definition at line 530 of file NonlinearProgram.m.
Referenced by genConstrIndices().
function obj = NonlinearProgram.genCostIndices ()
This function generates the indexing information for cost functions.
Definition at line 380 of file NonlinearProgram.m.
Referenced by getCostInfos().
function obj = NonlinearProgram.genVarIndices ()
Generate indices for all optimization variables. It must be run after registered all optimization variables.
Definition at line 220 of file NonlinearProgram.m.
function [ constrArray , constrInfos ] = NonlinearProgram.getConstrInfos (char solver)
This function returns the indexing information of the constraints function array, including the Gradient and Hessian (if applicable) sparse structures.
Note
Indexing NLP constraints depends on different NLP solver being used. By default, we assume ipopt being used, with which all constraints are catagorized into one big group. If fmincon being used, then there will be linear/nonlinear and equality/inequality constraints, and each group of constraints are indexed separately.
Parameters
solver a string indicates the NLP solver being used Default: ipopt
Todo:
implement indexing function for fmincon
Todo:
implement indexing function for snopt
Definition at line 575 of file NonlinearProgram.m.
References constrArray, genConstrIndices(), and getConstrInfosIpopt().
function [ NlpConstr constrArray , struct constrInfos ] = NonlinearProgram.getConstrInfosIpopt ()
This function returns the indexing information of the constraints function array, including the Gradient and Hessian (if applicable) sparse structures.
Return values
constrArray An array of constraints
constrInfos A structure contains other pre-computed information regarding constraints array.
Required fields of constrInfos:
dimsConstr — The dimension of constraints
cl — The lower bound of constraints
cu — The upper bound of constraints
nnzJac — The number of nonzero entries in the objective gradient vector
gradSparseIndices — row and column indices of the nonzero entries in the sparse Gradient vector
nnzHess — The number of nonzero entries in the cost portion of the Hessian
hessSparseIndices — row and column indices of the nonzero entries in the sparse Hessian matrix associated with the cost function
Generated fields of constrInfos:
Definition at line 620 of file NonlinearProgram.m.
References NlpConstr.cl, and constrArray.
Referenced by getConstrInfos().
function [ NlpCost costArray , struct costInfos ] = NonlinearProgram.getCostInfos ()
This function returns the indexing information of the cost function array, including the Gradient and Hessian (if applicable) sparse structures.
Return values
costArray An array of cost function
costInfos A structure contains other pre-computed information regarding cost array.
Required fields of costInfos:
nnzGrad — The number of nonzero entries in the objective gradient vector
gradSparseIndices — row and column indices of the nonzero entries in the sparse Gradient vector
nnzHess — The number of nonzero entries in the cost portion of the Hessian
hessSparseIndices — row and column indices of the nonzero entries in the sparse Hessian matrix associated with the cost function
Generated fields of costInfos:
Definition at line 415 of file NonlinearProgram.m.
References costArray, genCostIndices(), and NlpFcn.nnzHess.
function z0 = NonlinearProgram.getStartingPoint (varargin)
Returns an initial guess for the NLP.
Definition at line 722 of file NonlinearProgram.m.
References z0.
function [ integer dimOptVar , colvec lb , colvec ub ] = NonlinearProgram.getVarInfos ()
The function returns the dimension, upper/lower limits of NLP variables.
Return values
dimOptVar the total dimension of all NLP variables
lb the lower limits
ub the upper limits
Definition at line 357 of file NonlinearProgram.m.
function obj = NonlinearProgram.setInitialGuess (z0)
Definition at line 734 of file NonlinearProgram.m.
References z0.
Member Data Documentation
NonlinearProgram.constrArray
Contains the information of registered constraints in the form of structure array.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 103 of file NonlinearProgram.m.
Referenced by getConstrInfos(), and getConstrInfosIpopt().
NonlinearProgram.costArray
Contains the information of registered cost functions in the form of structure array.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 90 of file NonlinearProgram.m.
Referenced by getCostInfos().
NonlinearProgram.name
The name identification.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 52 of file NonlinearProgram.m.
NonlinearProgram.options
The class option.
Required fileds of options
withHessian: indicates whether the user-defined Hessian function is provided. Default: false
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 119 of file NonlinearProgram.m.
Referenced by SolverApplication.SolverApplication().
NonlinearProgram.optVarIndices
A data structure that stores the indexing of optimization variables.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 77 of file NonlinearProgram.m.
NonlinearProgram.optVars
The structure array contains all information regarding NLP optimization variables.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 64 of file NonlinearProgram.m.
NonlinearProgram.z0 protected
The initial guess of the decision variables.
Definition at line 138 of file NonlinearProgram.m.
Referenced by getStartingPoint(), and setInitialGuess().
The documentation for this class was generated from the following file:
nlp/@NonlinearProgram/NonlinearProgram.m