FROST: animator Class Reference
animator Class Reference
This class defines a simple basic animator objects for multi-body mechanical systems (a.k.a. robots).
Public Member Functions
animator (model, options, ground)
The constructor function.
function obj = setOption (varargin)
function fig_hl = animate (flow, output_file)
Run the animation.
function [ traj , axis_offset ] = parse (flow)
Public Attributes
struct Options
Options for animation.
Ground Ground
The ground plot options.
struct LineObjects
The line objects to be plotted.
Detailed Description
This class defines a simple basic animator objects for multi-body mechanical systems (a.k.a. robots).
Definition at line 17 of file animator.m.
Constructor & Destructor Documentation
animator.animator (model, options, ground)
The constructor function.
Required fields of model:
Definition at line 61 of file animator.m.
References struct_overlay().
Member Function Documentation
function fig_hl = animator.animate (flow, output_file)
Run the animation.
Definition at line 105 of file animator.m.
References parse().
function [traj , axis_offset ] = animator.parse (flow)
Definition at line 226 of file animator.m.
References even_sample().
Referenced by animate().
function obj = animator.setOption (varargin)
Definition at line 94 of file animator.m.
References struct_overlay().
Member Data Documentation
animator.Ground
The ground plot options.
Definition at line 38 of file animator.m.
animator.LineObjects
The line objects to be plotted.
array
Definition at line 48 of file animator.m.
animator.Options
Options for animation.
Definition at line 28 of file animator.m.
The documentation for this class was generated from the following file:
animator.m