FROST: HybridSystem Class Reference
HybridSystem Class Reference
HybridSystem defines a hybrid dynamical system that has both continuous and discrete dynamics, such as bipedal locomotion.
Public Member Functions
HybridSystem (name, model)
the default calss constructor
function obj = addVertex (varargin)
Adds a vertex or a group of vertices to the directed graph 'Gamma'.
function obj = addEdge (varargin)
Adds an edge or a group of edges to the directed graph 'Gamma'.
function obj = rmVertex (varargin)
Removes a vertex or a group of vertices from the directed graph object 'Gamma'.
function obj = rmEdge (varargin)
Removes a edge or a group of edges from the directed graph object 'Gamma'.
function obj = setEdgeProperties (s, t, varargin)
Sets the values of edge properties.
function obj = setVertexProperties (cellstr vertex, varargin)
Sets the values of vertex properties.
function [ colvec dx , extra ] = calcDynamics (double t,colvec x,table cur_node)
This function computes the continuous dynamics of the dynmical system.
function [ value , isterminal , direction ] = checkGuard (double t,colvec x, cur_node,table assoc_edges)
Detect the guard condition (event trigger)
function obj = simulate (struct options)
Simulate the hybrid dynamical system.
Public Attributes
char Name
This is the name of the object that gives the object an universal identification.
digraph Gamma
The directed graph that describes the hybrid dynamical system structure.
RigidBodyModel Model
The rigid body model of the hybrid system.
cell Flow
The hybrid flows (trajectory) recorder.
struct VertexProperties
A structure describes the name, type, attributes, and default value of each properties of the vertex.
struct EdgeProperties
A structure describes the name, type, attributes, and default value of each properties of the edge.
Detailed Description
HybridSystem defines a hybrid dynamical system that has both continuous and discrete dynamics, such as bipedal locomotion.
This class provides basic elements and functionalities of a hybrid dynamicsl system. The mathematical definition of the hybrid system is given as
\begin{eqnarray*} \mathscr{HC} = \{\Gamma, \mathcal{D}, U, S, \Delta, FG\} \end{eqnarray*}
The implementation of the hybrid system class is heavily based on the Matlab's digraph data type, with wrapper functions with additional validation.
Author
Ayonga Hereid
Date
2016-09-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file HybridSystem.m.
Constructor & Destructor Documentation
HybridSystem.HybridSystem (name, model)
the default calss constructor
Parameters
varargin variable class construction arguments.
Definition at line 171 of file HybridSystem.m.
References addEdge(), addVertex(), calcDynamics(), checkGuard(), rmEdge(), rmVertex(), setEdgeProperties(), setVertexProperties(), and simulate().
Member Function Documentation
function obj = HybridSystem.addEdge (varargin)
Adds an edge or a group of edges to the directed graph 'Gamma'.
This function is a wrapper function of Matlab 'addedge' function. It provides extra data type validations for each properties of an edge, besides it supports more flexible way to assign edge properties. The properties will be given as separate input arguments using 'Name-Value' pairs, and missing properties will be inserted with the default value of the corresponding properties.
Note
To add 'Weights' to the edge, specifity 'Weights' properties as other properties. See detailed explanation of the input arguments.
See also
addedge
Note
A struct can be used to replace the (PropName, PropValue) inputs. To be valid input, the structure must have fields with the same name as vertex properties. For mutilple nodes, use the array of structures instead of the structure of arrays. Invalid fields in the structure will be ignored, and missing properties will be added with their default values.
Parameters
varargin variable types of input arguments.
addEdge (T, s,t, PropName, PropValue)
Required Parameters for varargin:
T a table describes an edge or edges to be added. It must have a variable named 'EndNodes' to be a valid edge. Variables that do not match any of the edge properties will be ignored. Missing edge properties will be added with its default values. Use syntex
sys =  addVertex(sys, T)
s,t the name pairs of the source vertics and target vertices to be added. They must be a cell string or a character array. Use syntex
sys =  addVertex(sys, s, t)
PropName a character vector specifiy the name of an edge property for the added edges. It must be given as a 'Name'-'Value' pairs.
PropValue the values of the edge properties specified by the 'PropName'. It must be scalar or a cell array with the the same length of the number of the vertices to be added. If it is a scalar, all edges will be assign this scalar value. Use syntex
sys =  addVertex(sys, s, t, PropName,PropValue,...)
Generated fields of obj:
Definition at line 18 of file addEdge.m.
References addVertex(), and implode().
Referenced by HybridSystem().
function obj = HybridSystem.addVertex (varargin)
Adds a vertex or a group of vertices to the directed graph 'Gamma'.
This function is a wrapper function of Matlab 'addnode' function. It provides extra data type validations for each properties of a vertex, besides it supports more flexible way to assign properties. The properties will be given as separate input arguments using 'Name-Value' pairs, and missing properties will be inserted with the default value of the corresponding properties.
See also
addnode
Note
A struct can be used to replace the (PropName, PropValue) inputs. To be valid input, the structure must have fields with the same name as vertex properties. For mutilple nodes, use the array of structures instead of the structure of arrays. Invalid fields in the structure will be ignored, and missing properties will be added with their default values.
Parameters
varargin
Definition at line 18 of file addVertex.m.
References implode().
Referenced by addEdge(), and HybridSystem().
function [ colvec dx , extra ] = HybridSystem.calcDynamics (double t, colvec x, table cur_node)
This function computes the continuous dynamics of the dynmical system.
Parameters
t the time instant
x the system states
cur_node the current node being calculated Return values:
dx the first order derivatives
Required fields of cur_node:
Generated fields of extra:
Definition at line 18 of file calcDynamics.m.
Referenced by HybridSystem(), and simulate().
function [ value , isterminal , direction ] = HybridSystem.checkGuard (double t, colvec x, cur_node, table assoc_edges)
Detect the guard condition (event trigger)
Parameters
t the absolute time
x the system states
assoc_edges a table of transition edges from the current domain
cur_domain the current domain
Required fields of cur_node:
Required fields of assoc_edges:
Required fields of x:
Definition at line 18 of file checkGuard.m.
Referenced by HybridSystem(), and simulate().
function obj = HybridSystem.rmEdge (varargin)
Removes a edge or a group of edges from the directed graph object 'Gamma'.
Note
We only accept char or cellstr type of argument. We do not support scalar, vector, or matrix type of arguments that the 'rmnode' function usually supports. This is for unexpected behaviors to be occured.
See also
digraph, rmnode
Parameters
s the source vertices
t the target vertices
Generated fields of obj:
Definition at line 18 of file rmEdge.m.
Referenced by HybridSystem().
function obj = HybridSystem.rmVertex (vertex_name)
Removes a vertex or a group of vertices from the directed graph object 'Gamma'.
Note
We only accept char or cellstr type of argument. We do not support scalar, vector, or matrix type of arguments that the 'rmnode' function usually supports. This is for unexpected behaviors to be occured.
See also
digraph, rmnode
Parameters
vname the vertex name
Generated fields of obj:
Definition at line 18 of file rmVertex.m.
Referenced by HybridSystem().
function obj = HybridSystem.setEdgeProperties (s, t, varargin)
Sets the values of edge properties.
Note
A struct can be used to replace the (PropName, PropValue) inputs. To be valid input, the structure must have fields with the same name as vertex properties. For mutilple nodes, use the array of structures instead of the structure of arrays. Invalid fields in the structure will be ignored, and missing properties will be added with their default values.
Parameters
varargin
Definition at line 18 of file setEdgeProperties.m.
References implode().
Referenced by HybridSystem().
function obj = HybridSystem.setVertexProperties (cellstr vertex, varargin)
Sets the values of vertex properties.
Note
A struct can be used to replace the (PropName, PropValue) inputs. To be valid input, the structure must have fields with the same name as vertex properties. For mutilple nodes, use the array of structures instead of the structure of arrays. Invalid fields in the structure will be ignored, and missing properties will be added with their default values.
Parameters
vertex the names of the vertices to be configured. It must be a cell string or a character array.
varargin
Definition at line 18 of file setVertexProperties.m.
References implode().
Referenced by HybridSystem().
function obj = HybridSystem.simulate (struct options)
Simulate the hybrid dynamical system.
Parameters
options simulation options of hybrid system
Required fields of options:
Optional fields of options:
subgraph — the node list of the subgraph to be simulated
start — the first domain from which the simulation starts, the first domain in the graph if not explicitly specified
terminal — the last domain at which the simulation terminates, empty if not explicitly specified
numcycle — the number of cycle if the simulated system is periodic, 1 if not specified
x0 — the initial states of the system, zero if not specified
Generated fields of obj:
Definition at line 18 of file simulate.m.
References calcDynamics(), checkGuard(), and even_sample().
Referenced by HybridSystem().
Member Data Documentation
HybridSystem.EdgeProperties
A structure describes the name, type, attributes, and default value of each properties of the edge.
Note
This property has the MATLAB attribute Hidden set to true.
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 125 of file HybridSystem.m.
HybridSystem.Flow
The hybrid flows (trajectory) recorder.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 89 of file HybridSystem.m.
HybridSystem.Gamma
The directed graph that describes the hybrid dynamical system structure.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 64 of file HybridSystem.m.
HybridSystem.Model
The rigid body model of the hybrid system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 77 of file HybridSystem.m.
Referenced by HybridTrajectoryOptimization.HybridTrajectoryOptimization().
HybridSystem.Name
This is the name of the object that gives the object an universal identification.
Default: '
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 51 of file HybridSystem.m.
HybridSystem.VertexProperties
A structure describes the name, type, attributes, and default value of each properties of the vertex.
Note
This property has the MATLAB attribute Hidden set to true.
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 111 of file HybridSystem.m.
The documentation for this class was generated from the following files:
system/@HybridSystem/HybridSystem.m
system/@HybridSystem/addEdge.m
system/@HybridSystem/addVertex.m
system/@HybridSystem/calcDynamics.m
system/@HybridSystem/checkGuard.m
system/@HybridSystem/rmEdge.m
system/@HybridSystem/rmVertex.m
system/@HybridSystem/setEdgeProperties.m
system/@HybridSystem/setVertexProperties.m
system/@HybridSystem/simulate.m