FROST: DynamicalSystem Class Reference
DynamicalSystem Class Reference
A superclass for continuous/discrete dynamic systems.
Public Member Functions
function obj = addState (varargin)
Add state variables of the dynamical system.
function obj = addInput (category, name, var, gf, varargin)
Add input variables of the dynamical system.
function obj = removeInput (category, name)
Remove input variables of the dynamical system.
function obj = addParam (varargin)
Add parameter variables of the dynamical system.
function obj = removeParam (param_name)
Remove parameter variables of the dynamical system.
function obj = setParamValue (varargin)
set the actual value of the system parameters
function obj = compile (export_path, varargin)
export the symbolic expressions of the system dynamics matrices and vectors and compile as MEX files.
DynamicalSystem (char type,char name)
The class construction function.
function obj = setName (name)
set the name of the dynamical system
function var_group = validateVarName (char name)
Adds unilateral (inequality) constraints on the dynamical system states and inputs.
function obj = setType (char type)
Sets the type of the dynamical system.
Public Attributes
char Name
The unique name identification of the system.
function_handle ExternalOutputFun
Returns the external input defined on the dynamical system.
char Type
The highest order of the state derivatives of the system.
struct States
A structure that contains the symbolic representation of state variables.
double numState
The total number of system states.
struct Inputs
A structure that contains the symbolic representation of input variables.
struct Params
The parameters of the system.
struct Gvec
The struct of input vector fields Gvec(x,u) SymFunction.
struct Gmap
The struct of input map Gmap(x) SymFunction.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Protected Member Functions
function value = getValue (vars)
returns the variables (vars) value that are stored during computing the dynamics
function v_type = validateSystemType (type)
validate if it is valid system type
Protected Attributes
double t_
The time.
struct states_
The states.
struct inputs_
The inputs.
struct params_
The parameters.
struct GmapName_
The name of the Gmap functions.
struct GvecName_
The name of the Gvec functions.
Detailed Description
A superclass for continuous/discrete dynamic systems.
Author
ayonga
Date
2017-02-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Note
This class has the class property Abstract and needs to be inherited in order to be instantiable.
Definition at line 17 of file DynamicalSystem.m.
Constructor & Destructor Documentation
DynamicalSystem.DynamicalSystem (char type, char name)
The class construction function.
Parameters
type the type of the system
name the name of the system
Definition at line 197 of file DynamicalSystem.m.
Referenced by DiscreteDynamics.addState(), ContinuousDynamics.addState(), ContinuousDynamics.compile(), ContinuousDynamics.ContinuousDynamics(), and DiscreteDynamics.DiscreteDynamics().
Member Function Documentation
function obj = DynamicalSystem.addInput (category, name, var, gf, varargin)
Add input variables of the dynamical system.
Note
By default, we assume the input is affine.
Parameters
category the category of the input
name the name of the inputs
var the symbolic variables or a list or number of input signals of the inputs
gf the input map g(x) or g(x,u)
varargin optional argument indicating whether the input is affine
addInput (...,  [ "Affine", Affine_value ])
Named Parameters for varargin:
Affine Affine (Default: true)
Definition at line 18 of file addInput.m.
References handle.fieldnames, and handle.transpose.
Referenced by ContinuousDynamics.addHolonomicConstraint(), and RigidImpact.addImpactConstraint().
function obj = DynamicalSystem.addParam (varargin)
Add parameter variables of the dynamical system.
Parameters
varargin the name-value pairs (or struct) of the system parameters
Definition at line 18 of file addParam.m.
References handle.fieldnames.
Referenced by ContinuousDynamics.addHolonomicConstraint(), and ContinuousDynamics.addVirtualConstraint().
function obj = DynamicalSystem.addState (varargin)
Add state variables of the dynamical system.
Parameters
varargin the name-value pairs (or struct) of the system parameters
Generated fields of obj:
Definition at line 18 of file addState.m.
References handle.fieldnames.
function obj = DynamicalSystem.compile (export_path, varargin)
export the symbolic expressions of the system dynamics matrices and vectors and compile as MEX files.
Parameters
export_path the path to export the file
varargin variable input parameters
compile (..., StackVariable, File, ForceExport, BuildMex, Namespace)
Required Parameters for varargin:
StackVariable whether to stack variables into one
File the (full) file name of exported file
ForceExport force the export
BuildMex flag whether to MEX the exported file
Namespace the namespace of the function
Definition at line 18 of file compile.m.
References handle.fieldnames.
function value = DynamicalSystem.getValue (vars) protected
returns the variables (vars) value that are stored during computing the dynamics
Definition at line 312 of file DynamicalSystem.m.
Referenced by ContinuousDynamics.checkGuard().
function obj = DynamicalSystem.removeInput (category, name)
Remove input variables of the dynamical system.
Parameters
category the category of the input
name the name of the input variables to be removed
Definition at line 18 of file removeInput.m.
Referenced by ContinuousDynamics.removeHolonomicConstraint(), and RigidImpact.removeImpactConstraint().
function obj = DynamicalSystem.removeParam (param_name)
Remove parameter variables of the dynamical system.
Parameters
param_name the name of the parameter variables to be removed
Generated fields of obj:
Definition at line 18 of file removeParam.m.
Referenced by ContinuousDynamics.removeHolonomicConstraint(), and ContinuousDynamics.removeVirtualConstraint().
function obj = DynamicalSystem.setName (name)
set the name of the dynamical system
Generated fields of obj:
Definition at line 242 of file DynamicalSystem.m.
function obj = DynamicalSystem.setParamValue (varargin)
set the actual value of the system parameters
Parameters
varargin the parameter values
Definition at line 18 of file setParamValue.m.
References handle.fieldnames.
function obj = DynamicalSystem.setType (char type)
Sets the type of the dynamical system.
Parameters
type the system type
Generated fields of obj:
Definition at line 292 of file DynamicalSystem.m.
function v_type = DynamicalSystem.validateSystemType (type) protected
validate if it is valid system type
Definition at line 341 of file DynamicalSystem.m.
function var_group = DynamicalSystem.validateVarName (char name)
Adds unilateral (inequality) constraints on the dynamical system states and inputs.
Parameters
name the name string of the variable
Definition at line 259 of file DynamicalSystem.m.
Referenced by UnilateralConstraint.UnilateralConstraint().
Member Data Documentation
DynamicalSystem.ExternalOutputFun
Returns the external input defined on the dynamical system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 60 of file DynamicalSystem.m.
DynamicalSystem.Gmap
The struct of input map Gmap(x) SymFunction.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 161 of file DynamicalSystem.m.
DynamicalSystem.GmapName_ protected
The name of the Gmap functions.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 408 of file DynamicalSystem.m.
DynamicalSystem.Gvec
The struct of input vector fields Gvec(x,u) SymFunction.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 149 of file DynamicalSystem.m.
Referenced by RigidImpact.rigidImpactConstraint().
DynamicalSystem.GvecName_ protected
The name of the Gvec functions.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 420 of file DynamicalSystem.m.
DynamicalSystem.Inputs
A structure that contains the symbolic representation of input variables.
We categorized input signals into three different groups: Control: the control input ConstraintWrench: the constrained wrench from any bilateral (holonomic or nonholonomic) constraints External: other external inputs, such as disturbance, etc.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 117 of file DynamicalSystem.m.
DynamicalSystem.inputs_ protected
The inputs.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 383 of file DynamicalSystem.m.
DynamicalSystem.Name
The unique name identification of the system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 43 of file DynamicalSystem.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint(), RobotLinks.configure(), RobotLinks.configureKinematics(), and UnilateralConstraint.UnilateralConstraint().
DynamicalSystem.numState
The total number of system states.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 105 of file DynamicalSystem.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint().
DynamicalSystem.Params
The parameters of the system.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 136 of file DynamicalSystem.m.
DynamicalSystem.params_ protected
The parameters.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 395 of file DynamicalSystem.m.
DynamicalSystem.States
A structure that contains the symbolic representation of state variables.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 92 of file DynamicalSystem.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint(), and HolonomicConstraint.HolonomicConstraint().
DynamicalSystem.states_ protected
The states.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 371 of file DynamicalSystem.m.
DynamicalSystem.t_ protected
The time.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 359 of file DynamicalSystem.m.
DynamicalSystem.Type
The highest order of the state derivatives of the system.
Note
The system could be either a FirstOrder system or a SecondOrder system.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 75 of file DynamicalSystem.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint(), and RobotLinks.configure().
The documentation for this class was generated from the following files:
system/@DynamicalSystem/DynamicalSystem.m
system/@DynamicalSystem/addInput.m
system/@DynamicalSystem/addParam.m
system/@DynamicalSystem/addState.m
system/@DynamicalSystem/compile.m
system/@DynamicalSystem/removeInput.m
system/@DynamicalSystem/removeParam.m
system/@DynamicalSystem/setParamValue.m