FROST: RigidJoint Class Reference
RigidJoint Class Reference
A coordinate frame that is rigidly attached to the origin a rigid joint and the child link of the joint. In addition, this class stores the type, rotation axis, child link, and limit of the rigid joints.
Public Member Functions
RigidJoint (varargin)
The class constructor function.
function obj = setAxis (rowvec axis)
set the joint rotation axis vector in the joint coordinate
function obj = setType (char type)
Sets the joint type.
function obj = setParent (char parent)
set the parent link frame
function obj = setChild (char child)
set the child link frame
function obj = setLimit (struct limit)
set the physical limits of the rigid joints
function obj = setChainIndices (rowvec indices)
Set the kinematic chain indices of the parent reference frames.
function xi = getTwist ()
returns the twist vector of the rigid joint
function obj = computeTwist ()
computes the twist from the base frame
function obj = setTwistPairs (RigitJoint dofs,SymVariable q)
set the twist paris of all precedent joints
Public Member Functions inherited from CoordinateFrame
CoordinateFrame (varargin)
The class constructor function.
function obj = ToContactFrame (char type)
convert a coordinate frame into a contact frame
function obj = setReference (CoordinateFrame ref)
set the reference frame
function obj = setOffset (rowvec offset)
set the offset of the origin of the frame from the reference frame origin (in the reference frame)
function obj = setRotationMatrix (rowvec|matrix r)
set the rotation matrix (R) of the frame w.r.t to the reference frame
function obj = computeHomogeneousTransform ()
computes the homogeneous transformation matrix from the world coordinates
function pos = computeCartesianPosition (rowvec p)
computes the cartesian position of a point p in the body (current) coordinate frame
function rpy = computeEulerAngle ()
computes the Euler angles the body (current) coordinate frame in the world frame (base coordinate)
function g = computeForwardKinematics ()
computes the forward kinematics transformation matrix of the coordinate frame
function Jac = computeBodyJacobian (integer nDof)
computes the body Jacobian matrix of the coordinate frame
function Jac = computeSpatialJacobian (integer nDof)
computes the spatial Jacobian matrix of the coordinate frame
function c_str = getTwists (matrix p)
Returns the symbolic representation of the body jacobians of coordinate frames.
Public Attributes
char Type
The type of the rigid joint.
rowvec Axis
The rotation axis vector of the rigid joint.
char Child
The name of the child link.
char Parent
The name of the parent link.
struct Limit
A structure data stores the physical limits of the rigid joints.
rowvec ChainIndices
The indices of kinematic chains from the base to the current joint.
rowvec Twist
The twist from the base frame.
SymExpression TwistPairs
The twist pairs of all precedent joints (coordinate frame)
Public Attributes inherited from CoordinateFrame
char Name
The name of the coordinate frame.
CoordinateFrame Reference
The parent reference coordinate frame.
rowvec Offset
The offset of the origin of the frame from the origin of the reference frame.
matrix R
The rotation matrix of the frame w.r.t. the reference frame.
matrix gst0
The homogeneous transformation from the base coordinate.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Additional Inherited Members
Static Public Member Functions inherited from CoordinateFrame
static function gst = RPToHomogeneous (R, p)
Convert a rotation + translation to a homogeneous matrix.
static function adj = RigidAdjoint (g)
rigid adjoint matrix from the homonegeous matrix
static function R = RigidOrientation (g)
extract the rigid orientation from the homogeneous transformation matrix
static function p = RigidPosition (g)
extract the rigid position from the homogeneous transformation matrix
static function s = AxisToSkew (p)
converts the axis vector to a skew matrix
Detailed Description
A coordinate frame that is rigidly attached to the origin a rigid joint and the child link of the joint. In addition, this class stores the type, rotation axis, child link, and limit of the rigid joints.
Copyright (c) 2016-2017, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file RigidJoint.m.
Constructor & Destructor Documentation
RigidJoint.RigidJoint (varargin)
The class constructor function.
Parameters
varargin variable nama-value pair input arguments, in detail:
RigidJoint (Name, Reference, Offset, R, Axis, Type, Child, Limit)
Required Parameters for varargin:
Name the name of the frame
Reference the reference frame
Offset the offset of the origin
R the rotation matrix or the Euler angles
Axis the rotation axis vector
Type the type of the joints
Child the child link frame
Limit the joint physical limits
Required fields of limit:
effort — the maximum actuator effort
lower — the minimum allowable displacement
upper — the maximum allowable displacement
velocity — the maximum allowable velocity
Definition at line 149 of file RigidJoint.m.
References computeTwist(), CoordinateFrame.CoordinateFrame(), getTwist(), setAxis(), setChainIndices(), setChild(), setLimit(), setParent(), setTwistPairs(), and setType().
Member Function Documentation
function obj = RigidJoint.computeTwist ()
computes the twist from the base frame
Generated fields of obj:
Definition at line 18 of file computeTwist.m.
References CoordinateFrame.RigidAdjoint(), and handle.transpose.
Referenced by RigidJoint(), and setTwistPairs().
function xi = RigidJoint.getTwist ()
returns the twist vector of the rigid joint
Definition at line 18 of file getTwist.m.
Referenced by RigidJoint().
function obj = RigidJoint.setAxis (rowvec axis)
set the joint rotation axis vector in the joint coordinate
Parameters
axis the axis vector
Generated fields of obj:
Definition at line 18 of file setAxis.m.
Referenced by RigidJoint().
function obj = RigidJoint.setChainIndices (rowvec indices)
Set the kinematic chain indices of the parent reference frames.
Parameters
indices the index vector
Generated fields of obj:
Definition at line 18 of file setChainIndices.m.
References handle.transpose.
Referenced by RigidJoint().
function obj = RigidJoint.setChild (char child)
set the child link frame
Parameters
child the child link frame object
Generated fields of obj:
Definition at line 18 of file setChild.m.
Referenced by RigidJoint().
function obj = RigidJoint.setLimit (struct limit)
set the physical limits of the rigid joints
Parameters
limit the physical limit
Generated fields of obj:
Definition at line 18 of file setLimit.m.
References implode().
Referenced by RigidJoint().
function obj = RigidJoint.setParent (char parent)
set the parent link frame
Parameters
parent the parent link frame object
Generated fields of obj:
Definition at line 18 of file setParent.m.
Referenced by RigidJoint().
function obj = RigidJoint.setTwistPairs (RigitJoint dofs, SymVariable q)
set the twist paris of all precedent joints
Parameters
dofs the array of rigid joints
q the symbolic variabls of rigid joints
Generated fields of obj:
Definition at line 18 of file setTwistPairs.m.
References computeTwist(), and mat2math().
Referenced by RigidJoint().
function obj = RigidJoint.setType (char type)
Sets the joint type.
Parameters
type the joint type
Generated fields of obj:
Definition at line 18 of file setType.m.
Referenced by RigidJoint().
Member Data Documentation
RigidJoint.Axis
The rotation axis vector of the rigid joint.
Note
it must be a 3x1 vector.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 53 of file RigidJoint.m.
RigidJoint.ChainIndices
The indices of kinematic chains from the base to the current joint.
Note
This property has the MATLAB attribute Hidden set to true.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 107 of file RigidJoint.m.
RigidJoint.Child
The name of the child link.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 67 of file RigidJoint.m.
RigidJoint.Limit
A structure data stores the physical limits of the rigid joints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 91 of file RigidJoint.m.
RigidJoint.Parent
The name of the parent link.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 79 of file RigidJoint.m.
RigidJoint.Twist
The twist from the base frame.
Note
This property has the MATLAB attribute Hidden set to true.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 121 of file RigidJoint.m.
RigidJoint.TwistPairs
The twist pairs of all precedent joints (coordinate frame)
Note
This property has the MATLAB attribute Hidden set to true.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 134 of file RigidJoint.m.
RigidJoint.Type
The type of the rigid joint.
Note
valid joint types include: revolute, prismatic, continuous, fixed.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 38 of file RigidJoint.m.
The documentation for this class was generated from the following files:
robotics/@RigidJoint/RigidJoint.m
robotics/@RigidJoint/computeTwist.m
robotics/@RigidJoint/getTwist.m
robotics/@RigidJoint/setAxis.m
robotics/@RigidJoint/setChainIndices.m
robotics/@RigidJoint/setChild.m
robotics/@RigidJoint/setLimit.m
robotics/@RigidJoint/setParent.m
robotics/@RigidJoint/setTwistPairs.m
robotics/@RigidJoint/setType.m