AMBER Suite: IOFeedback Class Reference
IOFeedback Class Reference
This class defines the classic input-output feedback linearization controller.
Public Member Functions
IOFeedback (char name)
The controller class constructor function.
function obj = setParam (varargin)
Sets the controller parameters.
function [ u , extra ] = calcControl (double t,colvec qe,colvec dqe,colvec vfc,colvec gfc,Domain domain)
Computes the classical input-output feedback linearization control law for virtual constraints.
Public Member Functions inherited from Controller
Controller (char name)
The controller class constructor function.
virtual function [ u , extra ] = calcControl (qe, dqe, vfc, gfc, domain)
Additional Inherited Members
Public Attributes inherited from Controller
char Name
The name of the controller.
struct Param
The parameters of the controller.
Detailed Description
This class defines the classic input-output feedback linearization controller.
Author
ayonga
Date
2016-10-14
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file IOFeedback.m.
Constructor & Destructor Documentation
IOFeedback.IOFeedback (char name)
The controller class constructor function.
Parameters
name the controller name
Definition at line 45 of file IOFeedback.m.
References calcControl(), Controller.Controller(), and setParam().
Member Function Documentation
function [ colvec u , struct extra ] = IOFeedback.calcControl (double t, colvec qe, colvec dqe, colvec vfc, colvec gfc, Domain domain)
Computes the classical input-output feedback linearization control law for virtual constraints.
Parameters
t the time instant
qe the joint configuration
dqe the joint velocities
vfc the vector field f(x)
gfc the vector field g(x)
domain the continuous domain
Return values
u the computed torque
extra additional computed data
Generated fields of extra:
Definition at line 18 of file calcControl.m.
Referenced by IOFeedback().
function obj = IOFeedback.setParam (varargin) virtual
Sets the controller parameters.
Note
When using 'ep' as the control parameters, we use the following relationships for 'kp' and 'kd': \(kp = ep^2\), \(kd = 2*ep\).
Please do not specifiy 'ep' and ('kp','kd') at the same time. In this case, only 'ep' will be used.
Parameters
varargin name-value pairs of control parameters. Expected arguments are:
setParam (ep, kp, kd)
Required Parameters for varargin:
ep epsilon for human-inspired control
kp kp
kd kd
Generated fields of obj:
Implements Controller.
Definition at line 18 of file setParam.m.
Referenced by IOFeedback().
The documentation for this class was generated from the following files:
control/@IOFeedback/IOFeedback.m
control/@IOFeedback/calcControl.m
control/@IOFeedback/setParam.m