AMBER Suite: Domain Class Reference
Domain Class Reference
Domain defines an admissible continuous domain (or phase) in the hybrid system model. The admissibility conditions are determined by the kinematic constraints defined on the domain.
Public Member Functions
Domain (char name)
the calss constructor for Domain class
function obj = addContact (KinematicContact contacts)
Adds a contact constraint for the domain.
function obj = addHolonomicConstraint (Kinematic kins)
Adds holonomic kinematic constraints other than contact constraints to the domain.
function obj = addUnilateralConstraint (Kinematic kins)
Adds unilateral kinematic constraints other than contact constraints to the domain.
function obj = removeContact (contacts)
Removes holonomic kinematic constraints other than contact constraints from the domain.
function obj = removeHolonomicConstraint (Kinematic kins)
Removes holonomic kinematic constraints other than contact constraints from the domain.
function obj = removeUnilateralConstraint (Kinematic kins)
Removes unilateral kinematic constraints other than contact constraints from the domain.
function obj = setAcutation (RigidBodyModel model,cellstr actuated_joints)
Sets the actuation map for the current domain.
function obj = compile (RigidBodyModel model, varargin)
Compiles the symbolic expression of kinematic functions related to the domain in Mathematica.
function obj = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function Fe = calcConstraintForces (varargin)
Calculates the constraints forces exert on the kinematic constraints of the rigid body model.
function value = calcUnilateralCondition (cell cond,RigidBodyModel model,colvec qe,colvec dqe,colvec u)
Calculates the unilateral condition specified by 'cond'.
function [ vfc , gfc ] = calcVectorFields (RigidBodyModel model,colvec qe,colvec dqe,matrix De,colvec He)
Calculates the vector fields of the affine control system \(dot{x} = f(x) + g(x)*u\) for the constrained dynamics.
function x_post = updateStates (RigitBodyModel model, x_pre,struct delta)
Updates the system states using the reset map associated with the discontinuous transition to the current domain to get the initial states of the current domain.
Public Attributes
char Name
% basic properties This is the name of the object that gives the object an universal identification
KinematicGroup HolonomicConstr
% holonomic constraints A group of holonomic kinematic constraints
table UnilateralConstr
% unilateral constraints A table of all unilateral constraints
matrix ActuationMap
% actuation a map for robot actuation on the current domain
Detailed Description
Domain defines an admissible continuous domain (or phase) in the hybrid system model. The admissibility conditions are determined by the kinematic constraints defined on the domain.
Contraints are typically given as kinematic constraints, such as holonomic constraints and unilateral constraints, of the rigid body model.
Author
ayonga
Date
2016-09-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file Domain.m.
Constructor & Destructor Documentation
Domain.Domain (char name)
the calss constructor for Domain class
Parameters
name the name of the domain
Definition at line 120 of file Domain.m.
References addContact(), addHolonomicConstraint(), addUnilateralConstraint(), calcConstraintForces(), calcUnilateralCondition(), calcVectorFields(), compile(), export(), removeContact(), removeHolonomicConstraint(), removeUnilateralConstraint(), setAcutation(), and updateStates().
Referenced by VirtualConstrDomain.compile(), VirtualConstrDomain.export(), and VirtualConstrDomain.VirtualConstrDomain().
Member Function Documentation
function obj = Domain.addContact (KinematicContact contacts)
Adds a contact constraint for the domain.
Parameters
contacts a cell array of kinematic contacts
Generated fields of obj:
Definition at line 18 of file addContact.m.
References Kinematics.Name.
Referenced by Domain().
function obj = Domain.addHolonomicConstraint (Kinematic kins)
Adds holonomic kinematic constraints other than contact constraints to the domain.
Parameters
kins a cell array of kinematic constraints
Generated fields of obj:
Definition at line 18 of file addHolonomicConstraint.m.
Referenced by Domain().
function obj = Domain.addUnilateralConstraint (Kinematic kins)
Adds unilateral kinematic constraints other than contact constraints to the domain.
Parameters
kins a cell array of kinematic constraints
Generated fields of obj:
Definition at line 18 of file addUnilateralConstraint.m.
Referenced by Domain().
function colvec Fe = Domain.calcConstraintForces (varargin)
Calculates the constraints forces exert on the kinematic constraints of the rigid body model.
Use one of the following two syntax
Fe = calcConstraintForces(obj, model, qe, dqe, u) or Fe = calcConstraintForces(obj, model, qe, dqe, u, De, He) The latter option save time if the natural dynamics has been already computed and input as argumets.
Parameters
varargin variable input arguments. They could be
calcConstraintForces (model, qe, dqe, u, De, He)
Required Parameters for varargin:
model a rigid body model
qe the coordinate configuration \(q\)
dqe the coordinate velocity \(\dot{q}\)
u the control inputs \(u\)
De (optional) the inertia matrix of the rigid body model \(D(q)\)
He (optional) the corilios, gravity and internal force vector \(H(q,\dot{q})\)
Return values
Fe the external constraint forces \(Fe(q,\dot{q},u)\)
Definition at line 18 of file calcConstraintForces.m.
Referenced by calcUnilateralCondition(), and Domain().
function value = Domain.calcUnilateralCondition (cell cond, RigidBodyModel model, colvec qe, colvec dqe, colvec u)
Calculates the unilateral condition specified by 'cond'.
Use the syntax
Fe = calcConstraintForces(obj, cond, model, qe, dqe, u)
Parameters
cond the list of unilaternal constraints
model a rigid body model
qe the coordinate configuration \(q\)
dqe the coordinate velocity \(\dot{q}\)
u the control inputs \(u\)
Return values
value the value of the unilateral condition
Definition at line 18 of file calcUnilateralCondition.m.
References calcConstraintForces().
Referenced by Domain().
function [ colvec vfc , colvec gfc ] = Domain.calcVectorFields (RigidBodyModel model, colvec qe, colvec dqe, matrix De, colvec He)
Calculates the vector fields of the affine control system \(dot{x} = f(x) + g(x)*u\) for the constrained dynamics.
Use one of the following two syntax
[vfc, gfc] = calcVectorFields(obj, model, qe, dqe) or [vfc, gfc] = calcVectorFields(obj, model, qe, dqe, De, He) The latter option save time if the natural dynamics has been already computed and input as argumets.
Parameters
model a rigid body model
qe the coordinate configuration \(q\)
dqe the coordinate velocity \(\dot{q}\)
De (optional) the inertia matrix of the rigid body model \(D(q)\)
He (optional) the corilios, gravity and internal force vector \(H(q,\dot{q})\)
Return values
vfc the vector field \(f(x)\)
gfc the vector field \(g(x)\)
Definition at line 18 of file calcVectorFields.m.
Referenced by Domain().
function obj = Domain.compile (RigidBodyModel model, varargin)
Compiles the symbolic expression of kinematic functions related to the domain in Mathematica.
See also
Kinematics.compile
Definition at line 18 of file compile.m.
Referenced by Domain().
function logical status = Domain.export (char export_path, logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
Parameters
export_path the complete directory path where the compiled symbolic function will be exported to
do_build determine whether build the mex files. Default: true
Return values
status indicator of successful export/built process
Definition at line 18 of file export.m.
Referenced by Domain().
function obj = Domain.removeContact (contacts)
Removes holonomic kinematic constraints other than contact constraints from the domain.
Parameters
kins a cell array of kinematic objects or name string
Generated fields of obj:
Definition at line 18 of file removeContact.m.
Referenced by Domain().
function obj = Domain.removeHolonomicConstraint (Kinematic kins)
Removes holonomic kinematic constraints other than contact constraints from the domain.
Parameters
kins a cell array of kinematic objects or name string
Generated fields of obj:
Definition at line 18 of file removeHolonomicConstraint.m.
Referenced by Domain().
function obj = Domain.removeUnilateralConstraint (Kinematic kins)
Removes unilateral kinematic constraints other than contact constraints from the domain.
Parameters
kins a cell array of kinematic objects or name string
Definition at line 18 of file removeUnilateralConstraint.m.
Referenced by Domain().
function obj = Domain.setAcutation (RigidBodyModel model, cellstr actuated_joints)
Sets the actuation map for the current domain.
Todo:
better implementation ...
Parameters
model a rigid body model
actuated_joints a list of actuated joints
Required fields of model:
Generated fields of obj:
Definition at line 18 of file setAcutation.m.
References RigidBodyModel.nDof.
Referenced by Domain().
function x_post = Domain.updateStates (RigitBodyModel model, x_pre, struct delta)
Updates the system states using the reset map associated with the discontinuous transition to the current domain to get the initial states of the current domain.
Parameters
model the robot model
delta the reset map option
qe_pre pre-guard joint configuration
dqe_pre pre-guard velocities
Return values
qe_post post-guard joint configuration
dqe_post post-guard velocities
Required fields of model:
Required fields of delta:
Definition at line 18 of file updateStates.m.
Referenced by Domain().
Member Data Documentation
Domain.ActuationMap
% actuation a map for robot actuation on the current domain
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 98 of file Domain.m.
Domain.HolonomicConstr
% holonomic constraints A group of holonomic kinematic constraints
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 64 of file Domain.m.
Domain.Name
% basic properties This is the name of the object that gives the object an universal identification
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 47 of file Domain.m.
Domain.UnilateralConstr
% unilateral constraints A table of all unilateral constraints
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 78 of file Domain.m.
The documentation for this class was generated from the following files:
system/@Domain/Domain.m
system/@Domain/addContact.m
system/@Domain/addHolonomicConstraint.m
system/@Domain/addUnilateralConstraint.m
system/@Domain/calcConstraintForces.m
system/@Domain/calcUnilateralCondition.m
system/@Domain/calcVectorFields.m
system/@Domain/compile.m
system/@Domain/export.m
system/@Domain/removeContact.m
system/@Domain/removeHolonomicConstraint.m
system/@Domain/removeUnilateralConstraint.m
system/@Domain/setAcutation.m
system/@Domain/updateStates.m