FROST: Controller Class Reference
Controller Class Reference abstract
This abstract class defines interfaces to configuration and functionalities of different types of controllers.
Public Member Functions
Controller (char name)
The controller class constructor function.
virtual function obj = setParam (varargin)
virtual function [ u , extra ] = calcControl (qe, dqe, vfc, gfc, domain)
Public Attributes
char Name
The name of the controller.
struct Param
The parameters of the controller.
Detailed Description
This abstract class defines interfaces to configuration and functionalities of different types of controllers.
Author
ayonga
Date
2016-10-04
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file Controller.m.
Constructor & Destructor Documentation
Controller.Controller (char name)
The controller class constructor function.
Parameters
name the controller name
Definition at line 60 of file Controller.m.
References calcControl(), and setParam().
Referenced by CLFQP.CLFQP(), IOFeedback.IOFeedback(), JointPD.JointPD(), and OutputPD.OutputPD().
Member Function Documentation
virtual function [u , extra ] = Controller.calcControl (qe, dqe, vfc, gfc, domain) pure virtual
Referenced by Controller().
virtual function obj = Controller.setParam (varargin) pure virtual
Implemented in IOFeedback, JointPD, and OutputPD.
Referenced by Controller().
Member Data Documentation
Controller.Name
The name of the controller.
Definition at line 37 of file Controller.m.
Controller.Param
The parameters of the controller.
Definition at line 46 of file Controller.m.
The documentation for this class was generated from the following file:
control/Controller.m