AMBER Suite: Kinematics Class Reference
Kinematics Class Reference
Defines a kinematic function of a rigid body model.
Public Member Functions
Kinematics (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic function. By default, we assume the dimension of a kinematic function is 1, unless this method is overloaded by subclasses.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function print (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
Public Attributes
char Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
logical Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
char Prefix
A prefix for the function to be exported.
char Suffix
A suffix for the function to be exported.
struct Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
struct Funcs
File names of the kinematic functions.
Protected Member Functions
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
function cmd = getJacDotMathCommand ()
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Protected Attributes
logical LinearizeFlagChanged
A flag for whether the 'Linearize' option is changed.
Detailed Description
Defines a kinematic function of a rigid body model.
Author
ayonga
Date
2016-09-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Note
This class has the class property Abstract and needs to be inherited in order to be instantiable.
Definition at line 17 of file Kinematics.m.
Constructor & Destructor Documentation
Kinematics.Kinematics (varargin)
The constructor function.
See also
struct
Parameters
varargin it could be a struct has the same fields as this class or name-value pair arguments. The syntax would be similar to construct a struct in Matlab. Use either
kin = Kinematics('Prop1', Value1,'Prop2',Value2,...);
or
kin = Kinematics(KinStruct);
Definition at line 105 of file Kinematics.m.
Referenced by KinematicCom.KinematicCom(), KinematicContact.KinematicContact(), KinematicDof.KinematicDof(), KinematicExpr.KinematicExpr(), KinematicGroup.KinematicGroup(), and KinematicOrientation.KinematicOrientation().
Member Function Documentation
function status = Kinematics.compile (RigidBodyModel model, logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
Parameters
model the rigid body model
re_load re-evaluate the symbolic expression
Required fields of model:
Definition at line 18 of file compile.m.
References check_var_exist(), eval_math(), getJacDotMathCommand(), getJacMathCommand(), getKinMathCommand(), and RigidBodyModel.Name.
Referenced by getDimension().
function logical status = Kinematics.export (char export_path, logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
Parameters
export_path the complete directory path where the compiled symbolic function will be exported to
do_build determine whether build the mex files. Default: true
Return values
status indicator of successful export/built process
Definition at line 18 of file export.m.
References build_mex(), check_var_exist(), eval_math(), getDimension(), and str2mathstr().
Referenced by getDimension().
function dim = Kinematics.getDimension ()
Returns the dimension of the kinematic function. By default, we assume the dimension of a kinematic function is 1, unless this method is overloaded by subclasses.
Definition at line 163 of file Kinematics.m.
References compile(), export(), and print().
Referenced by export(), and KinematicExpr.KinematicExpr().
function cmd = Kinematics.getJacDotMathCommand () protected
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Definition at line 394 of file Kinematics.m.
Referenced by compile(), and KinematicExpr.compile().
function cmd = Kinematics.getJacMathCommand (model) protected
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
Definition at line 381 of file Kinematics.m.
Referenced by compile().
function cmd = Kinematics.getKinMathCommand (model) protected
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
There is no default command for any specific kinematic constraint. All subclasses must overload this function.
Definition at line 365 of file Kinematics.m.
Referenced by compile().
function Kinematics.print (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
Todo:
better implementation ...
Definition at line 18 of file print.m.
References check_var_exist().
Referenced by getDimension().
Member Data Documentation
Kinematics.Funcs
File names of the kinematic functions.
Each field of 'Funcs' specifies the name of a function that used for a certain computation of the domain.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 225 of file Kinematics.m.
Kinematics.Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
if symbol expressions alreay exist, re-compile them
Generated fields of obj:
Note
This property has custom functionality when its value is changed.
Definition at line 70 of file Kinematics.m.
Kinematics.LinearizeFlagChanged protected
A flag for whether the 'Linearize' option is changed.
Note
This property has the MATLAB attribute Hidden set to true.
Matlab documentation of property attributes.
Definition at line 193 of file Kinematics.m.
Kinematics.Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
It has to be an unique string so as to prevent potential naming conflicts in Mathematica. A valid name must begin with a letter, and must consists only of letters and numbers. So special characters, e.g. underscores, are not allowed.
The actual symbol variable in Mathematica uses the name string as a subscript, i.e., it assigns the symbolic expression of the kinematic constraint to a variable name h["name"] to prevent potential naming conflicts. Similarly, it uses Jh["name"] and dJh["name"] for the Jacobian and time derivative of the Jacobian. You could print the symbolic expressions in matlab by calling math(obj.symbol) or math_eval(obj.symbol)
See also
symbol, jac_symbol, jacdot_symbol
Note
This property has custom functionality when its value is changed.
Definition at line 43 of file Kinematics.m.
Referenced by Domain.addContact(), KinematicGroup.addKinematic(), and KinematicGroup.removeKinematic().
Kinematics.Prefix
A prefix for the function to be exported.
Default: h
Note
This property has custom functionality when its value is changed.
Definition at line 80 of file Kinematics.m.
Referenced by VirtualConstrDomain.setPhaseVariable().
Kinematics.Suffix
A suffix for the function to be exported.
Default: '
Note
This property has custom functionality when its value is changed.
Definition at line 89 of file Kinematics.m.
Kinematics.Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 211 of file Kinematics.m.
The documentation for this class was generated from the following files:
kinematics/@Kinematics/Kinematics.m
kinematics/@Kinematics/compile.m
kinematics/@Kinematics/export.m
kinematics/@Kinematics/print.m