AMBER Suite: KinematicPosition Class Reference
KinematicPosition Class Reference
Defines one of the three dimensional Cartesian positions of a fixed point on a rigid link.
Public Member Functions
KinematicPosition (varargin)
The constructor function.
Public Member Functions inherited from Kinematics
Kinematics (varargin)
The constructor function.
function status = compileExpression (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function printExpression (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
function obj = linearize (linearize)
Public Attributes
char ParentLink
The name of the rigid link on which the point is attached to.
rowvec Offset
The 3-dimensional offset of the point in the body joint coordinates that is rigidly attached to parent link.
char Axis
The (x,y,z)-axis index of the position.
Public Attributes inherited from Kinematics
integer Dimension
The dimension of the kinematic function.
char Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
logical Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
Protected Member Functions
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand ()
overload the Jacobian compilation command This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
Protected Member Functions inherited from Kinematics
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
function cmd = getJacDotMathCommand ()
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Protected Attributes
integer pIndex
The index of the axis.
Protected Attributes inherited from Kinematics
struct Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
logical LinearizeFlagChanged
A flag for whether the 'Linearize' option is changed.
Detailed Description
Defines one of the three dimensional Cartesian positions of a fixed point on a rigid link.
Author
ayonga
Date
2016-09-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file KinematicPosition.m.
Constructor & Destructor Documentation
KinematicPosition.KinematicPosition (varargin)
The constructor function.
See Also
struct
Parameters
varargin it could be a struct has the same fields as this class or name-value pair arguments. The syntax would be similar to construct a struct in Matlab. Use either
kin = Kinematics('Prop1', Value1,'Prop2',Value2,...);
or
kin = Kinematics(KinStruct);
See Also
Kinematics
Definition at line 75 of file KinematicPosition.m.
References implode(), and Kinematics.Kinematics().
Member Function Documentation
function cmd = KinematicPosition.getJacMathCommand () protected
overload the Jacobian compilation command This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
Definition at line 245 of file KinematicPosition.m.
References cell2tensor().
function cmd = KinematicPosition.getKinMathCommand (model) protected
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
Required fields of model:
Definition at line 218 of file KinematicPosition.m.
References cell2tensor().
Member Data Documentation
KinematicPosition.Axis
The (x,y,z)-axis index of the position.
Set function for 'Axis'.
Generated fields of obj:
Note
This property has custom functionality when its value is changed.
Definition at line 58 of file KinematicPosition.m.
KinematicPosition.Offset
The 3-dimensional offset of the point in the body joint coordinates that is rigidly attached to parent link.
Set function for 'Offset'.
Generated fields of obj:
Note
This property has custom functionality when its value is changed.
Definition at line 48 of file KinematicPosition.m.
KinematicPosition.ParentLink
The name of the rigid link on which the point is attached to.
Set function for 'ParentLink'.
Generated fields of obj:
Note
This property has custom functionality when its value is changed.
Definition at line 39 of file KinematicPosition.m.
KinematicPosition.pIndex protected
The index of the axis.
Get function of 'pIndex'.
Note
This property has the MATLAB attribute Hidden set to true.
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 184 of file KinematicPosition.m.
The documentation for this class was generated from the following file:
kinematics/KinematicPosition.m