FROST: VirtualConstraint Class Reference
VirtualConstraint Class Reference
VirtualConstraint: represents a group of virtual constraints of a dynamical systems.
Public Member Functions
VirtualConstraint (DynamicalSystem model, ya,SymExpression name, varargin)
The class constructor function.
function export (export_path, varargin)
export the symbolic expressions of the constraints matrices and vectors and compile as MEX files.
function configure (varargin)
compiles the derivatives and Jacobian of the actual/desired outputs functions
function varargout = calcActual (x, dx)
calculate the actual outputs
function varargout = calcDesired (t, x, dx, a, p)
calculate the desired outputs
function varargout = calcPhaseVariable (t, x, dx, p)
calculate the phase variable
function nlp = imposeNLPConstraint (nlp, ep, nzy)
impose virtual constraints as NLP constraints in the trajectory optimization problem nlp of the dynamical system
function obj = setOutputLabel (cellstr label)
OutputLabel sets the naming labels of outputs.
function obj = setPhaseType (char type)
PhaseType sets the type of the phase variable.
function obj = setDesiredType (char type,integer degree)
DesiredType sets the function type of the desired outputs.
function obj = setRelativeDegree (integer degree)
RelativeDegree sets the relative degree of the virtual constraints.
function obj = setHolonomic (logical type)
Holonomic sets the type of whether the virtual constraints are holonomic or nonholonomic.
function obj = setPhaseVariable (SymExpression tau,SymVariable p)
Phase variale sets the symbolic expression of the state-based timing phase variable.
function name = validateName (name)
Name.
Public Attributes
integer Dimension
The dimension of the virtual constraints.
SymVariable OutputParams
The symbolic representation of parameter sets of the desired outputs.
char Name
The name of the virtual constraints.
SymVariable PhaseParams
The symbolic representation of parameters of the phase variable.
char OutputLabel
The label of the virtual constraint.
char PhaseType
The type of the phase variable.
DesiredType
The type of the desired output function.
integer RelativeDegree
The relative degree of the output.
logical Holonomic
Indicates whether the virtual constraint is holonomic or nonholonomic constraints.
integer PolyDegree
The maximum degree of the polynomial function.
SymFunction ActualFuncs
The actual outputs.
SymFunction DesiredFuncs
The desired outputs.
SymFunction PhaseFuncs
The phase variable.
SymFunction OutputFuncs
The virtual constraints ya - yd functions.
SymExpression PhaseVariable
The phase variable.
SymExpression ActualOutput
The actual outputs.
SymExpression DesiredOutput
The desired outputs.
PhaseParamName
The name of the phase parameter variable.
char OutputParamName
The name of the output parameter variable.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Protected Attributes
DynamicalSystem Model
The dynamical system model.
SymExpression ya_
The actual outputs.
SymExpression yd_
The desired outputs.
SymExpression tau_
The phase variables.
Detailed Description
VirtualConstraint: represents a group of virtual constraints of a dynamical systems.
Author
ayonga
Date
2017-04-20
Copyright (c) 2016-2017, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file VirtualConstraint.m.
Constructor & Destructor Documentation
VirtualConstraint.VirtualConstraint (DynamicalSystem model, ya, SymExpression name, varargin)
The class constructor function.
Parameters
model the dynamical system model in which the virtual constraints are defined
ya the symbolic expression of the actual outputs
name the name of the virtual constraints
varargin optional parameters. In details
VirtualConstraint (..., DesiredType, PolyDegree, RelativeDegree, PhaseType, Holonomic, OutputLabel)
Required Parameters for varargin:
DesiredType
PolyDegree
RelativeDegree
PhaseType
Holonomic
OutputLabel
Definition at line 411 of file VirtualConstraint.m.
References calcActual(), calcDesired(), calcPhaseVariable(), configure(), eval_math_fun(), export(), imposeNLPConstraint(), str2mathstr(), and validateName().
Member Function Documentation
function varargout = VirtualConstraint.calcActual (x, dx)
calculate the actual outputs
Note
: the last Jacobian output is the Jacobian of the dNya with respoect to the states, which is [x] for a first order system and [x;dx] for a second order system.
Parameters
x the states
dx the first order derivatives
Return values
varargout variable outputs in the following order:
ya the actual output value
d1ya the first order derivative ...
dNya the N = RelativeDegree - 1 order derivative
JdNya the Jacobian of dNya w.r.t. to the states
Definition at line 18 of file calcActual.m.
References Name.
Referenced by VirtualConstraint().
function varargout = VirtualConstraint.calcDesired (t, x, dx, a, p)
calculate the desired outputs
Note
: the last Jacobian output is the Jacobian of the dNyd with respoect to the states, which is [x] for a first order system and [x;dx] for a second order system.
Parameters
t the time
x the states
dx the first order derivatives
a the parameters of the desired output
p the parameters of the phase variable
Return values
varargout variable outputs in the following order:
yd the actual output value
d1yd the first order derivative ...
dNyd the N = RelativeDegree - 1 order derivative
JdNyd the Jacobian of dNya w.r.t. to the states
Definition at line 18 of file calcDesired.m.
References Name.
Referenced by VirtualConstraint().
function varargout = VirtualConstraint.calcPhaseVariable (t, x, dx, p)
calculate the phase variable
Note
: the last Jacobian output is the Jacobian of the dNya with respoect to the states, which is [x] for a first order system and [x;dx] for a second order system.
Parameters
x the states
dx the first order derivatives
p the parameter set
Return values
varargout variable outputs in the following order:
tau the phase variable value
d1tau the first order derivative ...
dNtau the N = RelativeDegree - 1 order derivative
JdNtau the Jacobian of dNya w.r.t. to the states
Definition at line 18 of file calcPhaseVariable.m.
References Name.
Referenced by VirtualConstraint().
function obj = VirtualConstraint.configure (varargin)
compiles the derivatives and Jacobian of the actual/desired outputs functions
Generated fields of obj:
Definition at line 18 of file configure.m.
Referenced by VirtualConstraint().
function VirtualConstraint.export (export_path, varargin)
export the symbolic expressions of the constraints matrices and vectors and compile as MEX files.
Parameters
export_path the path to export the file
varargin variable input parameters
export (..., Vars, File, ForceExport, BuildMex, Namespace)
Required Parameters for varargin:
Vars a list of symbolic variables
File the (full) file name of exported file
ForceExport force the export
BuildMex flag whether to MEX the exported file
Namespace the namespace of the function
Definition at line 18 of file export.m.
Referenced by VirtualConstraint().
function TrajectoryOptimization nlp = VirtualConstraint.imposeNLPConstraint (nlp, ep, nzy)
impose virtual constraints as NLP constraints in the trajectory optimization problem nlp of the dynamical system
For each (vector) virtual constraints, we will enforce the following
constraints at the first node
{y, y', ..., y^N} % where N = RelativeDegree - 1
and this constraint
y^(N+1) + ep_N y^N + ... ep_1 y = 0 at all nodes.
Note
For example, ep = [kp, kd] for typical vector relative degree 2 holonomic virtual constraints.
For example, nzy = [0] for a relative degree 1 nonholonomic virtual constraint (velocity outputs) means we do not require y to be zero at the first node. Another example, nzy = [0,0] for a relative degree 2 virtual constraints, we do not require both y and y' to be zero at the first node, on the other hand, nzy = [1,0] for a relative degree 2 virtual constraints, we only enforce y being zero at the first node.
Parameters
nlp the trajectory optimization NLP
ep the coefficients of the derivatives
nzy the derivatives that does not requires to be zero at the first node
Required fields of nlp:
Definition at line 18 of file imposeNLPConstraint.m.
References TrajectoryOptimization.NumNode, NonlinearProgram.Options, and TrajectoryOptimization.OptVarTable.
Referenced by VirtualConstraint().
function obj = VirtualConstraint.setDesiredType (char type, integer degree)
DesiredType sets the function type of the desired outputs.
Parameters
type the function type
degree the degree of polynomials
Generated fields of obj:
Definition at line 638 of file VirtualConstraint.m.
function obj = VirtualConstraint.setHolonomic (logical type)
Holonomic sets the type of whether the virtual constraints are holonomic or nonholonomic.
Parameters
type true for holonomic, false for nonholonomic
Generated fields of obj:
Definition at line 696 of file VirtualConstraint.m.
function obj = VirtualConstraint.setOutputLabel (cellstr label)
OutputLabel sets the naming labels of outputs.
Parameters
label the cell array of labels
Generated fields of obj:
Definition at line 591 of file VirtualConstraint.m.
function obj = VirtualConstraint.setPhaseType (char type)
PhaseType sets the type of the phase variable.
Parameters
type type of the phase variable
Generated fields of obj:
Definition at line 617 of file VirtualConstraint.m.
function obj = VirtualConstraint.setPhaseVariable (SymExpression tau, SymVariable p)
Phase variale sets the symbolic expression of the state-based timing phase variable.
Parameters
tau the phase variable
p the parameters of tau
Generated fields of obj:
Definition at line 726 of file VirtualConstraint.m.
function obj = VirtualConstraint.setRelativeDegree (integer degree)
RelativeDegree sets the relative degree of the virtual constraints.
Parameters
degree relative degree of outputs
Generated fields of obj:
Definition at line 674 of file VirtualConstraint.m.
function name = VirtualConstraint.validateName (name)
Name.
Definition at line 759 of file VirtualConstraint.m.
Referenced by VirtualConstraint().
Member Data Documentation
VirtualConstraint.ActualFuncs
The actual outputs.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 185 of file VirtualConstraint.m.
VirtualConstraint.ActualOutput
The actual outputs.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 254 of file VirtualConstraint.m.
VirtualConstraint.DesiredFuncs
The desired outputs.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 198 of file VirtualConstraint.m.
VirtualConstraint.DesiredOutput
The desired outputs.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 267 of file VirtualConstraint.m.
VirtualConstraint.DesiredType
The type of the desired output function.
It could be one of the following functions
{Bezier,CWF,ECWF,MinJerk,Constant}
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 129 of file VirtualConstraint.m.
VirtualConstraint.Dimension
The dimension of the virtual constraints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 41 of file VirtualConstraint.m.
VirtualConstraint.Holonomic
Indicates whether the virtual constraint is holonomic or nonholonomic constraints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 157 of file VirtualConstraint.m.
VirtualConstraint.Model protected
The dynamical system model.
Definition at line 352 of file VirtualConstraint.m.
VirtualConstraint.Name
The name of the virtual constraints.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 73 of file VirtualConstraint.m.
Referenced by calcActual(), calcDesired(), and calcPhaseVariable().
VirtualConstraint.OutputFuncs
The virtual constraints ya - yd functions.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 224 of file VirtualConstraint.m.
VirtualConstraint.OutputLabel
The label of the virtual constraint.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 101 of file VirtualConstraint.m.
VirtualConstraint.OutputParamName
The name of the output parameter variable.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 292 of file VirtualConstraint.m.
VirtualConstraint.OutputParams
The symbolic representation of parameter sets of the desired outputs.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 55 of file VirtualConstraint.m.
VirtualConstraint.PhaseFuncs
The phase variable.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 211 of file VirtualConstraint.m.
VirtualConstraint.PhaseParamName
The name of the phase parameter variable.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 279 of file VirtualConstraint.m.
VirtualConstraint.PhaseParams
The symbolic representation of parameters of the phase variable.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 87 of file VirtualConstraint.m.
VirtualConstraint.PhaseType
The type of the phase variable.
It could be either StateBased or TimeBased
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 115 of file VirtualConstraint.m.
VirtualConstraint.PhaseVariable
The phase variable.
Note
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 241 of file VirtualConstraint.m.
VirtualConstraint.PolyDegree
The maximum degree of the polynomial function.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 172 of file VirtualConstraint.m.
VirtualConstraint.RelativeDegree
The relative degree of the output.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 144 of file VirtualConstraint.m.
VirtualConstraint.tau_ protected
The phase variables.
Definition at line 384 of file VirtualConstraint.m.
VirtualConstraint.ya_ protected
The actual outputs.
Definition at line 363 of file VirtualConstraint.m.
VirtualConstraint.yd_ protected
The desired outputs.
Definition at line 373 of file VirtualConstraint.m.
The documentation for this class was generated from the following files:
system/@VirtualConstraint/VirtualConstraint.m
system/@VirtualConstraint/calcActual.m
system/@VirtualConstraint/calcDesired.m
system/@VirtualConstraint/calcPhaseVariable.m
system/@VirtualConstraint/configure.m
system/@VirtualConstraint/export.m
system/@VirtualConstraint/imposeNLPConstraint.m