FROST: IpoptApplication Class Reference
IpoptApplication Class Reference
IpoptApplication defines an interface application class for IPOPT solvers.
Public Member Functions
IpoptApplication (NonlinearProgram nlp,struct new_opts)
The default constructor function.
function obj = initialize ()
This function initialize the specific NLP application based on the nonlinear programming problem (specified by nlp).
function [ sol , info ] = optimize (x0)
This function runs the solver's optimization routine for the NLP.
Public Member Functions inherited from SolverApplication
virtual function initialize (nlp)
An abstract method that initialize the solver to be ready to solve the given NLP problem.
SolverApplication ()
The default constructor function.
Public Attributes
struct Objective
A structure contains the information of objective functions.
struct Constraint
A sturcture contains the information of constraints.
NonlinearProgram Nlp
The nonlinear programming object.
Public Attributes inherited from SolverApplication
struct Options
A structure for NLP solver options.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Detailed Description
IpoptApplication defines an interface application class for IPOPT solvers.
Author
Ayonga Hereid
Date
2016-10-22
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file IpoptApplication.m.
Constructor & Destructor Documentation
IpoptApplication.IpoptApplication (NonlinearProgram nlp, struct new_opts)
The default constructor function.
Parameters
nlp the NLP problem object to be solved
new_opts the new solver options
Required fields of nlp:
Definition at line 75 of file IpoptApplication.m.
References initialize(), optimize(), NonlinearProgram.Options, SolverApplication.SolverApplication(), and struct_overlay().
Member Function Documentation
function obj = IpoptApplication.initialize ()
This function initialize the specific NLP application based on the nonlinear programming problem (specified by nlp).
The initialization including group different types of constraints, index objective functions and constraints arrays, etc.
See also
NonlinearProgram
Generated fields of obj:
Definition at line 18 of file initialize.m.
Referenced by IpoptApplication().
function [ sol , info ] = IpoptApplication.optimize (x0) virtual
This function runs the solver's optimization routine for the NLP.
Be sure the run the initialization procedure before run this function.
Implements SolverApplication.
Definition at line 18 of file optimize.m.
Referenced by IpoptApplication().
Member Data Documentation
IpoptApplication.Constraint
A sturcture contains the information of constraints.
Definition at line 51 of file IpoptApplication.m.
IpoptApplication.Nlp
The nonlinear programming object.
Definition at line 61 of file IpoptApplication.m.
IpoptApplication.Objective
A structure contains the information of objective functions.
Definition at line 42 of file IpoptApplication.m.
The documentation for this class was generated from the following files:
solver/@IpoptApplication/IpoptApplication.m
solver/@IpoptApplication/initialize.m
solver/@IpoptApplication/optimize.m