FROST: ContactFrame Class Reference
ContactFrame Class Reference
A mechanical contact coordinate frame of a robot.
Public Member Functions
ContactFrame (varargin)
The class constructor function.
function obj = setType (char type)
Sets the contact type.
function [ f_constr , label , auxdata ] = getFrictionCone (SymVariable f,struct fric_coef)
returns the symbolic expression of the friction cone constraints of the contact
function [ f_constr , label , auxdata ] = getZMPConstraint (SymVariable f,struct geometry)
returns the symbolic expression of the zero moment point constraints of the contact
Public Member Functions inherited from CoordinateFrame
CoordinateFrame (varargin)
The class constructor function.
function obj = ContactFrame (type)
convert a coordinate frame into a contact frame
function obj = setReference (CoordinateFrame ref)
set the reference frame
function obj = setOffset (rowvec offset)
set the offset of the origin of the frame from the reference frame origin (in the reference frame)
function obj = setRotationMatrix (rowvec|matrix r)
set the rotation matrix (R) of the frame w.r.t to the reference frame
function obj = computeHomogeneousTransform ()
computes the homogeneous transformation matrix from the world coordinates
function pos = computeCartesianPosition (rowvec p)
computes the cartesian position of a point p in the body (current) coordinate frame
function rpy = computeEulerAngle ()
computes the Euler angles the body (current) coordinate frame in the world frame (base coordinate)
function g = computeForwardKinematics ()
computes the forward kinematics transformation matrix of the coordinate frame
function Jac = computeBodyJacobian (integer nDof)
computes the body Jacobian matrix of the coordinate frame
function Jac = computeSpatialJacobian (integer nDof)
computes the spatial Jacobian matrix of the coordinate frame
Public Attributes
char Type
The contact type.
matrix WrenchBase
The wrench basis.
Public Attributes inherited from CoordinateFrame
char Name
The name of the coordinate frame.
CoordinateFrame Reference
The parent reference coordinate frame.
rowvec Offset
The offset of the origin of the frame from the origin of the reference frame.
matrix R
The rotation matrix of the frame w.r.t. the reference frame.
matrix gst0
The homogeneous transformation from the base coordinate.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Additional Inherited Members
Static Public Member Functions inherited from CoordinateFrame
static function gst = RPToHomogeneous (R, p)
Convert a rotation + translation to a homogeneous matrix.
static function adj = RigidAdjoint (g)
rigid adjoint matrix from the homonegeous matrix
static function R = RigidOrientation (g)
extract the rigid orientation from the homogeneous transformation matrix
static function p = RigidPosition (g)
extract the rigid position from the homogeneous transformation matrix
static function s = AxisToSkew (p)
converts the axis vector to a skew matrix
Detailed Description
A mechanical contact coordinate frame of a robot.
Note
We assume that the positive z axis of the coordinate frame is the normal axis of the contact.
We assume the line contact is along the y axis of the coordinate frame.
We use the terminology from Matt Mason's (CMU) lecture note. see
The following contact type is supported
PointContactWithFriction
PointContactWithoutFriction
LineContactWithFriction
LineContactWithoutFriction
PlanarContactWithFriction
PlanarContactWithoutFriction
Copyright (c) 2016-2017, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file ContactFrame.m.
Constructor & Destructor Documentation
ContactFrame.ContactFrame (varargin)
The class constructor function.
Parameters
varargin variable nama-value pair input arguments, in detail:
ContactFrame (Name, Reference, Offset, R, Type)
Required Parameters for varargin:
Name the name of the frame
Reference the reference frame
Offset the offset of the origin
R the rotation matrix or the Euler angles
Type the type of the contact
Definition at line 94 of file ContactFrame.m.
References CoordinateFrame.CoordinateFrame(), getFrictionCone(), getZMPConstraint(), and setType().
Member Function Documentation
function [ SymFunction f_constr , cellstr label , cell auxdata ] = ContactFrame.getFrictionCone (SymVariable f, struct fric_coef)
returns the symbolic expression of the friction cone constraints of the contact
Note
The friction cone constraints does not includes the ZMP/CWS constraints.
Parameters
f the SymVariable of the constraint wrenches
fric_coef the coefficient of friction.
Return values
f_constr symbolic function of the friction cone
label the label of the constraints
auxdata constant data used in the constraint function
Optional fields of fric_coef:
mu — the (static) coefficient of friction.
gamma — the coefficient of torsional friction
Definition at line 18 of file getFrictionCone.m.
Referenced by ContactFrame().
function [ SymFunction f_constr , cellstr label , cell auxdata ] = ContactFrame.getZMPConstraint (SymVariable f, struct geometry)
returns the symbolic expression of the zero moment point constraints of the contact
Note
For more detail, please refer to Eq. (28) and Fig. 3 in this article: Grizzle, J. W.; Chevallereau, C.; Sinnet, R. W. & Ames, A. D. Models, feedback control, and open problems of 3D bipedal robotic walking. Automatica, 2014, 50, 1955 - 1988
Parameters
f the SymVariable of the constraint wrenches
geometry the geometry constant of the contact
Return values
f_constr symbolic expression of the ZMP constraints
label the label of the constraints
auxdata constant data used in the constraint function
Optional fields of geometry:
la — the distance from the origin to the rolling edge along the negative y-axis
lb — the distance from the origin to the rolling edge along the positive y-axis
La — the distance from the origin to the rolling edge along the negative x-axis
Lb — the distance from the origin to the rolling edge along the positive x-axis
Definition at line 18 of file getZMPConstraint.m.
Referenced by ContactFrame().
function obj = ContactFrame.setType (char type)
Sets the contact type.
Parameters
type the contact type
Generated fields of obj:
Definition at line 18 of file setType.m.
Referenced by ContactFrame().
Member Data Documentation
ContactFrame.Type
The contact type.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 54 of file ContactFrame.m.
ContactFrame.WrenchBase
The wrench basis.
Note
For the formal definition of wrench basis, please refer to Chapter 5. of the "A Mathematical Introduction to Robotic Manipulation" by Murray et al.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 71 of file ContactFrame.m.
Referenced by RobotLinks.addContact().
The documentation for this class was generated from the following files:
robotics/@ContactFrame/ContactFrame.m
robotics/@ContactFrame/getFrictionCone.m
robotics/@ContactFrame/getZMPConstraint.m
robotics/@ContactFrame/setType.m