FROST: KinematicOrientation Class Reference
KinematicOrientation Class Reference
Defines three dimensional orientations of a body frame rigidly attached to a link, i.e., it belongs to SO(3).
Public Member Functions
KinematicOrientation (varargin)
The constructor function.
Public Member Functions inherited from Kinematics
Kinematics (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic function. By default, we assume the dimension of a kinematic function is 1, unless this method is overloaded by subclasses.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function print (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
Public Attributes
char ParentLink
The parent link name of the body frame.
char Axis
The (x,y,z)-axis of the rotation.
integer pIndex
The index of the axis.
Public Attributes inherited from Kinematics
char Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
logical Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
char Prefix
A prefix for the function to be exported.
char Suffix
A suffix for the function to be exported.
struct Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
struct Funcs
File names of the kinematic functions.
Protected Member Functions
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
overload the Jacobian compilation command This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
Protected Member Functions inherited from Kinematics
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
function cmd = getJacDotMathCommand ()
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Additional Inherited Members
Protected Attributes inherited from Kinematics
logical LinearizeFlagChanged
A flag for whether the 'Linearize' option is changed.
Detailed Description
Defines three dimensional orientations of a body frame rigidly attached to a link, i.e., it belongs to SO(3).
Author
Ayonga Hereid
Date
2016-09-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file KinematicOrientation.m.
Constructor & Destructor Documentation
KinematicOrientation.KinematicOrientation (varargin)
The constructor function.
See also
struct
Parameters
varargin it could be a struct has the same fields as this class or name-value pair arguments. The syntax would be similar to construct a struct in Matlab. Use either
kin = Kinematics('Prop1', Value1,'Prop2',Value2,...);
or
kin = Kinematics(KinStruct);
Definition at line 70 of file KinematicOrientation.m.
References Kinematics.Kinematics().
Member Function Documentation
function cmd = KinematicOrientation.getJacMathCommand (model) protected
overload the Jacobian compilation command This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
Required fields of model:
Definition at line 188 of file KinematicOrientation.m.
References cell2tensor().
function cmd = KinematicOrientation.getKinMathCommand (model) protected
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
Required fields of model:
Definition at line 164 of file KinematicOrientation.m.
References cell2tensor().
Member Data Documentation
KinematicOrientation.Axis
The (x,y,z)-axis of the rotation.
Note
This property has custom functionality when its value is changed.
Definition at line 48 of file KinematicOrientation.m.
KinematicOrientation.ParentLink
The parent link name of the body frame.
Note
This property has custom functionality when its value is changed.
Definition at line 39 of file KinematicOrientation.m.
KinematicOrientation.pIndex
The index of the axis.
Note
This property has the MATLAB attribute Hidden set to true.
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 107 of file KinematicOrientation.m.
The documentation for this class was generated from the following file:
kinematics/KinematicOrientation.m