FROST: KinematicContact Class Reference
KinematicContact Class Reference
Defines a kinematic contact constraint.
Public Member Functions
KinematicContact (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic contact constraints.
function [ names , constraints ] = getWrenchConstraint (model, varargin)
Returns all admissible conditions of contact wrenches.
Public Member Functions inherited from Kinematics
Kinematics (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic function. By default, we assume the dimension of a kinematic function is 1, unless this method is overloaded by subclasses.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function print (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
Public Attributes
char ParentLink
The name of the parent rigid link on which the contact point is attached to.
rowvec Offset
The 3-dimensional offset of the contact point in the body coordinate frame that is rigidly attached to parent link.
char NormalAxis
The normal axis of the contact given in the reference frame.
char TangentAxis
The tangent axis of the contact given in the reference frame for Line contact.
char ContactType
The contact type.
char ModelType
The rigid model type, either 'planar' or 'spatial'.
double Mu
The positive friction coefficient if the contact has friction.
cell Geometry
The geometry shape of the contact if it is a line or planar contact.
rowvec ConstrIndices
the indices of constrained degrees of freedom of the kinematic contact
double NormalAxisSign
The positive/negative sign of normal direction. In some cases, the positive direction of the normal axis represented in the body frame could points outward to the body. In these cases, the normal force will be always negative.
Public Attributes inherited from Kinematics
char Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
logical Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
char Prefix
A prefix for the function to be exported.
char Suffix
A suffix for the function to be exported.
struct Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
struct Funcs
File names of the kinematic functions.
Protected Member Functions
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the Jacobian of kinematic constraint.
Protected Member Functions inherited from Kinematics
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
function cmd = getJacDotMathCommand ()
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Additional Inherited Members
Protected Attributes inherited from Kinematics
logical LinearizeFlagChanged
A flag for whether the 'Linearize' option is changed.
Detailed Description
Defines a kinematic contact constraint.
Author
ayonga
Date
2016-09-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file KinematicContact.m.
Constructor & Destructor Documentation
KinematicContact.KinematicContact (varargin)
The constructor function.
See also
struct
Parameters
varargin it could be a struct has the same fields as this class or name-value pair arguments. The syntax would be similar to construct a struct in Matlab. Use either
kin = KinematicContact('Prop1', Value1,'Prop2',Value2,...);
or
kin = KinematicContact(KinStruct);
Definition at line 227 of file KinematicContact.m.
References Kinematics.Kinematics().
Member Function Documentation
function dim = KinematicContact.getDimension ()
Returns the dimension of the kinematic contact constraints.
Definition at line 286 of file KinematicContact.m.
function cmd = KinematicContact.getJacMathCommand (model) protected
This function returns he Mathematica command to compile the symbolic expression for the Jacobian of kinematic constraint.
Required fields of model:
Definition at line 333 of file KinematicContact.m.
References cell2tensor(), ConstrIndices, ContactType, Geometry, getWrenchConstraint(), implode(), mat2math(), ModelType, Mu, NormalAxis, Offset, ParentLink, and TangentAxis.
function cmd = KinematicContact.getKinMathCommand (model) protected
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
Required fields of model:
Definition at line 306 of file KinematicContact.m.
References cell2tensor(), and mat2math().
function [ cellstr names , constraints ] = KinematicContact.getWrenchConstraint (model, varargin)
Returns all admissible conditions of contact wrenches.
Todo:
This function not has been heavily tested yet. Plase use it after testing the particular cases you use.
Return values
names the name of admissible conditions
conditions the condition matrices
Definition at line 18 of file getWrenchConstraint.m.
Referenced by getJacMathCommand().
Member Data Documentation
KinematicContact.ConstrIndices
the indices of constrained degrees of freedom of the kinematic contact
Note
This property has the MATLAB attribute Hidden set to true.
This property has the MATLAB attribute Dependent set to true.
Matlab documentation of property attributes.
[readonly]
Definition at line 188 of file KinematicContact.m.
Referenced by getJacMathCommand().
KinematicContact.ContactType
The contact type.
We use the terminology from Matt Mason's (CMU) lecture note. see http://www.cs.rpi.edu/~trink/Courses/RobotManipulation/lectures/lecture11.pdf
The following contact type is supported
PointContactWithFriction
PointContactWithoutFriction
LineContactWithFriction
LineContactWithoutFriction
PlanarContactWithFriction
PlanarContactWithoutFriction
Note
This property has custom functionality when its value is changed.
Definition at line 116 of file KinematicContact.m.
Referenced by getJacMathCommand(), and Guard.setResetMap().
KinematicContact.Geometry
The geometry shape of the contact if it is a line or planar contact.
These numbers will be used to compute unilateral constraints of the contact wrenches. It consists of cell arrays with one string specifies the axis of which the contact moment is computed ,and one 1x2 vector specifies the distances to the rolling edges of that axis. The first number specifies the distance to the rolling edge for the positive moment and the second number specifies the distance to the rolling edge for the negative moment. For more detail, please refer to Eq. (28) and Fig. 3 in this article: Grizzle, J. W.; Chevallereau, C.; Sinnet, R. W. & Ames, A. D. Models, feedback control, and open problems of 3D bipedal robotic walking Automatica , 2014, 50, 1955 - 1988
Note
For a line contact, we assume the contact shape is a stick.
For a planar contact, we assume the contact shape is a rectangler.
This property has custom functionality when its value is changed.
Definition at line 156 of file KinematicContact.m.
Referenced by getJacMathCommand().
KinematicContact.ModelType
The rigid model type, either 'planar' or 'spatial'.
Default: spatial
Note
This property has custom functionality when its value is changed.
Definition at line 138 of file KinematicContact.m.
Referenced by getJacMathCommand(), and Guard.setResetMap().
KinematicContact.Mu
The positive friction coefficient if the contact has friction.
Note
This property has custom functionality when its value is changed.
Definition at line 147 of file KinematicContact.m.
Referenced by getJacMathCommand().
KinematicContact.NormalAxis
The normal axis of the contact given in the reference frame.
It must be along one of the (x,y,z) axes. If the actual normal axis is none of the three Cartesian axes, it would be better to change the body coordinate frame so that the normal axis is along the body coordinates axes.
Note
The normal axis should be the direction where the positive normal force acts on. For example, we the z-axis of the body coordinate of the ParentLink points outward to the body, then the NormalAxis should be -z axis.
This property has custom functionality when its value is changed.
Definition at line 79 of file KinematicContact.m.
Referenced by getJacMathCommand().
KinematicContact.NormalAxisSign
The positive/negative sign of normal direction. In some cases, the positive direction of the normal axis represented in the body frame could points outward to the body. In these cases, the normal force will be always negative.
Default: 1
Note
This property has the MATLAB attribute Hidden set to true.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 205 of file KinematicContact.m.
KinematicContact.Offset
The 3-dimensional offset of the contact point in the body coordinate frame that is rigidly attached to parent link.
Note
This property has custom functionality when its value is changed.
Definition at line 67 of file KinematicContact.m.
Referenced by getJacMathCommand().
KinematicContact.ParentLink
The name of the parent rigid link on which the contact point is attached to.
Note
This property has custom functionality when its value is changed.
Definition at line 57 of file KinematicContact.m.
Referenced by getJacMathCommand().
KinematicContact.TangentAxis
The tangent axis of the contact given in the reference frame for Line contact.
It must be along one of the (x,y,z) axes. If the actual normal axis is none of the three Cartesian axes, it would be better to change the body coordinate frame so that the normal axis is along the body coordinates axes.
Note
This property has custom functionality when its value is changed.
Definition at line 99 of file KinematicContact.m.
Referenced by getJacMathCommand().
The documentation for this class was generated from the following files:
kinematics/@KinematicContact/KinematicContact.m
kinematics/@KinematicContact/getWrenchConstraint.m