FROST: CLFQP Class Reference
CLFQP Class Reference
This class defines a class of Control Lyapunov Functions (CLFs) that use quadratic programming (QP)
Public Member Functions
CLFQP (char name)
The controller class constructor function.
function [ u , extra ] = calcControl (t, qe, dqe, vfc, gfc, domain)
Computes the classical input-output feedback linearization control law for virtual constraints.
Public Member Functions inherited from Controller
Controller (char name)
The controller class constructor function.
virtual function obj = setParam (varargin)
Additional Inherited Members
Public Attributes inherited from Controller
char Name
The name of the controller.
struct Param
The parameters of the controller.
Detailed Description
This class defines a class of Control Lyapunov Functions (CLFs) that use quadratic programming (QP)
Todo:
implement the CLF-QP controller
Author
ayonga
Date
2016-10-14
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file CLFQP.m.
Constructor & Destructor Documentation
CLFQP.CLFQP (char name)
The controller class constructor function.
Parameters
name the controller name
Definition at line 47 of file CLFQP.m.
References calcControl(), and Controller.Controller().
Member Function Documentation
function [ colvec u , struct extra ] = CLFQP.calcControl (t, qe, dqe, vfc, gfc, domain) virtual
Computes the classical input-output feedback linearization control law for virtual constraints.
Parameters
t the time instant
qe the joint configuration
dqe the joint velocities
vfc the vector field f(x)
gfc the vector field g(x)
domain the continuous domain
Return values
u the computed torque
extra additional computed data
Implements Controller.
Definition at line 18 of file calcTorques.m.
Referenced by CLFQP().
The documentation for this class was generated from the following files:
control/@CLFQP/CLFQP.m
control/@CLFQP/calcTorques.m