FROST: HybridTrajectoryOptimization Class Reference
HybridTrajectoryOptimization Class Reference
HybridTrajectoryOptimization defines a particular type of nonlinear programing problem — trajectory optimization problem for a hybrid dynamical system.
Public Member Functions
HybridTrajectoryOptimization (HybridSystem plant, varargin)
The constructor function.
function obj = initializeNLP (options)
Initializes the trajectory optimization problem.
function obj = addAuxilaryVariable (integer phase,rowvec nodes, varargin)
Adds auxilary defect variables (such as h or impF) as the NLP decision variables to the problem.
function obj = addControlVariable (integer phase)
Adds control variables as the NLP decision variables to the problem.
function obj = addGuardVariable (integer phase, lb, ub, x0)
Adds defect variables associated with discrete transition at the guard as the NLP decision variables to the problem. It includes the constant vector of holonomic constraints, instantaneous impact force, etc.
function obj = addParamVariable (integer phase, lb, ub, x0)
Adds virtual constraint parameters as the NLP decision variables to the problem.
function obj = addStateVariable (integer phase)
Adds state variables as the NLP decision variables to the problem.
function obj = addTimeVariable (integer phase,double lb,double ub,double x0)
Adds time as the NLP decision variables to the problem.
function obj = genericSymFunctions ()
This function creates symbolic functions for the hybrid trajectory optimization problem.
function obj = compileSymFunction (char field,char phase,char export_path)
This function compiles symbolic functions for the hybrid trajectory optimization problem.
function obj = addCollocationConstraint (phase)
Add direct collocation equations as a set of equality constraints % Parameters: phase: the index of the phase (domain) model: the rigid body model of the robot.
function obj = addDomainConstraint (integer phase)
Add generic domain-admissibility constraints.
function obj = addDynamicsConstraint (integer phase)
Add system dynamics equations as a set of equality constraints.
function obj = addJumpConstraint (integer phase)
Add generic switching surface constraints, including guard condition and reset map constraints.
function obj = addOutputConstraint (integer phase)
Add output dynamics associated with domain virtual constraints as a set of equality constraints.
function obj = addParamConstraint (integer phase)
Add parameter consistency constraints within the phase.
function obj = addAuxilaryConstraint (integer phase,rowvec nodes, deps, varargin)
Add auxilary user-defined constraints constraints.
function obj = addRunningCost (integer phase,SymFunction func)
Add a running cost to the problem.
function obj = addTerminalCost (integer phase,char name,struct func,cellstr deps,double nodes, auxdata)
Add a terminal cost to the problem.
function phase_idx = getPhaseIndex (phase)
Returns the index of a particular phase specified by input argument 'phase'.
function [ yc , cl , cu ] = checkConstraints (x)
Check the violation of the constraints.
function [ xc , lb , ub ] = checkVariables (x)
Check the violation of the constraints.
function [ calcs , params ] = exportSolution (colvec sol)
Analyzes the solution of the NLP problem.
Public Member Functions inherited from NonlinearProgram
NonlinearProgram (struct varargin)
The default class constructor function.
function obj = regVariable (varargin)
This method registers the information of an optimization variable.
function obj = update ()
Updates the NLP problems before load it to NLP solver.
function obj = regObjective (NlpFunction funcs)
This method registers the information of a NLP function as a cost function.
function obj = regConstraint (NlpFunction funcs)
This method registers the information of a NLP function as a constraint.
function [ nVar , lowerbound , upperbound ] = getVarInfo ()
The function returns the dimension, upper/lower limits of NLP variables.
function x0 = getInitialGuess (char method)
This function returns an initial guess for the NLP.
Public Attributes
struct Funcs
A structure of which each sub-field provides the interface to external functions for NLP constraints or cost function.
cell Phase
The discrete phases of the hybrid trajectory optimization.
RigidBodyModel Model
The rigid body model of interest.
digraph Gamma
The directed graph of the hybrid sytem model to be optimized.
Public Attributes inherited from NonlinearProgram
struct Options
The class option.
cell VariableArray
The cell array contains all information regarding NLP optimization variables.
cell CostArray
A cell array data stores objective functions.
cell ConstrArray
A cell array data stores all constraints functions.
Sol
The solution of the NLP problem.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Detailed Description
HybridTrajectoryOptimization defines a particular type of nonlinear programing problem — trajectory optimization problem for a hybrid dynamical system.
See also
NonlinearProgram, HybridSystem
Author
ayonga
Date
2016-10-26
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file HybridTrajectoryOptimization.m.
Constructor & Destructor Documentation
HybridTrajectoryOptimization.HybridTrajectoryOptimization (HybridSystem plant, varargin)
The constructor function.
Parameters
plant the hybrid system plant
varargin
Definition at line 119 of file HybridTrajectoryOptimization.m.
References addAuxilaryConstraint(), addAuxilaryVariable(), addCollocationConstraint(), addControlVariable(), addDomainConstraint(), addDynamicsConstraint(), addGuardVariable(), addJumpConstraint(), addOutputConstraint(), addParamConstraint(), addParamVariable(), addRunningCost(), addStateVariable(), addTerminalCost(), addTimeVariable(), checkConstraints(), checkVariables(), compileSymFunction(), exportSolution(), HybridSystem.Gamma, genericSymFunctions(), getPhaseIndex(), initializeNLP(), HybridSystem.Model, and NonlinearProgram.NonlinearProgram().
Member Function Documentation
function obj = HybridTrajectoryOptimization.addAuxilaryConstraint (integer phase, rowvec nodes, deps, varargin)
Add auxilary user-defined constraints constraints.
See also
NlpFunction
Note
The deps must have the same length as the nodes.
Parameters
phase the index of the phase (domain)
nodes the node list of the variable
varargin variable input arguments for property values non-empty NlpFunction other than the DepVariables
Definition at line 18 of file addAuxilaryConstraint.m.
References getPhaseIndex(), and implode().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addAuxilaryVariable (integer phase, rowvec nodes, varargin)
Adds auxilary defect variables (such as h or impF) as the NLP decision variables to the problem.
See also
NlpVariable
Parameters
phase the index of the phase (domain)
nodes the node list of the variable
varargin variable input arguments for property values non-empty NlpVariables This function updates the properties of the class object based on the input name-value pair arguments.
varargin variable nama-value pair input arguments, in detail:
updateProp (Dimension, lb, ub, x0)
Required Parameters for varargin:
Dimension dimension of the variable
lb lower limit
ub upper limit
x0 a typical value of the variable
Definition at line 18 of file addAuxilaryVariable.m.
References getPhaseIndex(), and implode().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addCollocationConstraint (phase)
Add direct collocation equations as a set of equality constraints % Parameters: phase: the index of the phase (domain) model: the rigid body model of the robot.
Todo:
implement pseudospectral method
Definition at line 18 of file addCollocationConstraint.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addControlVariable (integer phase)
Adds control variables as the NLP decision variables to the problem.
Parameters
phase the index of the phase (domain)
model the rigid body model of the robot
Definition at line 18 of file addControlVariable.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addDomainConstraint (integer phase)
Add generic domain-admissibility constraints.
Parameters
phase the index of the phase (domain)
Definition at line 18 of file addDomainConstraint.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addDynamicsConstraint (integer phase)
Add system dynamics equations as a set of equality constraints.
The full dynamics equations consist of two parts, the Euler-Langrangian dynamics of the rigid body model and the holonomic
constraints of the system
\begin{eqnarray*} D(q)*\ddot{q} + C(q,\dot{q}) + G(q) - Be*u - J^T(q)*Fe &= 0 \ J(q)*\ddot{q} + \dot{J}(q,\dot{q})*\dot{q} &= 0 \end{eqnarray*}
Parameters
phase the index of the phase (domain)
Definition at line 18 of file addDynamicsConstraint.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addGuardVariable (integer phase, lb, ub, x0)
Adds defect variables associated with discrete transition at the guard as the NLP decision variables to the problem. It includes the constant vector of holonomic constraints, instantaneous impact force, etc.
Parameters
phase the index of the phase (domain)
hbar_props properties of parameter 'hbar'
impf_props properties of parameter 'impF'
model the rigid body model of the robot
Required fields of hbar_props:
lb — the lower bound of the parameters
ub — the upper bound of the parameters
x0 — the typical initial value of the parameters
Required fields of impf_pros:
lb — the lower bound of the parameters
ub — the upper bound of the parameters
x0 — the typical initial value of the parameters
Definition at line 18 of file addGuardVariable.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addJumpConstraint (integer phase)
Add generic switching surface constraints, including guard condition and reset map constraints.
Parameters
phase the index of the phase (domain)
Definition at line 18 of file addJumpConstraint.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addOutputConstraint (integer phase)
Add output dynamics associated with domain virtual constraints as a set of equality constraints.
The output dynamics equations are enforced to determine the feedback control law via virtual constraints. In order to have hybrid zero dynamics, relative degree two outputs should have initial value of zeros at the first node.
\begin{eqnarray*} \dot{y}_1(q,\dot{q},\ddot{q},v,p) + \epsilon * y_1(q,\dot{q},v,p) &= 0\ \ddot{y}_2(q,\dot{q},\ddot{q},a,p) + 2*\epsilon * \dot{y}_2(q,\dot{q},a,p) + \epsilon^2 * y_2(q,a,p)&= 0 \end{eqnarray*}
Parameters
phase the index of the phase (domain)
Definition at line 18 of file addOutputConstraint.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addParamConstraint (integer phase)
Add parameter consistency constraints within the phase.
Parameters
phase the index of the phase (domain)
Definition at line 18 of file addParamConstraint.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addParamVariable (integer phase, lb, ub, x0)
Adds virtual constraint parameters as the NLP decision variables to the problem.
Parameters
phase the index of the phase (domain)
a_props properties of parameter 'a'
v_props properties of parameter 'v'
p_props properties of parameter 'v'
model the rigid body model of the robot
Required fields of a_props:
lb — the lower bound of the parameters
ub — the upper bound of the parameters
x0 — the typical initial value of the parameters
Required fields of v_props:
lb — the lower bound of the parameters
ub — the upper bound of the parameters
x0 — the typical initial value of the parameters
Required fields of p_props:
lb — the lower bound of the parameters
ub — the upper bound of the parameters
x0 — the typical initial value of the parameters
Definition at line 18 of file addParamVariable.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addRunningCost (integer phase, SymFunction func)
Add a running cost to the problem.
Todo:
complete the implementation for other schemes
Parameters
phase the index of the phase (domain)
func a symbolic function to be integrated
Required fields of func:
Definition at line 18 of file addRunningCost.m.
References SymFunction.DepSymbols, SymFunction.Description, SymFunction.Expression, NlpFunction.Funcs, getPhaseIndex(), SymFunction.Name, and SymFunction.PreCommands.
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addStateVariable (integer phase)
Adds state variables as the NLP decision variables to the problem.
Parameters
phase the index of the phase (domain)
Definition at line 18 of file addStateVariable.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addTerminalCost (integer phase, char name, struct func, cellstr deps, double nodes, auxdata)
Add a terminal cost to the problem.
Parameters
phase the index of the phase (domain)
name the name of the function
func a symbolic function to be integrated
deps a list of dependent variables
nodes indicates at which nodes (first or last) be defined
auxdata (optional) auxilary arguments
Definition at line 18 of file addTerminalCost.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.addTimeVariable (integer phase, double lb, double ub, double x0)
Adds time as the NLP decision variables to the problem.
Parameters
phase the index of the phase (domain)
lb the lower bound of the phase time
ub the upper bound of the phase time
x0 the typical initial value of the phase time
Definition at line 18 of file addTimeVariable.m.
References getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function [ yc , cl , cu ] = HybridTrajectoryOptimization.checkConstraints (x)
Check the violation of the constraints.
Definition at line 18 of file checkConstraints.m.
References Funcs.
Referenced by HybridTrajectoryOptimization().
function [ xc , lb , ub ] = HybridTrajectoryOptimization.checkVariables (x)
Check the violation of the constraints.
Definition at line 18 of file checkVariables.m.
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.compileSymFunction (char field, char phase, char export_path)
This function compiles symbolic functions for the hybrid trajectory optimization problem.
Parameters
field the field of symbolic function to be compiled
phase name or index of particular phases
export_path the directory to export compiled files
Definition at line 18 of file compileSymFunction.m.
References handle.fields, and getPhaseIndex().
Referenced by HybridTrajectoryOptimization().
function [ calcs , params ] = HybridTrajectoryOptimization.exportSolution (colvec sol)
Analyzes the solution of the NLP problem.
Parameters
sol The solution vector of the NLP problem
Definition at line 18 of file exportSolution.m.
References handle.reshape.
Referenced by HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.genericSymFunctions ()
This function creates symbolic functions for the hybrid trajectory optimization problem.
Note
This function will only creates mandatory constraints functions. To create user-defined constraints or cost function, it is suggested to write your own function for the purpose.
This function should be called first by the overloaded method in any inherited classed, if any.
Generated fields of obj:
Definition at line 18 of file genericSymFunctions.m.
References cell2tensor(), and mat2math().
Referenced by HybridTrajectoryOptimization().
function phase_idx = HybridTrajectoryOptimization.getPhaseIndex (phase)
Returns the index of a particular phase specified by input argument 'phase'.
Definition at line 18 of file getPhaseIndex.m.
Referenced by addAuxilaryConstraint(), addAuxilaryVariable(), addCollocationConstraint(), addControlVariable(), addDomainConstraint(), addDynamicsConstraint(), addGuardVariable(), addJumpConstraint(), addOutputConstraint(), addParamConstraint(), addParamVariable(), addRunningCost(), addStateVariable(), addTerminalCost(), addTimeVariable(), compileSymFunction(), and HybridTrajectoryOptimization().
function obj = HybridTrajectoryOptimization.initializeNLP (varargin)
Initializes the trajectory optimization problem.
Parameters
varargin namr-value pairs of optimization options
Optional fields of options:
GridCount — the number of grids of each domain
StartingVertex — the first domain from which the optimization StartingVertexs, the first domain in the graph if not explicitly specified
TerminalVertex — the last domain at which the optimization terminates, empty if not explicitly specified
Definition at line 18 of file initializeNLP.m.
Referenced by HybridTrajectoryOptimization().
Member Data Documentation
HybridTrajectoryOptimization.Funcs
A structure of which each sub-field provides the interface to external functions for NLP constraints or cost function.
Note
Typically, we will use SymFunction to construct such an object for a function. However, users could also employ other class or structure for their own custom functions. One requirement of such an object is that it must have a field called 'Funcs' to provides the external function name (or function handles).
To add a new function object, create a new field in this variable.
See also
SymFunction
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 46 of file HybridTrajectoryOptimization.m.
Referenced by checkConstraints().
HybridTrajectoryOptimization.Gamma
The directed graph of the hybrid sytem model to be optimized.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 96 of file HybridTrajectoryOptimization.m.
HybridTrajectoryOptimization.Model
The rigid body model of interest.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 84 of file HybridTrajectoryOptimization.m.
HybridTrajectoryOptimization.Phase
The discrete phases of the hybrid trajectory optimization.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 71 of file HybridTrajectoryOptimization.m.
The documentation for this class was generated from the following files:
nlp/@HybridTrajectoryOptimization/HybridTrajectoryOptimization.m
nlp/@HybridTrajectoryOptimization/addAuxilaryConstraint.m
nlp/@HybridTrajectoryOptimization/addAuxilaryVariable.m
nlp/@HybridTrajectoryOptimization/addCollocationConstraint.m
nlp/@HybridTrajectoryOptimization/addControlVariable.m
nlp/@HybridTrajectoryOptimization/addDomainConstraint.m
nlp/@HybridTrajectoryOptimization/addDynamicsConstraint.m
nlp/@HybridTrajectoryOptimization/addGuardVariable.m
nlp/@HybridTrajectoryOptimization/addJumpConstraint.m
nlp/@HybridTrajectoryOptimization/addOutputConstraint.m
nlp/@HybridTrajectoryOptimization/addParamConstraint.m
nlp/@HybridTrajectoryOptimization/addParamVariable.m
nlp/@HybridTrajectoryOptimization/addRunningCost.m
nlp/@HybridTrajectoryOptimization/addStateVariable.m
nlp/@HybridTrajectoryOptimization/addTerminalCost.m
nlp/@HybridTrajectoryOptimization/addTimeVariable.m
nlp/@HybridTrajectoryOptimization/checkConstraints.m
nlp/@HybridTrajectoryOptimization/checkVariables.m
nlp/@HybridTrajectoryOptimization/compileSymFunction.m
nlp/@HybridTrajectoryOptimization/exportSolution.m
nlp/@HybridTrajectoryOptimization/genericSymFunctions.m
nlp/@HybridTrajectoryOptimization/getPhaseIndex.m
nlp/@HybridTrajectoryOptimization/initializeNLP.m