FROST: CoordinateFrame Class Reference
CoordinateFrame Class Reference
A kinematic coordinate frame class.
Public Member Functions
CoordinateFrame (varargin)
The class constructor function.
function obj = ContactFrame (type)
convert a coordinate frame into a contact frame
function obj = setReference (CoordinateFrame ref)
set the reference frame
function obj = setOffset (rowvec offset)
set the offset of the origin of the frame from the reference frame origin (in the reference frame)
function obj = setRotationMatrix (rowvec|matrix r)
set the rotation matrix (R) of the frame w.r.t to the reference frame
function obj = computeHomogeneousTransform ()
computes the homogeneous transformation matrix from the world coordinates
function pos = computeCartesianPosition (rowvec p)
computes the cartesian position of a point p in the body (current) coordinate frame
function rpy = computeEulerAngle ()
computes the Euler angles the body (current) coordinate frame in the world frame (base coordinate)
function g = computeForwardKinematics ()
computes the forward kinematics transformation matrix of the coordinate frame
function Jac = computeBodyJacobian (integer nDof)
computes the body Jacobian matrix of the coordinate frame
function Jac = computeSpatialJacobian (integer nDof)
computes the spatial Jacobian matrix of the coordinate frame
Static Public Member Functions
static function gst = RPToHomogeneous (R, p)
Convert a rotation + translation to a homogeneous matrix.
static function adj = RigidAdjoint (g)
rigid adjoint matrix from the homonegeous matrix
static function R = RigidOrientation (g)
extract the rigid orientation from the homogeneous transformation matrix
static function p = RigidPosition (g)
extract the rigid position from the homogeneous transformation matrix
static function s = AxisToSkew (p)
converts the axis vector to a skew matrix
Public Attributes
char Name
The name of the coordinate frame.
CoordinateFrame Reference
The parent reference coordinate frame.
rowvec Offset
The offset of the origin of the frame from the origin of the reference frame.
matrix R
The rotation matrix of the frame w.r.t. the reference frame.
matrix gst0
The homogeneous transformation from the base coordinate.
Public Attributes inherited from handle
addlistener
Creates a listener for the specified event and assigns a callback function to execute when the event occurs.
notify
Broadcast a notice that a specific event is occurring on a specified handle object or array of handle objects.
delete
Handle object destructor method that is called when the object's lifecycle ends.
disp
Handle object disp method which is called by the display method. See the MATLAB disp function.
display
Handle object display method called when MATLAB software interprets an expression returning a handle object that is not terminated by a semicolon. See the MATLAB display function.
findobj
Finds objects matching the specified conditions from the input array of handle objects.
findprop
Returns a meta.property objects associated with the specified property name.
fields
Returns a cell array of string containing the names of public properties.
fieldnames
Returns a cell array of string containing the names of public properties. See the MATLAB fieldnames function.
isvalid
Returns a logical array in which elements are true if the corresponding elements in the input array are valid handles. This method is Sealed so you cannot override it in a handle subclass.
eq
Relational functions example. See details for more information.
transpose
Transposes the elements of the handle object array.
permute
Rearranges the dimensions of the handle object array. See the MATLAB permute function.
reshape
hanges the dimensions of the handle object array to the specified dimensions. See the MATLAB reshape function.
sort
ort the handle objects in any array in ascending or descending order.
Detailed Description
A kinematic coordinate frame class.
Copyright (c) 2016-2017, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file CoordinateFrame.m.
Constructor & Destructor Documentation
CoordinateFrame.CoordinateFrame (varargin)
The class constructor function.
Parameters
varargin variable nama-value pair input arguments, in detail:
CoordinateFrame (Name, Reference, Offset, R)
Required Parameters for varargin:
Name the name of the frame
Reference the reference frame
Offset the offset of the origin
R the rotation matrix or the Euler angles
Definition at line 105 of file CoordinateFrame.m.
Referenced by ContactFrame.ContactFrame(), RigidBody.RigidBody(), and RigidJoint.RigidJoint().
Member Function Documentation
function s = CoordinateFrame.AxisToSkew (p) static
converts the axis vector to a skew matrix
Definition at line 269 of file CoordinateFrame.m.
References computeBodyJacobian(), computeCartesianPosition(), computeEulerAngle(), computeForwardKinematics(), and computeSpatialJacobian().
Referenced by RigidAdjoint().
function SymExpression Jac = CoordinateFrame.computeBodyJacobian (integer nDof)
computes the body Jacobian matrix of the coordinate frame
Parameters
nDof the total degrees of freedom of the system
Return values
Jac the Jacobian matrix
Definition at line 18 of file computeBodyJacobian.m.
References eval_math_fun().
Referenced by AxisToSkew().
function SymExpression pos = CoordinateFrame.computeCartesianPosition (rowvec p)
computes the cartesian position of a point p in the body (current) coordinate frame
Note
If (p) is not given, then returns the cartesian positions of the origin of the current coordinate frame.
Parameters
p the offset vector of the point in the current frame
Return values
pos the symbolic expression of the cartesian position
Definition at line 18 of file computeCartesianPosition.m.
References RigidPosition(), and RPToHomogeneous().
Referenced by AxisToSkew().
function SymExpression rpy = CoordinateFrame.computeEulerAngle ()
computes the Euler angles the body (current) coordinate frame in the world frame (base coordinate)
Return values
rpy the Euler (roll,pitch,yaw) angles of the frame
Definition at line 18 of file computeEulerAngle.m.
References RigidOrientation(), and handle.transpose.
Referenced by AxisToSkew().
function SymExpression g = CoordinateFrame.computeForwardKinematics ()
computes the forward kinematics transformation matrix of the coordinate frame
Return values
g the forward transformation matrix under the coordinate system
Definition at line 18 of file computeForwardKinematics.m.
References eval_math_fun().
Referenced by AxisToSkew().
function obj = CoordinateFrame.computeHomogeneousTransform ()
computes the homogeneous transformation matrix from the world coordinates
Generated fields of obj:
Definition at line 18 of file computeHomogeneousTransform.m.
References RPToHomogeneous().
Referenced by ContactFrame(), and setReference().
function SymExpression Jac = CoordinateFrame.computeSpatialJacobian (integer nDof)
computes the spatial Jacobian matrix of the coordinate frame
Parameters
nDof the total degrees of freedom of the system
Return values
Jac the Jacobian matrix
Definition at line 18 of file computeSpatialJacobian.m.
References eval_math_fun().
Referenced by AxisToSkew().
function obj = CoordinateFrame.ContactFrame (type)
convert a coordinate frame into a contact frame
Definition at line 169 of file CoordinateFrame.m.
References computeHomogeneousTransform(), setOffset(), setReference(), and setRotationMatrix().
function adj = CoordinateFrame.RigidAdjoint (g) static
rigid adjoint matrix from the homonegeous matrix
Definition at line 216 of file CoordinateFrame.m.
References AxisToSkew(), R, RigidOrientation(), and RigidPosition().
Referenced by RigidJoint.computeTwist().
function R = CoordinateFrame.RigidOrientation (g) static
extract the rigid orientation from the homogeneous transformation matrix
Definition at line 235 of file CoordinateFrame.m.
Referenced by computeEulerAngle(), and RigidAdjoint().
function p = CoordinateFrame.RigidPosition (g) static
extract the rigid position from the homogeneous transformation matrix
Definition at line 252 of file CoordinateFrame.m.
Referenced by computeCartesianPosition(), and RigidAdjoint().
function gst = CoordinateFrame.RPToHomogeneous (R, p) static
Convert a rotation + translation to a homogeneous matrix.
Definition at line 203 of file CoordinateFrame.m.
References R.
Referenced by computeCartesianPosition(), and computeHomogeneousTransform().
function obj = CoordinateFrame.setOffset (rowvec offset)
set the offset of the origin of the frame from the reference frame origin (in the reference frame)
Parameters
offset the offset vector
Generated fields of obj:
Definition at line 18 of file setOffset.m.
Referenced by ContactFrame().
function obj = CoordinateFrame.setReference (CoordinateFrame ref)
set the reference frame
Parameters
ref the reference frame object
Generated fields of obj:
Definition at line 18 of file setReference.m.
References computeHomogeneousTransform().
Referenced by ContactFrame().
function obj = CoordinateFrame.setRotationMatrix (rowvec|matrix r)
set the rotation matrix (R) of the frame w.r.t to the reference frame
Parameters
r the rotation matrix or Euler angles (in radian)
Generated fields of obj:
Definition at line 18 of file setRotationMatrix.m.
Referenced by ContactFrame().
Member Data Documentation
CoordinateFrame.gst0
The homogeneous transformation from the base coordinate.
Note
This property has the MATLAB attribute Hidden set to true.
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 88 of file CoordinateFrame.m.
CoordinateFrame.Name
The name of the coordinate frame.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 36 of file CoordinateFrame.m.
Referenced by RobotLinks.addContact().
CoordinateFrame.Offset
The offset of the origin of the frame from the origin of the reference frame.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 61 of file CoordinateFrame.m.
CoordinateFrame.R
The rotation matrix of the frame w.r.t. the reference frame.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 74 of file CoordinateFrame.m.
Referenced by RigidAdjoint(), and RPToHomogeneous().
CoordinateFrame.Reference
The parent reference coordinate frame.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 49 of file CoordinateFrame.m.
The documentation for this class was generated from the following files:
robotics/@CoordinateFrame/CoordinateFrame.m
robotics/@CoordinateFrame/computeBodyJacobian.m
robotics/@CoordinateFrame/computeCartesianPosition.m
robotics/@CoordinateFrame/computeEulerAngle.m
robotics/@CoordinateFrame/computeForwardKinematics.m
robotics/@CoordinateFrame/computeHomogeneousTransform.m
robotics/@CoordinateFrame/computeSpatialJacobian.m
robotics/@CoordinateFrame/setOffset.m
robotics/@CoordinateFrame/setReference.m
robotics/@CoordinateFrame/setRotationMatrix.m