FROST: RigidBodyModel Class Reference
RigidBodyModel Class Reference
A class with basic model descriptions and functionalities of the multi-link rigid-body robot platform.
Public Member Functions
RigidBodyModel (char config_file,struct base_dofs,char model_type)
The class constructor function.
function [ obj , mass , indices , indices , status , status , sva , obj , dofs , obj , obj , status ] = checkFlag (reload, obj, obj, link_names, obj, dof_names, obj, export_path, do_build, obj, export_path, do_build, obj, model, base_dofs, obj, obj, model, base_dofs, obj, obj, obj,char flag)
This function checks the flag in Mathematica's RobotModel package.
function [ matrix De , colvec He ] = calcNaturalDynamics (colvec qe,colvec dqe,logical useSVA)
This function compute the natural unconstrained dynamics of the rigid body model.
function obj = exportLineFunctions (varargin)
This function compile the symbolic expressions of the animation objects (kinematic) position and first order Jacobian.
Public Attributes
char Name
The unique name of the rigid body model.
char Type
The type of the model, it could be either planar or spatial.
char ConfigFile
The full path of the model configuration file.
struct Links
Represents the list of rigid body links.
struct Dof
A structure describes the configuration of the total degrees of freedom, including base coordinates.
struct BaseDof
Represents the list of rigid body joints The structur contains the configuration of the base coordinates, which normally does not conver in the URDF file.
double nDof
The total degrees of freedom of the model.
double nBaseDof
The dimension of the floating base coordinates.
rowvec qeIndices
The indexing vector of extended full coordiantes.
rowvec dqeIndices
The indexing vector of extended full coordiantes.
rowvec qIndices
The indexing vector of joint coordiantes.
rowvec dqIndices
The indexing vector of joint coordinate velocities.
rowvec qbIndices
The indexing vector of floating base coordiantes.
rowvec dqbIndices
The indexing vector of floating base coordinate velocities.
struct SVA
A model parameter structure constructed based on the requirement of the Spatial Vector Algebra (sva) package http://royfeatherstone.org/spatial/.
struct LineObjects
Animation Line objects.
Detailed Description
A class with basic model descriptions and functionalities of the multi-link rigid-body robot platform.
References
The descriptions of rigid body model is based on but not limited to the following resrouces
Richard Murray, Zexiang Li, and Shankar Sastry. "A Mathematical Introduction to Robotic Manipulation". 1994, CRC Press. http://www.cds.caltech.edu/~murray/mlswiki.
Roy Featherstones. "Rigid Body Dynamics Algorithm". Springer, 2008. http://royfeatherstone.org/spatial/
Author
Ayonga Hereid
Date
2016-09-26
New in 1.0:
(Ayonga Hereid, 2016-09-26) Migrated from old modelConfig class
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file RigidBodyModel.m.
Constructor & Destructor Documentation
RigidBodyModel.RigidBodyModel (char config_file, struct base_dofs, char model_type)
The class constructor function.
Note
To construct a rigid body model, a model URDF file must be specified.
The supported base joint types are
floating: This joint allows motion for all 6 degrees of freedom. (default axes: {Px,Py,Pz,Rx,Ry,Rz})
planar: This joint allows motion in a plane perpendicular to the axis. (default axes: {px,pz,r})
revolute: a hinge joint that rotates along the axis and has a limited range specified by the upper and lower limits. (default axes: r)
continuous: a continuous hinge joint that rotates around the axis and has no upper and lower limits. (default axes: r)
prismatic: a sliding joint that slides along the axis, and has a limited range specified by the upper and lower limits. (default axes: pz)
fixed: This is not really a joint because it cannot move. All degrees of freedom are locked. This type of joint does not require the axis, calibration, dynamics, limits or safety_controller. (default axes: [])
Note
Non-default axes configuration for the base jonits are prohibited in the current implementation, because it could cause many unexpected issues. The options are still left for the future extendability.
For more definition regarding the supported joint type, please see the URDF joint description at http://wiki.ros.org/urdf/XML/joint
Parameters
config_file the full path of the model configuration file.
base_dofs the base coordinates configuration of the model
model_type the type (spatial or planar) of the model. The model type is in fact only being used if SVA package is used
Required fields of sva:
NB — the number of bodies in the tree, including the fixed base. NB is also the number of joints plus the base coordinates, since we are interested in dynamics model in floating base coordinates.
parent — parent(i) is the body number of the parent of body i in the tree. The fixed base is defined to be body number 0; and the remaining bodies are numbered from 1 to NB in any order such that each body has a higher number than its parent (so parent(i) < i for all i). Joint i connects from body parent(i) to body i.
jtype — jtype{i} contains either the joint type code or the joint-descriptor data structure for joint i. Joint type codes are strings and joint descriptors are data structures containing a field called code and an optional second field called pars, the former containing the joint type code and the latter any parameters that are needed by that type of joint.
Xtree — Xtree{i} is the coordinate transform from the coordinate system of body parent(i) to the coordinate system of the predecessor frame of joint i (which is embedded in body parent(i)). The product of this transform with the joint transform for joint i, as calculated by jcalc, is the transform from body parent(i) coordinates to body i coordinates.
I — is the spatial or planar (as appropriate) inertia of body i, expressed in body i coordinates.
gravity — This is specifying the gravitational acceleration vector in base (body 0) coordinates. The dimension is either 2 or 3, depending on whether the underlying arithmetic is planar or spatial. If this field is omitted then a default value of [0;0;−9.81] is used in spatial models, and [0;-9.81] in planar models.
Required fields of base_dofs:
Optional fields of sva:
type — model type
Optional fields of base_dofs:
type — Specifies the type of the rigid body model.
lower — the lower limits of each base joints
upper — the upper limits of each base joints
velocity — the velocity limits of each base joints
axis — axes of each base joints. If not specified, then use default axes for each type.
Definition at line 279 of file RigidBodyModel.m.
References calcNaturalDynamics(), checkFlag(), exportLineFunctions(), and ros_load_urdf().
Member Function Documentation
function [ matrix De , colvec He ] = RigidBodyModel.calcNaturalDynamics (colvec qe, colvec dqe, logical useSVA)
This function compute the natural unconstrained dynamics of the rigid body model.
Parameters
qe the coordinate configuration
dqe the coordinate velocity
useSVA indicates whether to use SVA package to compute dynamics Default: false Return values:
De the inertia matrix
He the corilios and gravity term
Definition at line 18 of file calcNaturalDynamics.m.
Referenced by RigidBodyModel().
function logical status = RigidBodyModel.checkFlag (reload, obj, obj, link_names, obj, dof_names, obj, export_path, do_build, obj, export_path, do_build, obj, model, base_dofs, obj, obj, model, base_dofs, obj, obj, obj, char flag)
This function checks the flag in Mathematica's RobotModel package.
Parameters
flag a string of the flag
Return values
status returns the flag status.
Definition at line 18 of file checkFlag.m.
References str2mathstr().
Referenced by RigidBodyModel().
function obj = RigidBodyModel.exportLineFunctions (varargin)
This function compile the symbolic expressions of the animation objects (kinematic) position and first order Jacobian.
Attention
initialize(obj) must be called before run this function.
Definition at line 18 of file exportLineFunctions.m.
Referenced by RigidBodyModel().
Member Data Documentation
RigidBodyModel.BaseDof
Represents the list of rigid body joints The structur contains the configuration of the base coordinates, which normally does not conver in the URDF file.
The link structure contains the elements of joint specified in the URDF file.
Joints
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 126 of file RigidBodyModel.m.
RigidBodyModel.ConfigFile
The full path of the model configuration file.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 84 of file RigidBodyModel.m.
RigidBodyModel.Dof
A structure describes the configuration of the total degrees of freedom, including base coordinates.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 111 of file RigidBodyModel.m.
RigidBodyModel.dqbIndices
The indexing vector of floating base coordinate velocities.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 234 of file RigidBodyModel.m.
RigidBodyModel.dqeIndices
The indexing vector of extended full coordiantes.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 186 of file RigidBodyModel.m.
RigidBodyModel.dqIndices
The indexing vector of joint coordinate velocities.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 210 of file RigidBodyModel.m.
RigidBodyModel.LineObjects
Animation Line objects.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 262 of file RigidBodyModel.m.
RigidBodyModel.Links
Represents the list of rigid body links.
The link structure contains the elements of link specified in the URDF file.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 96 of file RigidBodyModel.m.
RigidBodyModel.Name
The unique name of the rigid body model.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 60 of file RigidBodyModel.m.
Referenced by KinematicGroup.compile(), Kinematics.compile(), and KinematicExpr.compile().
RigidBodyModel.nBaseDof
The dimension of the floating base coordinates.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 162 of file RigidBodyModel.m.
RigidBodyModel.nDof
The total degrees of freedom of the model.
It includes the dimensions of floating base coordinates if options.use_floating_base = true.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 147 of file RigidBodyModel.m.
Referenced by Domain.setAcutation(), and Guard.setResetMap().
RigidBodyModel.qbIndices
The indexing vector of floating base coordiantes.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 222 of file RigidBodyModel.m.
RigidBodyModel.qeIndices
The indexing vector of extended full coordiantes.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 174 of file RigidBodyModel.m.
RigidBodyModel.qIndices
The indexing vector of joint coordiantes.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 198 of file RigidBodyModel.m.
RigidBodyModel.SVA
A model parameter structure constructed based on the requirement of the Spatial Vector Algebra (sva) package http://royfeatherstone.org/spatial/.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 248 of file RigidBodyModel.m.
RigidBodyModel.Type
The type of the model, it could be either planar or spatial.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 72 of file RigidBodyModel.m.
Referenced by Guard.setResetMap().
The documentation for this class was generated from the following files:
model/@RigidBodyModel/RigidBodyModel.m
model/@RigidBodyModel/calcNaturalDynamics.m
model/@RigidBodyModel/checkFlag.m
model/@RigidBodyModel/exportLineFunctions.m