FROST: KinematicGroup Class Reference
KinematicGroup Class Reference
Defines a group of kinematic constraint that expressed as functions of other kinematic constraints.
Public Member Functions
KinematicGroup (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic function.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function obj = addKinematic (cell kin)
add kinematic objects to the group
function obj = removeKinematic (Kinematics kin)
remove kinematic objects from the group
function obj = updateIndex ()
Generates indices for the kinematic objects in the group.
function index = getIndex (char kin)
Returns the index of the kinematic object in the group.
function pos = getPosition (char kin)
Returns the position of the kinematic object in the group.
Public Member Functions inherited from Kinematics
Kinematics (varargin)
The constructor function.
function dim = getDimension ()
Returns the dimension of the kinematic function. By default, we assume the dimension of a kinematic function is 1, unless this method is overloaded by subclasses.
function status = compile (RigidBodyModel model,logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
function status = export (char export_path,logical do_build)
Export the symbolic expression of functions to C/C++ source files and build them as MEX files.
function print (file)
This function prints out the symbolic expression from the Mathematica to Matlab screen.
Public Attributes
struct KinGroupTable
The group of Kinematic constraints objects represented by an array of structures.
Public Attributes inherited from Kinematics
char Name
An unique name string that determines the symbolic expressions of the kinematic constraint in Mathematica.
logical Linearize
A flag whether linearize the output or not. The actual output will be the linearization of the functioni at q = 0.
char Prefix
A prefix for the function to be exported.
char Suffix
A suffix for the function to be exported.
struct Symbols
A actual symbol that represents the symbolic expression of the kinematic constraint in Mathematica.
struct Funcs
File names of the kinematic functions.
Additional Inherited Members
Protected Member Functions inherited from Kinematics
function cmd = getKinMathCommand (model)
This function returns he Mathematica command to compile the symbolic expression for the kinematic constraint.
function cmd = getJacMathCommand (model)
This function returns the Mathematica command to compile the symbolic expression for the kinematic constraint's Jacobian.
function cmd = getJacDotMathCommand ()
The function returns the Mathematica command to compile the symbolic expressions for the time derivative of the kinematic constraint's Jacobian.
Protected Attributes inherited from Kinematics
logical LinearizeFlagChanged
A flag for whether the 'Linearize' option is changed.
Detailed Description
Defines a group of kinematic constraint that expressed as functions of other kinematic constraints.
Author
Ayonga Hereid
Date
2016-09-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file KinematicGroup.m.
Constructor & Destructor Documentation
KinematicGroup.KinematicGroup (varargin)
The constructor function.
See also
struct
Parameters
varargin it could be a struct has the same fields as this class or name-value pair arguments. The syntax would be similar to construct a struct in Matlab. Use either
kin = Kinematics('Prop1', Value1,'Prop2',Value2,...);
or
kin = Kinematics(KinStruct);
See also
Kinematics
Required fields of KinGroupTable:
Name — the name of the kinematic object
KinObj — the kinematic object
Index — the indices of the kinematic object in the group
Definition at line 63 of file KinematicGroup.m.
References Kinematics.Kinematics().
Member Function Documentation
function obj = KinematicGroup.addKinematic (cell kin)
add kinematic objects to the group
Parameters
kin one or a group of kinematic objects to be added to the existing group
Definition at line 18 of file addKinematic.m.
References Kinematics.Name, and updateIndex().
Referenced by getDimension().
function status = KinematicGroup.compile (RigidBodyModel model, logical re_load)
This function computes the symbolic expression of the kinematics constraints in Mathematica.
Parameters
model the rigid body model
re_load re-evaluate the symbolic expression
Required fields of model:
Definition at line 18 of file compile.m.
References cell2tensor(), check_var_exist(), eval_math(), and RigidBodyModel.Name.
Referenced by getDimension().
function dim = KinematicGroup.getDimension ()
Returns the dimension of the kinematic function.
Definition at line 110 of file KinematicGroup.m.
References addKinematic(), compile(), getIndex(), getPosition(), removeKinematic(), and updateIndex().
Referenced by updateIndex().
function index = KinematicGroup.getIndex (char kin)
Returns the index of the kinematic object in the group.
Parameters
kin the name of the kinematic object or the kinematic object
Definition at line 18 of file getIndex.m.
References getPosition().
Referenced by getDimension().
function pos = KinematicGroup.getPosition (char kin)
Returns the position of the kinematic object in the group.
Parameters
kin the name of the kinematic object or the kinematic object
Required fields of kin:
Definition at line 18 of file getPosition.m.
Referenced by getDimension(), and getIndex().
function obj = KinematicGroup.removeKinematic (Kinematics kin)
remove kinematic objects from the group
Parameters
kin one or a group of kinematic objects or names to be removed from the existing group
Definition at line 18 of file removeKinematic.m.
References Kinematics.Name, and updateIndex().
Referenced by getDimension().
function obj = KinematicGroup.updateIndex ()
Generates indices for the kinematic objects in the group.
Definition at line 18 of file updateIndex.m.
References getDimension().
Referenced by addKinematic(), getDimension(), and removeKinematic().
Member Data Documentation
KinematicGroup.KinGroupTable
The group of Kinematic constraints objects represented by an array of structures.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 42 of file KinematicGroup.m.
The documentation for this class was generated from the following files:
kinematics/@KinematicGroup/KinematicGroup.m
kinematics/@KinematicGroup/addKinematic.m
kinematics/@KinematicGroup/compile.m
kinematics/@KinematicGroup/getIndex.m
kinematics/@KinematicGroup/getPosition.m
kinematics/@KinematicGroup/removeKinematic.m
kinematics/@KinematicGroup/updateIndex.m