FROST: utils/mathlink/eval_math_fun.m File Reference
eval_math_fun.m File Reference
Evaluate symbolic function eval_math_fun(fun,x1,...,xn) evaluates the symbolic function 'fun' at the given arguments x1, ..., xn.
Functions
function ret = eval_math_fun (char fun,cell args,cell opts,varargin varargin)
Evaluate symbolic function eval_math_fun(fun,x1,...,xn) evaluates the symbolic function 'fun' at the given arguments x1, ..., xn.
Detailed Description
Evaluate symbolic function eval_math_fun(fun,x1,...,xn) evaluates the symbolic function 'fun' at the given arguments x1, ..., xn.
Definition in file eval_math_fun.m.
Function Documentation
function ret = eval_math_fun (char fun, cell args, cell opts, varargin varargin)
Evaluate symbolic function eval_math_fun(fun,x1,...,xn) evaluates the symbolic function 'fun' at the given arguments x1, ..., xn.
Author
ayonga
Date
2017-03-23
Example
eval_math_fun(RandomReal,{10})
ans =
4.0980963150223175
Parameters
fun the name of the Mathematica function
args the input argument of the Mathematica function
opts the option argument of the Mathematica function
varargin the option argument of the SymExpression object
Definition at line 17 of file eval_math_fun.m.
References cell2tensor(), and struct2assoc().
Referenced by CoordinateFrame.computeBodyJacobian(), CoordinateFrame.computeForwardKinematics(), CoordinateFrame.computeSpatialJacobian(), RobotLinks.configureDynamics(), RobotLinks.getBodyJacobian(), RobotLinks.getCartesianPosition(), RobotLinks.getComPosition(), RobotLinks.getEulerAngles(), RobotLinks.getSpatialJacobian(), and VirtualConstraint.VirtualConstraint().