FROST: utils/mathlink/eval_math.m File Reference
eval_math.m File Reference
A wrapper function that calls the mathlink function to evaluate the expression specified by expr.
Functions
function char ret = eval_math (char expr,char flag, val)
A wrapper function that calls the mathlink function to evaluate the expression specified by expr.
Detailed Description
A wrapper function that calls the mathlink function to evaluate the expression specified by expr.
Definition in file eval_math.m.
Function Documentation
function char ret = eval_math (char expr, char flag, val)
A wrapper function that calls the mathlink function to evaluate the expression specified by expr.
Author
ayonga
Date
2016-11-23
Author
Ayonga Hereid ayong.nosp@m.a27@.nosp@m.gmail.nosp@m..com
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Parameters
expr a string of Mathematica expression
flag a char suggests the operation direction
val value to be assigned
Return values
ret the return value of the mathematica evaluation if no error detected.
Definition at line 17 of file eval_math.m.
Referenced by SymExpression.char(), check_var_exist(), clear_symbol(), RobotLinks.configure(), SymExpression.display(), SymExpression.double(), SymExpression.eq(), SymExpression.islist(), SymExpression.ne(), SymExpression.privToCell(), SymExpression.size(), SymVariable.subsasgn(), SymExpression.subsasgn(), SymVariable.subsref(), SymExpression.subsref(), SymExpression.SymExpression(), and SymVariable.SymVariable().