FROST: utils/mathlink/general2math.m File Reference
general2math.m File Reference
Convert a general expression to a Mathematica expression.
Functions
function expr = general2math (x, varargin)
Convert a general expression to a Mathematica expression.
Detailed Description
Convert a general expression to a Mathematica expression.
Definition in file general2math.m.
Function Documentation
function expr = general2math (x, varargin)
Convert a general expression to a Mathematica expression.
Author
ayonga
Date
2016-11-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file general2math.m.
References cell2tensor(), mat2math(), num2mathstr(), str2mathstr(), and struct2assoc().
Referenced by cell2tensor(), struct2assoc(), SymVariable.subsasgn(), SymExpression.subsasgn(), and SymExpression.SymExpression().