FROST: utils/mathlink/mat2math.m File Reference
mat2math.m File Reference
Converts a 2-D matrix to a string that will be read as a matrix (tensor) in Mathematica.
Functions
function expr = mat2math (A, varargin)
Converts a 2-D matrix to a string that will be read as a matrix (tensor) in Mathematica.
Detailed Description
Converts a 2-D matrix to a string that will be read as a matrix (tensor) in Mathematica.
Definition in file mat2math.m.
Function Documentation
function expr = mat2math (A, varargin)
Converts a 2-D matrix to a string that will be read as a matrix (tensor) in Mathematica.
Author
ayonga
Date
2016-11-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file mat2math.m.
References implode().
Referenced by general2math(), HybridTrajectoryOptimization.genericSymFunctions(), KinematicContact.getJacMathCommand(), and KinematicContact.getKinMathCommand().