FROST: utils/mathlink/str2mathstr.m File Reference
str2mathstr.m File Reference
Converts a Matlab string to a Mathematica string.
Functions
function expr = str2mathstr (s, varargin)
Converts a Matlab string to a Mathematica string.
Detailed Description
Converts a Matlab string to a Mathematica string.
Definition in file str2mathstr.m.
Function Documentation
function expr = str2mathstr (s, varargin)
Converts a Matlab string to a Mathematica string.
Author
ayonga
Date
2016-11-23
varargin: conversion options. ConvertString: If false, this will keep the character as it is, which will be considered as symbolic variables in Mathematica
Default:
true
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Parameters
varargin
Definition at line 17 of file str2mathstr.m.
Referenced by RigidBodyModel.checkFlag(), Kinematics.export(), VirtualConstrDomain.export(), KinematicExpr.export(), SymFunction.export(), and general2math().