FROST: utils/general/str_index.m File Reference
str_index.m File Reference
Functions
function indices = str_index (needle, haystack)
Function Documentation
function indices = str_index (needle, haystack)
Definition at line 17 of file str_index.m.
Referenced by HybridTrajectoryOptimization.addJumpConstraint(), RobotLinks.configure(), RobotLinks.configureKinematics(), RobotLinks.getJointIndices(), RobotLinks.getLinkIndices(), TrajectoryOptimization.removeConstraint(), TrajectoryOptimization.removeCost(), and TrajectoryOptimization.removeVariable().