FROST: utils/mathlink/struct2assoc.m File Reference
struct2assoc.m File Reference
Converts a Matlab structure into a string that describes an expression for Mathematica association.
Functions
function str = struct2assoc (s, varargin)
Converts a Matlab structure into a string that describes an expression for Mathematica association.
Detailed Description
Converts a Matlab structure into a string that describes an expression for Mathematica association.
Definition in file struct2assoc.m.
Function Documentation
function str = struct2assoc (s, varargin)
Converts a Matlab structure into a string that describes an expression for Mathematica association.
Author
ayonga
Date
2016-11-23
Copyright (c) 2016, AMBER Lab All right reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted only in compliance with the BSD 3-Clause license, see http://www.opensource.org/licenses/bsd-license.php
Definition at line 17 of file struct2assoc.m.
References cell2tensor(), general2math(), implode(), and str2mathstr().
Referenced by eval_math_fun(), and general2math().