classdef AtlasRobot < RobotLinks
    
    properties
        ContactPoints
        lt = 0.1728;
        lh = 0.082;
        wf = 0.1524;
        hf = -0.07645;
    end
    
    methods
        
        function obj = AtlasRobot(urdf)
            
            base = get_base_dofs('floating');
            
            limits = [base.Limit];
            
            [limits.lower] = deal(-0.6, -0.2, 0.7, -0.1, -0.5, -0.1);
            [limits.upper] = deal(0.3, 0.2, 0.9, 0.1, 0.5, 0.1);
            [limits.velocity] = deal(1, 0.1, 0.5, 0.5, 0.5, 0.5);
            [limits.effort] = deal(0);
            for i=1:6
                base(i).Limit = limits(i);
            end
            
            obj = obj@RobotLinks(urdf,base);
            
            act_joints = obj.Joints(arrayfun(@(x)~isempty(x.Actuator),obj.Joints));
            act_joint_name = {act_joints.Name};
            n_act = numel(act_joints);
            actuators(n_act) =  struct('Inertia',0.001,'Ratio',1);
            [actuators.Inertia] = deal(1);
            [actuators.Ratio]   = deal(1);
            obj.configureActuator(act_joint_name,actuators); 
            
            %% define contact frames
            lt = obj.lt;
            lh = obj.lh;
            wf = obj.wf;
            hf = obj.hf;
            % right toe is a point on the r_foot link. However, its position is
            % defined on the reference coordinate frame of the r_foot link, not the
            % r_foot link frame (which coincidence with the CoM position of the
            % link, not the origin)
            % r_foot_link = obj.Links(getLinkIndices(obj, 'r_foot'));
            % r_foot_frame = r_foot_link.Reference;
            r_foot_frame = obj.Joints(getJointIndices(obj, 'r_leg_akx'));
            obj.ContactPoints.RightToe = CoordinateFrame(...
                'Name','RightToe',...
                'Reference',r_foot_frame,...
                'Offset',[lt, 0, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            obj.ContactPoints.RightHeel = CoordinateFrame(...
                'Name','RightHeel',...
                'Reference',r_foot_frame,...
                'Offset',[-lh, 0, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );            
            obj.ContactPoints.RightSole = CoordinateFrame(...
                'Name','RightSole',...
                'Reference',r_foot_frame,...
                'Offset',[0, 0, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            
            obj.ContactPoints.RightToeInside = CoordinateFrame(...
                'Name','RightToeInside',...
                'Reference',r_foot_frame,...
                'Offset',[lt, wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            obj.ContactPoints.RightHeelInside = CoordinateFrame(...
                'Name','RightHeelInside',...
                'Reference',r_foot_frame,...
                'Offset',[-lh, wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            obj.ContactPoints.RightSoleInside = CoordinateFrame(...
                'Name','RightSoleInside',...
                'Reference',r_foot_frame,...
                'Offset',[0, wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            
            obj.ContactPoints.RightToeOutside = CoordinateFrame(...
                'Name','RightToeOutside',...
                'Reference',r_foot_frame,...
                'Offset',[lt, -wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            obj.ContactPoints.RightHeelOutside = CoordinateFrame(...
                'Name','RightHeelOutside',...
                'Reference',r_foot_frame,...
                'Offset',[-lh, -wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            obj.ContactPoints.RightSoleOutside = CoordinateFrame(...
                'Name','RightSoleOutside',...
                'Reference',r_foot_frame,...
                'Offset',[0, -wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, so no rotation required
                );
            
            % l_foot_link = obj.Links(getLinkIndices(obj, 'l_foot'));
            % l_foot_frame = l_foot_link.Reference;
            l_foot_frame = obj.Joints(getJointIndices(obj, 'l_leg_akx'));
            obj.ContactPoints.LeftToe = CoordinateFrame(...
                'Name','LeftToe',...
                'Reference',l_foot_frame,...
                'Offset',[lt, 0, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            obj.ContactPoints.LeftHeel = CoordinateFrame(...
                'Name','LeftHeel',...
                'Reference',l_foot_frame,...
                'Offset',[-lh, 0, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            obj.ContactPoints.LeftSole = CoordinateFrame(...
                'Name','LeftSole',...
                'Reference',l_foot_frame,...
                'Offset',[0, 0, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            
            obj.ContactPoints.LeftToeInside = CoordinateFrame(...
                'Name','LeftToeInside',...
                'Reference',l_foot_frame,...
                'Offset',[lt, -wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            obj.ContactPoints.LeftHeelInside = CoordinateFrame(...
                'Name','LeftHeelInside',...
                'Reference',l_foot_frame,...
                'Offset',[-lh, -wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            obj.ContactPoints.LeftSoleInside = CoordinateFrame(...
                'Name','LeftSoleInside',...
                'Reference',l_foot_frame,...
                'Offset',[0, -wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            
            obj.ContactPoints.LeftToeOutside = CoordinateFrame(...
                'Name','LeftToeOutside',...
                'Reference',l_foot_frame,...
                'Offset',[lt, wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            obj.ContactPoints.LeftHeelOutside = CoordinateFrame(...
                'Name','LeftHeelOutside',...
                'Reference',l_foot_frame,...
                'Offset',[-lh, wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
            obj.ContactPoints.LeftSoleOutside = CoordinateFrame(...
                'Name','LeftSoleOutside',...
                'Reference',l_foot_frame,...
                'Offset',[0, wf/2, hf],...
                'R',[0,0,0]... % z-axis is the normal axis, y-axis is the tangential axis, so no rotation required
                );
        end
    end
    
    
end