function ret = poly_value_bezier(t,a)
    t0 = (1 - t) .^ 6;
    t1 = 6 .* t .* (1 - t) .^ 5;
    t2 = 15 .* t .^ 2 .* (1 - t) .^ 4;
    t3 = 20 .* t .^ 3 .* (1 - t) .^ 3;
    t4 = 15 .* t .^ 4 .* (1 - t) .^ 2;
    t5 = 6 .* t .^ 5 .* (1 - t);
    t6 = t .^ 6;
    totalsum = a(1) * t0 + ...
               a(2) * t1 + ...
               a(3) * t2 + ...
               a(4) * t3 + ...
               a(5) * t4 + ...
               a(6) * t5 + ...
               a(7) * t6;
    ret = totalsum;
end