classdef Atlas < RigidBodyModel
    %ATLAS Model
    
    properties
        Contacts
        
        FixedDofs
        
        Kins
        
    end
    
    methods
        
        function obj = Atlas(urdf)
            
            
            obj = obj@RigidBodyModel(urdf);
            
            % potential contact points
            obj.Contacts = struct();
            
            obj.Contacts.LeftFoot = KinematicContact('Name','LeftFoot');
            obj.Contacts.LeftFoot.ParentLink = 'l_foot';
            obj.Contacts.LeftFoot.Offset = [0.0, 0, -0.07645];
            obj.Contacts.LeftFoot.NormalAxis = 'z';
            obj.Contacts.LeftFoot.ContactType = 'PlanarContactWithFriction';
            obj.Contacts.LeftFoot.ModelType = obj.Type;
            obj.Contacts.LeftFoot.Mu = 0.5;
            obj.Contacts.LeftFoot.Geometry = {'x',[0.0625,0.0625];
                'y',[0.178,0.082]};
            
            obj.Contacts.RightFoot = KinematicContact('Name','RightFoot');
            obj.Contacts.RightFoot.ParentLink = 'r_foot';
            obj.Contacts.RightFoot.Offset = [0.0, 0, -0.07645];
            obj.Contacts.RightFoot.NormalAxis = 'z';
            obj.Contacts.RightFoot.ContactType = 'PlanarContactWithFriction';
            obj.Contacts.RightFoot.ModelType = obj.Type;
            obj.Contacts.RightFoot.Mu = 0.5;
            obj.Contacts.RightFoot.Geometry = {'x',[0.0625,0.0625];
                'y',[0.178,0.082]};
            
            fixed_joints = obj.Joints(strcmp('fixed',{obj.Joints.type}));
            obj.FixedDofs = cell(1, numel(fixed_joints));
            for i=1:numel(fixed_joints)
                obj.FixedDofs{i} = KinematicDof('Name',regexprep(fixed_joints(i).name,'_',''),...
                    'DofName',fixed_joints(i).name);                
            end
            
            % kinematic position
            Kins = struct();
            
            LeftHipPosX = KinematicPosition('Name', 'LeftHipPosX',...
                'ParentLink','l_uleg',...
                'Axis','x',...
                'Offset',[0,0,0]);
            RightHipPosX = KinematicPosition('Name', 'RightHipPosX',...
                'ParentLink','r_uleg',...
                'Axis','x',...
                'Offset',[0,0,0]);
            
            LeftHipPosZ = KinematicPosition('Name', 'LeftHipPosZ',...
                'ParentLink','l_uleg',...
                'Axis','z',...
                'Offset',[0,0,0]);
            RightHipPosZ = KinematicPosition('Name', 'RightHipPosZ',...
                'ParentLink','r_uleg',...
                'Axis','z',...
                'Offset',[0,0,0]);
            
            
            LeftAnklePosX = KinematicPosition('Name', 'LeftAnklePosX',...
                'ParentLink','l_talus',...
                'Axis','x',...
                'Offset',[0,0,0]);
            RightAnklePosX = KinematicPosition('Name', 'RightAnklePosX',...
                'ParentLink','r_talus',...
                'Axis','x',...
                'Offset',[0,0,0]);
            
            LeftAnklePosZ = KinematicPosition('Name', 'LeftAnklePosZ',...
                'ParentLink','l_talus',...
                'Axis','z',...
                'Offset',[0,0,0]);
            RightAnklePosZ = KinematicPosition('Name', 'RightAnklePosZ',...
                'ParentLink','r_talus',...
                'Axis','z',...
                'Offset',[0,0,0]);
            
            LeftFootPosX = KinematicPosition('Name', 'LeftFootPosX',...
                'ParentLink','l_foot',...
                'Axis','x',...
                'Offset',[0.0, 0, -0.07645]);
            RightFootPosX = KinematicPosition('Name', 'RightFootPosX',...
                'ParentLink','r_foot',...
                'Axis','x',...
                'Offset',[0.0, 0, -0.07645]);
            
            Kins.LeftFootPosZ = KinematicPosition('Name', 'LeftFootPosZ',...
                'ParentLink','l_foot',...
                'Axis','z',...
                'Offset',[0.0, 0, -0.07645]);
            Kins.RightFootPosZ = KinematicPosition('Name', 'RightFootPosZ',...
                'ParentLink','r_foot',...
                'Axis','z',...
                'Offset',[0.0, 0, -0.07645]);
            
            LeftHeelPosZ = KinematicPosition('Name', 'LeftHeelPosZ',...
                'ParentLink','l_foot',...
                'Axis','z',...
                'Offset',[-0.04626, 0, -0.07645]);
            RightHeelPosZ = KinematicPosition('Name', 'RightHeelPosZ',...
                'ParentLink','r_foot',...
                'Axis','z',...
                'Offset',[-0.04626, 0, -0.07645]);
            LeftToePosZ = KinematicPosition('Name', 'LeftToePosZ',...
                'ParentLink','l_foot',...
                'Axis','z',...
                'Offset',[0.1728, 0, -0.07645]);
            RightToePosZ = KinematicPosition('Name', 'RightToePosZ',...
                'ParentLink','r_foot',...
                'Axis','z',...
                'Offset',[0.1728, 0, -0.07645]);
            RightSoleInsidePosZ = KinematicPosition('Name', 'RightSoleInsidePosZ',...
                'ParentLink','r_foot',...
                'Axis','z',...
                'Offset',[0, 0.075, -0.07645]);
            RightSoleOutsidePosZ = KinematicPosition('Name', 'RightSoleOutsidePosZ',...
                'ParentLink','r_foot',...
                'Axis','z',...
                'Offset',[0, -0.075, -0.07645]);
            LeftSoleOutsidePosZ = KinematicPosition('Name', 'LeftSoleOutsidePosZ',...
                'ParentLink','l_foot',...
                'Axis','z',...
                'Offset',[0, 0.075, -0.07645]);
            LeftSoleInsidePosZ = KinematicPosition('Name', 'LeftSoleInsidePosZ',...
                'ParentLink','l_foot',...
                'Axis','z',...
                'Offset',[0, -0.075, -0.07645]);
            
            LeftHeelPosY = KinematicPosition('Name', 'LeftHeelPosY',...
                'ParentLink','l_foot',...
                'Axis','y',...
                'Offset',[-0.04626, 0, -0.07645]);
            RightHeelPosY = KinematicPosition('Name', 'RightHeelPosY',...
                'ParentLink','r_foot',...
                'Axis','y',...
                'Offset',[-0.04626, 0, -0.07645]);
            LeftToePosY = KinematicPosition('Name', 'LeftToePosY',...
                'ParentLink','l_foot',...
                'Axis','y',...
                'Offset',[0.1728, 0, -0.07645]);
            RightToePosY = KinematicPosition('Name', 'RightToePosY',...
                'ParentLink','r_foot',...
                'Axis','y',...
                'Offset',[0.1728, 0, -0.07645]);
            
            % velocity outputs
            Kins.LeftDeltaPhip = KinematicExpr('Name', 'LeftDeltaPhip',...
                'Linearize', true,...
                'Dependents', {{LeftHipPosX, LeftFootPosX}},...
                'Expression', 'LeftHipPosX - LeftFootPosX');
            Kins.RightDeltaPhip = KinematicExpr('Name', 'RightDeltaPhip',...
                'Linearize', true,...
                'Dependents', {{RightHipPosX, RightFootPosX}},...
                'Expression', 'RightHipPosX - RightFootPosX');
            
            % phase variables
            Kins.RightTau = KinematicExpr('Name', 'RightTau');
            Kins.RightTau.Dependents = {Kins.RightDeltaPhip};
            Kins.RightTau.Expression = '(RightDeltaPhip - p[2])/(p[1] - p[2])';
            Kins.RightTau.Parameters = struct('Name','p','Dimension',2);
            
            Kins.LeftTau = KinematicExpr('Name', 'LeftTau');
            Kins.LeftTau.Dependents = {Kins.LeftDeltaPhip};
            Kins.LeftTau.Expression = '(LeftDeltaPhip - p[2])/(p[1] - p[2])';
            Kins.LeftTau.Parameters = struct('Name','p','Dimension',2);
            
            % position outputs
            Kins.LeftAnkleRoll = KinematicDof('Name','LeftAnkleRoll',...
                'DofName','l_leg_akx');
            Kins.RightAnkleRoll = KinematicDof('Name','RightAnkleRoll',...
                'DofName','r_leg_akx');
            
            Kins.LeftHipRoll = KinematicDof('Name','LeftHipRoll',...
                'DofName','l_leg_hpx');
            Kins.RightHipRoll = KinematicDof('Name','RightHipRoll',...
                'DofName','r_leg_hpx');
            
            Kins.LeftAnklePitch = KinematicDof('Name','LeftAnklePitch',...
                'DofName','l_leg_aky');
            Kins.RightAnklePitch = KinematicDof('Name','RightAnklePitch',...
                'DofName','r_leg_aky');
            
            Kins.LeftKneePitch = KinematicDof('Name','LeftKneePitch',...
                'DofName','l_leg_kny');
            Kins.RightKneePitch = KinematicDof('Name','RightKneePitch',...
                'DofName','r_leg_kny');
            
            Kins.LeftHipPitch = KinematicDof('Name','LeftHipPitch',...
                'DofName','l_leg_hpy');
            Kins.RightHipPitch = KinematicDof('Name','RightHipPitch',...
                'DofName','r_leg_hpy');
            
            Kins.LeftTorsoPitch = KinematicExpr('Name','LeftTorsoPitch',...
                'Dependents',{{Kins.LeftAnklePitch, Kins.LeftKneePitch, Kins.LeftHipPitch}},...
                'Expression','- LeftAnklePitch - LeftKneePitch - LeftHipPitch');
            Kins.RightTorsoPitch = KinematicExpr('Name','RightTorsoPitch',...
                'Dependents',{{Kins.RightAnklePitch, Kins.RightKneePitch, Kins.RightHipPitch}},...
                'Expression','- RightAnklePitch - RightKneePitch - RightHipPitch');
            
            Kins.LeftTorsoRoll = KinematicExpr('Name','LeftTorsoRoll',...
                'Dependents',{{Kins.LeftAnkleRoll, Kins.LeftHipRoll}},...
                'Expression','- LeftAnkleRoll - LeftHipRoll');
            Kins.RightTorsoRoll = KinematicExpr('Name','RightTorsoRoll',...
                'Dependents',{{Kins.RightAnkleRoll, Kins.RightHipRoll}},...
                'Expression','- RightAnkleRoll - RightHipRoll');
            
            Kins.LeftHipYaw = KinematicDof('Name','LeftHipYaw',...
                'DofName','l_leg_hpz');
            Kins.RightHipYaw = KinematicDof('Name','RightHipYaw',...
                'DofName','r_leg_hpz');
   
            Kins.RightLinNSlope = KinematicExpr('Name', 'RightLinNSlope',...
                'Linearize', true,...
                'Dependents',{{RightAnklePosX, RightHipPosX, RightAnklePosZ, RightHipPosZ}},...
                'Expression','(RightAnklePosX - RightHipPosX) / (RightAnklePosZ - RightHipPosZ)');
            
            Kins.LeftLinNSlope = KinematicExpr('Name', 'LeftLinNSlope',...
                'Linearize', true,...
                'Dependents',{{LeftAnklePosX, LeftHipPosX, LeftAnklePosZ, LeftHipPosZ}},...
                'Expression','(LeftAnklePosX - LeftHipPosX) / (LeftAnklePosZ - LeftHipPosZ)');
    
            Kins.RightLegRoll = KinematicExpr('Name','RightLegRoll',...
                'Dependents',{{Kins.LeftHipRoll, Kins.RightHipRoll}},...
                'Expression','LeftHipRoll - RightHipRoll');
            Kins.LeftLegRoll = KinematicExpr('Name','LeftLegRoll',...
                'Dependents',{{Kins.RightHipRoll, Kins.LeftHipRoll}},...
                'Expression','RightHipRoll - LeftHipRoll');
            
            Kins.RightFootRoll = KinematicExpr('Name','RightFootRoll',...
                'Dependents',{{RightSoleInsidePosZ, RightSoleOutsidePosZ}},...
                'Expression','RightSoleInsidePosZ - RightSoleOutsidePosZ');
            Kins.RightFootPitch = KinematicExpr('Name','RightFootPitch',...
                'Dependents',{{RightHeelPosZ, RightToePosZ}},...
                'Expression','RightHeelPosZ - RightToePosZ');
            Kins.RightFootYaw = KinematicExpr('Name','RightFootYaw',...
                'Dependents',{{RightHeelPosY, RightToePosY}},...
                'Expression','RightHeelPosY - RightToePosY');
            
            Kins.LeftFootRoll = KinematicExpr('Name','LeftFootRoll',...
                'Dependents',{{LeftSoleInsidePosZ, LeftSoleOutsidePosZ}},...
                'Expression','LeftSoleInsidePosZ - LeftSoleOutsidePosZ');
            Kins.LeftFootPitch = KinematicExpr('Name','LeftFootPitch',...
                'Dependents',{{LeftHeelPosZ, LeftToePosZ}},...
                'Expression','LeftHeelPosZ - LeftToePosZ');
            Kins.LeftFootYaw = KinematicExpr('Name','LeftFootYaw',...
                'Dependents',{{LeftHeelPosY, LeftToePosY}},...
                'Expression','LeftHeelPosY - LeftToePosY');
            
            obj.Kins = Kins;
        end
    end
    
end

